-- ═══════════════════════════════════════════════════════════════════════════
-- V067 — a refund raised against a specific transaction
--
--   A refund is usually owed against a payment the University actually took:
--   an overpayment, a duplicate after a timeout, a withdrawal after fees. This
--   lets the officer name that transaction's reference on the refund, so the
--   refund is traceable to the receipt it reverses. When a source is named the
--   database checks it is a payment this portal confirmed, and refuses a refund
--   larger than what was paid on it — money cannot be refunded that never came
--   in. Free-form refunds (a sponsor's off-portal over-remittance) still work:
--   the source is optional. The maker–checker rule of V043 is unchanged.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

ALTER TABLE finance.refund ADD COLUMN IF NOT EXISTS source_reference text NULL;

-- recreate propose_refund with the optional source reference as a trailing,
-- defaulted argument, so the existing seven-argument callers keep working
DROP FUNCTION IF EXISTS finance.propose_refund(uuid, text, text, numeric, text, text, text);

CREATE OR REPLACE FUNCTION finance.propose_refund(p_student uuid, p_payer text, p_reason text, p_amount numeric,
                                                  p_bank text, p_account_name text, p_account_last4 text,
                                                  p_source text DEFAULT NULL)
RETURNS text
LANGUAGE plpgsql AS $$
DECLARE who uuid := nullif(current_setting('moaum.actor_id', true), '')::uuid; v_ref text; v_src text; st record;
BEGIN
    IF who IS NULL THEN RAISE EXCEPTION 'a refund is raised by a person' USING ERRCODE = '23514'; END IF;
    IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'a refund is for an amount' USING ERRCODE = '23514'; END IF;
    IF p_payer IS NULL OR btrim(p_payer) = '' THEN RAISE EXCEPTION 'a refund names who it is paid to' USING ERRCODE = '23514'; END IF;
    IF p_reason IS NULL OR btrim(p_reason) = '' THEN RAISE EXCEPTION 'a refund carries the reason it is owed' USING ERRCODE = '23514'; END IF;

    v_src := nullif(upper(btrim(coalesce(p_source, ''))), '');
    IF v_src IS NOT NULL THEN
        SELECT * INTO st FROM finance.reference_state(v_src);
        IF st IS NULL OR st.amount IS NULL THEN
            RAISE EXCEPTION 'no transaction % was generated by this portal', v_src USING ERRCODE = '23503',
                HINT = 'Refund against a reference this portal issued; a slip from elsewhere is not a transaction here.';
        END IF;
        IF st.confirmed_at IS NULL THEN
            RAISE EXCEPTION 'transaction % is not a confirmed payment; there is nothing paid to refund', v_src USING ERRCODE = '23514';
        END IF;
        IF p_amount > st.amount THEN
            RAISE EXCEPTION 'a refund of NGN % exceeds the NGN % paid on %', p_amount, st.amount, v_src USING ERRCODE = '23514',
                HINT = 'Refund up to what was received on the transaction, not more.';
        END IF;
    END IF;

    v_ref := 'RF-' || to_char(current_date, 'YYYY') || '-' ||
             lpad(platform.next_number('REFUND', 'UNIVERSITY', to_char(current_date, 'YYYY'))::text, 4, '0');
    INSERT INTO finance.refund (reference, student_id, payer, reason, amount, bank_name, account_name, account_last4, proposed_by, source_reference)
    VALUES (v_ref, p_student, btrim(p_payer), btrim(p_reason), p_amount,
            nullif(btrim(coalesce(p_bank, '')), ''), nullif(btrim(coalesce(p_account_name, '')), ''), nullif(btrim(coalesce(p_account_last4, '')), ''), who, v_src);
    RETURN v_ref;
END $$;

COMMIT;
