-- ═══════════════════════════════════════════════════════════════════════════
-- V068 — reconciliation of confirmed payments against the bank
--
--   A payment the portal marks confirmed was confirmed by a gateway callback or
--   by the Bursary against a bank record. The audit directorate's job is to
--   check that each such transaction actually landed in the University's bank
--   account, and to flag the ones that did not - a settled callback with no
--   matching credit, an amount that differs from the statement. This records
--   that check per transaction: who validated it, whether it matched the bank,
--   the bank's own reference, and a note for any discrepancy. Both the audit
--   directorate and the Bursary may reconcile; nothing here moves money - it is
--   the independent attestation that the ledger and the bank agree.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE finance.payment_reconciliation (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    reference      text NOT NULL,
    result         text NOT NULL,
    bank_reference text NULL,
    note           text NULL,
    checked_by     uuid NOT NULL,
    checked_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_precon_result CHECK (result IN ('MATCHED','DISCREPANCY'))
);
CREATE INDEX ix_precon_reference ON finance.payment_reconciliation (reference, checked_at DESC);
SELECT audit.attach('finance.payment_reconciliation');

-- one check on one transaction: it must be a payment this portal confirmed
CREATE OR REPLACE FUNCTION finance.reconcile_payment(p_reference text, p_result text, p_bank_reference text, p_note text)
RETURNS uuid
LANGUAGE plpgsql AS $$
DECLARE who uuid := nullif(current_setting('moaum.actor_id', true), '')::uuid; v_ref text := upper(btrim(coalesce(p_reference, ''))); v_result text := upper(btrim(coalesce(p_result, ''))); st record; v_id uuid;
BEGIN
    IF who IS NULL THEN RAISE EXCEPTION 'a reconciliation is recorded by a person' USING ERRCODE = '23514'; END IF;
    IF v_result NOT IN ('MATCHED','DISCREPANCY') THEN RAISE EXCEPTION 'a reconciliation is matched, or a discrepancy' USING ERRCODE = '23514'; END IF;
    SELECT * INTO st FROM finance.reference_state(v_ref);
    IF st IS NULL OR st.amount IS NULL THEN
        RAISE EXCEPTION 'no transaction % was generated by this portal', v_ref USING ERRCODE = '23503';
    END IF;
    IF st.confirmed_at IS NULL THEN
        RAISE EXCEPTION 'transaction % is not a confirmed payment; there is nothing to reconcile', v_ref USING ERRCODE = '23514';
    END IF;
    IF v_result = 'DISCREPANCY' AND (p_note IS NULL OR btrim(p_note) = '') THEN
        RAISE EXCEPTION 'a discrepancy is recorded with a note saying what does not agree' USING ERRCODE = '23514';
    END IF;
    INSERT INTO finance.payment_reconciliation (reference, result, bank_reference, note, checked_by)
    VALUES (v_ref, v_result, nullif(btrim(coalesce(p_bank_reference, '')), ''), nullif(btrim(coalesce(p_note, '')), ''), who)
    RETURNING id INTO v_id;
    RETURN v_id;
END $$;

-- confirmed transactions in a window, each with its latest reconciliation state (if any)
CREATE OR REPLACE FUNCTION finance.reconciliation_list(p_from date, p_to date)
RETURNS TABLE (reference text, confirmed_at timestamptz, payer text, number text, purpose text, amount numeric,
               channel text, receipt_no text, session text, result text, bank_reference text, note text,
               checked_at timestamptz, checked_by_name text)
LANGUAGE sql STABLE AS $$
    SELECT d.reference, d.confirmed_at, d.payer, d.number, d.purpose, d.amount, d.channel, d.receipt_no, d.session,
           c.result, c.bank_reference, c.note, c.checked_at, p.surname || ', ' || p.given_names
      FROM finance.day_book(p_from, p_to) d
      LEFT JOIN LATERAL (
          SELECT * FROM finance.payment_reconciliation r WHERE r.reference = d.reference ORDER BY r.checked_at DESC LIMIT 1
      ) c ON true
      LEFT JOIN iam.person p ON p.id = c.checked_by
     ORDER BY d.confirmed_at DESC
$$;

COMMIT;
