-- ═══════════════════════════════════════════════════════════════════════════
-- V206 — the postgraduate programme catalogue (2025/2026 handbook)
--
--   The real School of Postgraduate Studies programmes, from the 2025/2026
--   Programmes & Admissions handbook, seeded into the shared ref.programme as
--   POST GRADUATE (beside the undergraduate ones). One programme per degree —
--   the handbook's specialization lists are recorded per student later, not as
--   separate programmes. Missing faculties and departments are created; the
--   award is stored structurally (pg_award) and whether it ends in a thesis
--   (pg_research). Programmes already on record (name + department) are left as
--   they are, so this does not duplicate the earlier seeds.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

SELECT set_config('moaum.actor_id', '00000000-0000-0000-0000-000000000000', true);
SELECT set_config('moaum.actor_office', 'academic', true);
SELECT set_config('moaum.reason', 'Postgraduate programme catalogue from the 2025/2026 handbook (V206)', true);

-- the real award set is wider than the V201 shortlist; keep pg_award as free text
ALTER TABLE ref.programme DROP CONSTRAINT IF EXISTS ck_prog_pg_award;

-- faculties the handbook names that are not yet on the register
INSERT INTO ref.faculty (code, name) VALUES
    ('CLS', 'Clinical Sciences'),
    ('CTR', 'Postgraduate Centres')
ON CONFLICT (code) DO NOTHING;

-- departments the handbook names that are not yet on the register
INSERT INTO ref.department (code, name, faculty_code) VALUES
    ('EPI', 'Epidemiology and Community Health', 'CLS'),
    ('OBG', 'Gynaecology and Obstetrics', 'CLS'),
    ('PDS', 'Peace and Development Studies', 'CTR'),
    ('CSP', 'Conservation Science and Practice', 'CTR'),
    ('GND', 'Gender Studies', 'CTR')
ON CONFLICT (code) DO NOTHING;

-- the programmes; a programme already on record (same name + department) is left as is
INSERT INTO ref.programme (code, name, dept_code, faculty_code, min_score, archived, category, pg_award, pg_research)
SELECT v.code, v.name, v.dept, v.fac, 0, false, 'POST GRADUATE', v.award, v.research
  FROM (VALUES
    ('C90010', 'Postgraduate Diploma in Accounting', 'ACC', 'MS', 'PGD', false),
    ('C90011', 'Master in Public Sector Accounting', 'ACC', 'MS', 'MSC', true),
    ('C90012', 'M.Sc. Accounting and Finance', 'ACC', 'MS', 'MSC', true),
    ('C90013', 'M.Sc./Ph.D. Accounting and Finance', 'ACC', 'MS', 'MSC', true),
    ('C90014', 'Ph.D. Accounting and Finance', 'ACC', 'MS', 'PHD', true),
    ('C90015', 'Postgraduate Diploma in Management', 'BSM', 'MS', 'PGD', false),
    ('C90016', 'Master of Business Administration', 'BSM', 'MS', 'MBA', true),
    ('C90017', 'MBA', 'BSM', 'MS', 'MBA', true),
    ('C90018', 'M.Sc. Management', 'BSM', 'MS', 'MSC', true),
    ('C90019', 'M.Sc./Ph.D. Management', 'BSM', 'MS', 'MSC', true),
    ('C90020', 'M.Sc./Ph.D. Marketing', 'BSM', 'MS', 'MSC', true),
    ('C90021', 'Ph.D. Management', 'BSM', 'MS', 'PHD', true),
    ('C90022', 'Ph.D. Marketing', 'BSM', 'MS', 'PHD', true),
    ('C90023', 'Master of Public Administration', 'PUB', 'MS', 'MPA', true),
    ('C90024', 'M.Sc. Public Administration', 'PUB', 'MS', 'MSC', true),
    ('C90025', 'Ph.D. Public Administration', 'PUB', 'MS', 'PHD', true),
    ('C90026', 'M.A. English', 'ENG', 'AR', 'MA', true),
    ('C90027', 'M.A. Literature', 'ENG', 'AR', 'MA', true),
    ('C90028', 'Ph.D. English', 'ENG', 'AR', 'PHD', true),
    ('C90029', 'Ph.D. Literature', 'ENG', 'AR', 'PHD', true),
    ('C90030', 'M.A. Linguistics', 'LAN', 'AR', 'MA', true),
    ('C90031', 'M.A. French', 'LAN', 'AR', 'MA', true),
    ('C90032', 'Ph.D.  Linguistics', 'LAN', 'AR', 'PHD', true),
    ('C90033', 'Ph.D.  French', 'LAN', 'AR', 'PHD', true),
    ('C90034', 'M.A. History', 'HST', 'AR', 'MA', true),
    ('C90035', 'Ph.D. History', 'HST', 'AR', 'PHD', true),
    ('C90036', 'M.A. Theatre Arts', 'THE', 'AR', 'MA', true),
    ('C90037', 'Ph.D. Theatre Arts', 'THE', 'AR', 'PHD', true),
    ('C90038', 'M.A. Religious Studies', 'RAC', 'AR', 'MA', true),
    ('C90039', 'PhD Religious Studies', 'RAC', 'AR', 'PHD', true),
    ('C90040', 'Ph.D. Religious Studies', 'RAC', 'AR', 'PHD', true),
    ('C90041', 'M.A. Philosophy', 'PHL', 'AR', 'MA', true),
    ('C90042', 'PhD Philosophy', 'PHL', 'AR', 'PHD', true),
    ('C90043', 'Ph.D. Philosophy', 'PHL', 'AR', 'PHD', true),
    ('C90044', 'M.Sc. Human Anatomy', 'ANT', 'BAMS', 'MSC', true),
    ('C90045', 'Ph.D. Human Anatomy', 'ANT', 'BAMS', 'PHD', true),
    ('C90046', 'M.Sc. Human Physiology', 'PGY', 'BAMS', 'MSC', true),
    ('C90047', 'Ph.D. Human Physiology', 'PGY', 'BAMS', 'PHD', true),
    ('C90048', 'Master of Public Health', 'EPI', 'CLS', 'MPH', true),
    ('C90049', 'Master of Reproductive Health', 'OBG', 'CLS', 'MRH', true),
    ('C90050', 'Postgraduate Diploma in Mass Communication', 'MCM', 'CM', 'PGD', false),
    ('C90051', 'M.Sc. Mass Communication', 'BRC', 'CM', 'MSC', true),
    ('C90052', 'Ph.D. Mass Communication', 'BRC', 'CM', 'PHD', true),
    ('C90053', 'M.Sc. Mass Communication', 'JMS', 'CM', 'MSC', true),
    ('C90054', 'Ph.D. Mass Communication', 'JMS', 'CM', 'PHD', true),
    ('C90055', 'M.Sc. Mass Communication', 'PUR', 'CM', 'MSC', true),
    ('C90056', 'Ph.D. Mass Communication', 'PUR', 'CM', 'PHD', true),
    ('C90057', 'M.Ed. Curriculum and Instruction', 'ASS', 'ED', 'MED', true),
    ('C90058', 'M.Ed. Language Education', 'ASS', 'ED', 'MED', true),
    ('C90059', 'M.Ed. Social Studies Education', 'ASS', 'ED', 'MED', true),
    ('C90060', 'Ph.D. Curriculum and Instruction', 'ASS', 'ED', 'PHD', true),
    ('C90061', 'Ph.D. Language Education', 'ASS', 'ED', 'PHD', true),
    ('C90062', 'Ph.D. Social Studies Education', 'ASS', 'ED', 'PHD', true),
    ('C90063', 'M.Sc. (Ed) Mathematics', 'SME', 'ED', 'MSC', true),
    ('C90064', 'M.Sc. (Ed) Biology', 'SME', 'ED', 'MSC', true),
    ('C90065', 'M.Sc. (Ed) Chemistry', 'SME', 'ED', 'MSC', true),
    ('C90066', 'M.Sc. (Ed) Physics', 'SME', 'ED', 'MSC', true),
    ('C90067', 'M.Ed. Measurement and Evaluation', 'SME', 'ED', 'MED', true),
    ('C90068', 'M.Ed. Mathematics Education', 'SME', 'ED', 'MED', true),
    ('C90069', 'M.Ed. Science Education', 'SME', 'ED', 'MED', true),
    ('C90070', 'Ph.D. Measurement and Evaluation', 'SME', 'ED', 'PHD', true),
    ('C90071', 'Ph.D. Mathematics Education', 'SME', 'ED', 'PHD', true),
    ('C90072', 'Ph.D. Science Education', 'SME', 'ED', 'PHD', true),
    ('C90073', 'Ph.D. Biology Education', 'SME', 'ED', 'PHD', true),
    ('C90074', 'Ph.D. Chemistry Education', 'SME', 'ED', 'PHD', true),
    ('C90075', 'Ph.D. Physics Education', 'SME', 'ED', 'PHD', true),
    ('C90076', 'Postgraduate Diploma in Education', 'EDF', 'ED', 'PGD', false),
    ('C90077', 'M.Ed. Educational Management', 'EDF', 'ED', 'MED', true),
    ('C90078', 'M.Ed. Educational Psychology', 'EDF', 'ED', 'MED', true),
    ('C90079', 'M.Ed. Guidance and Counselling', 'EDF', 'ED', 'MED', true),
    ('C90080', 'Ph.D. Educational Management', 'EDF', 'ED', 'PHD', true),
    ('C90081', 'Ph.D. Marriage and Family Counselling', 'EDF', 'ED', 'PHD', true),
    ('C90082', 'Ph.D. Personal-Social Counselling', 'EDF', 'ED', 'PHD', true),
    ('C90083', 'Ph.D. School Counselling', 'EDF', 'ED', 'PHD', true),
    ('C90084', 'M.Sc. (Ed) Health Education', 'HKH', 'ED', 'MSC', true),
    ('C90085', 'M.Sc. (Ed) Exercise and Sport Science', 'HKH', 'ED', 'MSC', true),
    ('C90086', 'M.Sc. (Ed) Sports Management', 'HKH', 'ED', 'MSC', true),
    ('C90087', 'Ph.D. Public Health Education', 'HKH', 'ED', 'PHD', true),
    ('C90088', 'M.Sc. Geography', 'GEO', 'ES', 'MSC', true),
    ('C90089', 'M.Sc. Development Studies', 'GEO', 'ES', 'MSC', true),
    ('C90090', 'M.Sc. Environmental Management', 'GEO', 'ES', 'MSC', true),
    ('C90091', 'Ph.D Geography', 'GEO', 'ES', 'PHD', true),
    ('C90092', 'Ph.D. Geography', 'GEO', 'ES', 'PHD', true),
    ('C90093', 'Ph.D. Geography (Transport Geography', 'GEO', 'ES', 'PHD', true),
    ('C90094', 'Ph.D.  Development Studies', 'GEO', 'ES', 'PHD', true),
    ('C90095', 'Postgraduate Diploma in Planning Studies', 'URP', 'ES', 'PGD', false),
    ('C90096', 'Master of Urban and Regional Planning', 'URP', 'ES', 'MURP', true),
    ('C90097', 'M.Sc. Environmental Planning and Management', 'URP', 'ES', 'MSC', true),
    ('C90098', 'M.Sc. Housing', 'URP', 'ES', 'MSC', true),
    ('C90099', 'M.Sc. Regional Planning', 'URP', 'ES', 'MSC', true),
    ('C90100', 'M.Sc. Social Services Planning', 'URP', 'ES', 'MSC', true),
    ('C90101', 'M.Sc. Transportation Planning', 'URP', 'ES', 'MSC', true),
    ('C90102', 'M.Sc. Urban Design', 'URP', 'ES', 'MSC', true),
    ('C90103', 'M.Sc. Urban management', 'URP', 'ES', 'MSC', true),
    ('C90104', 'Ph.D. Urban & Regional Planning', 'URP', 'ES', 'PHD', true),
    ('C90105', 'Postgraduate Diploma in Arbitration', 'LAW', 'LW', 'PGD', false),
    ('C90106', 'Postgraduate Diploma in Humanitarian Law and Disaster Management', 'LAW', 'LW', 'PGD', false),
    ('C90107', 'Master of Laws', 'LAW', 'LW', 'LLM', true),
    ('C90108', 'LL.M', 'LAW', 'LW', 'LLM', true),
    ('C90109', 'Ph.D. Law', 'LAW', 'LW', 'PHD', true),
    ('C90110', 'M.Sc. Economics', 'ECO', 'SS', 'MSC', true),
    ('C90111', 'PhD Economics', 'ECO', 'SS', 'PHD', true),
    ('C90112', 'Ph.D. Economics', 'ECO', 'SS', 'PHD', true),
    ('C90113', 'Postgraduate Diploma in Library & Information Science', 'LIS', 'SS', 'PGD', false),
    ('C90114', 'MLIS', 'LIS', 'SS', 'MLIS', true),
    ('C90115', 'Ph.D. Library and Information Science', 'LIS', 'SS', 'PHD', true),
    ('C90116', 'M.A. International Relations and Strategic Studies', 'POL', 'SS', 'MA', true),
    ('C90117', 'M.Sc. International Relations and Strategic Studies', 'POL', 'SS', 'MSC', true),
    ('C90118', 'M.Sc. Peace studies and Conflict Resolution', 'POL', 'SS', 'MSC', true),
    ('C90119', 'M.Sc. Political Science', 'POL', 'SS', 'MSC', true),
    ('C90120', 'PhD Political Science', 'POL', 'SS', 'PHD', true),
    ('C90121', 'Ph.D. Political Science', 'POL', 'SS', 'PHD', true),
    ('C90122', 'Postgraduate Diploma in Psychology', 'PSY', 'SS', 'PGD', false),
    ('C90123', 'Master of Health Management', 'PSY', 'SS', 'MHM', true),
    ('C90124', 'M.Sc. Psychology', 'PSY', 'SS', 'MSC', true),
    ('C90125', 'M.Sc. Clinical Psychology', 'PSY', 'SS', 'MSC', true),
    ('C90126', 'M.Sc. Industrial/Organizational Psychology', 'PSY', 'SS', 'MSC', true),
    ('C90127', 'M.Sc. Developmental Psychology', 'PSY', 'SS', 'MSC', true),
    ('C90128', 'M.Sc. Experimental Psychology', 'PSY', 'SS', 'MSC', true),
    ('C90129', 'M.Sc. Social Psychology', 'PSY', 'SS', 'MSC', true),
    ('C90130', 'PhD Psychology', 'PSY', 'SS', 'PHD', true),
    ('C90131', 'Ph.D. Clinical Psychology', 'PSY', 'SS', 'PHD', true),
    ('C90132', 'Ph.D. Industrial/Organizational Psychology', 'PSY', 'SS', 'PHD', true),
    ('C90133', 'Ph.D. Health Psychology', 'PSY', 'SS', 'PHD', true),
    ('C90134', 'Ph.D. Developmental Psychology', 'PSY', 'SS', 'PHD', true),
    ('C90135', 'Ph.D. Experimental Psychology', 'PSY', 'SS', 'PHD', true),
    ('C90136', 'Ph.D. Social Psychology', 'PSY', 'SS', 'PHD', true),
    ('C90137', 'Postgraduate Diploma in Sociology', 'SOC', 'SS', 'PGD', false),
    ('C90138', 'Postgraduate Diploma in Social Work', 'SOC', 'SS', 'PGD', false),
    ('C90139', 'M.Sc. in Gender Studies', 'SOC', 'SS', 'MSC', true),
    ('C90140', 'M.Sc. in Social Work', 'SOC', 'SS', 'MSC', true),
    ('C90141', 'M.Sc. Rural Sociology & Agricultural Extension', 'SOC', 'SS', 'MSC', true),
    ('C90142', 'M.Sc. Sociology', 'SOC', 'SS', 'MSC', true),
    ('C90143', 'Ph.D. Sociology', 'SOC', 'SS', 'PHD', true),
    ('C90144', 'Ph.D. Rural Sociology & Agricultural Extension', 'SOC', 'SS', 'PHD', true),
    ('C90145', 'Ph.D. Social Work', 'SOC', 'SS', 'PHD', true),
    ('C90146', 'M.Sc. Medical Microbiology', 'BIO', 'SC', 'MSC', true),
    ('C90147', 'M.Sc. Pure and Applied Parasitology', 'BIO', 'SC', 'MSC', true),
    ('C90148', 'M.Sc. Pure and Applied Entomology', 'BIO', 'SC', 'MSC', true),
    ('C90149', 'M.Sc. Hydrobiology and Fisheries', 'BIO', 'SC', 'MSC', true),
    ('C90150', 'M.Sc. Plant Pathology', 'BIO', 'SC', 'MSC', true),
    ('C90151', 'M.Sc. Cytogenetic and Plant Breeding', 'BIO', 'SC', 'MSC', true),
    ('C90152', 'M.Sc. Systematic and Taxonomy', 'BIO', 'SC', 'MSC', true),
    ('C90153', 'Ph.D. Medical Microbiology', 'BIO', 'SC', 'PHD', true),
    ('C90154', 'Ph.D. Pure and Applied Parasitology', 'BIO', 'SC', 'PHD', true),
    ('C90155', 'Ph.D. Pure and Applied Entomology', 'BIO', 'SC', 'PHD', true),
    ('C90156', 'Ph.D. Hydrobiology and Fisheries', 'BIO', 'SC', 'PHD', true),
    ('C90157', 'Ph.D. Plant Pathology', 'BIO', 'SC', 'PHD', true),
    ('C90158', 'Ph.D. Cytogenetic and Plant Breeding', 'BIO', 'SC', 'PHD', true),
    ('C90159', 'Ph.D. Systematic and Taxonomy', 'BIO', 'SC', 'PHD', true),
    ('C90160', 'M.Sc. Physical Chemistry', 'CHM', 'SC', 'MSC', true),
    ('C90161', 'M.Sc. Organic Chemistry', 'CHM', 'SC', 'MSC', true),
    ('C90162', 'M.Sc. Inorganic Chemistry', 'CHM', 'SC', 'MSC', true),
    ('C90163', 'M.Sc. Analytical Chemistry', 'CHM', 'SC', 'MSC', true),
    ('C90164', 'M.Sc. Industrial Chemistry', 'CHM', 'SC', 'MSC', true),
    ('C90165', 'M.Sc. Environmental Toxicology, Pollution and Control', 'CHM', 'SC', 'MSC', true),
    ('C90166', 'M.Sc. Environmental Control & Sustainability', 'CHM', 'SC', 'MSC', true),
    ('C90167', 'M.Sc. Polymer Chemistry', 'CHM', 'SC', 'MSC', true),
    ('C90168', 'Ph.D. Physical Chemistry', 'CHM', 'SC', 'PHD', true),
    ('C90169', 'Ph.D. Organic Chemistry/Natural Products Chemistry', 'CHM', 'SC', 'PHD', true),
    ('C90170', 'Ph.D. Inorganic Chemistry', 'CHM', 'SC', 'PHD', true),
    ('C90171', 'Ph.D. Analytical/Environmental Chemistry', 'CHM', 'SC', 'PHD', true),
    ('C90172', 'Ph.D. Industrial Chemistry', 'CHM', 'SC', 'PHD', true),
    ('C90173', 'Ph.D. Environmental Toxicology, Pollution and Control', 'CHM', 'SC', 'PHD', true),
    ('C90174', 'Ph.D. Environmental Control & Sustainability', 'CHM', 'SC', 'PHD', true),
    ('C90175', 'Ph.D. Polymer Chemistry', 'CHM', 'SC', 'PHD', true),
    ('C90176', 'Postgraduate Diploma in Computer Science', 'MTC', 'SC', 'PGD', false),
    ('C90177', 'M.Sc. Mathematics', 'MTC', 'SC', 'MSC', true),
    ('C90178', 'M.Sc. Computer Science', 'MTC', 'SC', 'MSC', true),
    ('C90179', 'M.Sc. Theoretical Physics', 'PHY', 'SC', 'MSC', true),
    ('C90180', 'M.Sc. Medical Physics', 'PHY', 'SC', 'MSC', true),
    ('C90181', 'M.Sc. Radiation Physics', 'PHY', 'SC', 'MSC', true),
    ('C90182', 'M.Sc. Electronics and Communications Physics', 'PHY', 'SC', 'MSC', true),
    ('C90183', 'M.Sc. Atmospheric and Environmental Physics', 'PHY', 'SC', 'MSC', true),
    ('C90184', 'M.Sc. Materials Science and Renewable Energy Physics', 'PHY', 'SC', 'MSC', true),
    ('C90185', 'Ph.D. Theoretical Physics', 'PHY', 'SC', 'PHD', true),
    ('C90186', 'Ph.D. Medical Physics', 'PHY', 'SC', 'PHD', true),
    ('C90187', 'Ph.D. Radiation Physics', 'PHY', 'SC', 'PHD', true),
    ('C90188', 'Ph.D. Atmospheric & Environmental Physics', 'PHY', 'SC', 'PHD', true),
    ('C90189', 'Ph.D. Materials Science and Renewable Energy Physics', 'PHY', 'SC', 'PHD', true),
    ('C90190', 'M.Sc. (Ed) Technology Education', 'IND', 'TI', 'MSC', true),
    ('C90191', 'Ph.D. Industrial Technology Education', 'IND', 'TI', 'PHD', true),
    ('C90192', 'M.A. Religion and Peace Studies', 'PDS', 'CTR', 'MA', true),
    ('C90193', 'M.Sc. Humanitarian and Refugee Studies', 'PDS', 'CTR', 'MSC', true),
    ('C90194', 'M.Sc. Risk & Disaster Management', 'PDS', 'CTR', 'MSC', true),
    ('C90195', 'M.Sc. Applied Conservation', 'CSP', 'CTR', 'MSC', true),
    ('C90196', 'Postgraduate Diploma in Gender Studies', 'GND', 'CTR', 'PGD', false),
    ('C90197', 'Masters in Gender Studies', 'GND', 'CTR', 'MSC', true)
  ) AS v(code, name, dept, fac, award, research)
 WHERE NOT EXISTS (SELECT 1 FROM ref.programme p
                    WHERE p.category = 'POST GRADUATE' AND lower(p.name) = lower(v.name) AND p.dept_code = v.dept);

COMMIT;
