-- ═══════════════════════════════════════════════════════════════════════════
-- V273 — the reference lists the screening form chooses from, and its checks
--
--   The Registry's forms ask for nationality, state of origin and local
--   government area. Typed, they arrive as "Gwer-East", "Gwer East" and
--   "GWER EAST" for one place. They are now chosen: the countries, the
--   thirty-six states and the Federal Capital Territory, and the local
--   government areas of each — reference tables of their own, readable by
--   every signed-in account. The form's answers are checked on submission:
--   the state must be one of these, the local government must belong to it,
--   the nationality must be a country, phones eleven digits from 0, emails
--   shaped as emails, years four digits, the date of birth a past date, the
--   account number ten digits. And the two forms' fields the catalogue still
--   lacked — the date of birth where JAMB sent none, the bank sort code and
--   the bank's location — are added.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;
SELECT set_config('moaum.actor_id', '00000000-0000-0000-0000-000000000000', true),
       set_config('moaum.actor_office', 'ict', true),
       set_config('moaum.reason', 'V273: states, local governments, countries; the screening checks', true);

CREATE TABLE ref.country (
    name    text PRIMARY KEY,
    home    boolean NOT NULL DEFAULT false,      -- Nigeria, first in every list
    ord     int NOT NULL DEFAULT 0
);
SELECT audit.attach('ref.country');
INSERT INTO ref.country (name, home) VALUES
    ('Afghanistan', false),
    ('Albania', false),
    ('Algeria', false),
    ('Andorra', false),
    ('Angola', false),
    ('Antigua and Barbuda', false),
    ('Argentina', false),
    ('Armenia', false),
    ('Australia', false),
    ('Austria', false),
    ('Azerbaijan', false),
    ('Bahamas', false),
    ('Bahrain', false),
    ('Bangladesh', false),
    ('Barbados', false),
    ('Belarus', false),
    ('Belgium', false),
    ('Belize', false),
    ('Benin', false),
    ('Bhutan', false),
    ('Bolivia', false),
    ('Bosnia and Herzegovina', false),
    ('Botswana', false),
    ('Brazil', false),
    ('Brunei', false),
    ('Bulgaria', false),
    ('Burkina Faso', false),
    ('Burundi', false),
    ('Cabo Verde', false),
    ('Cambodia', false),
    ('Cameroon', false),
    ('Canada', false),
    ('Central African Republic', false),
    ('Chad', false),
    ('Chile', false),
    ('China', false),
    ('Colombia', false),
    ('Comoros', false),
    ('Congo (Brazzaville)', false),
    ('Congo (Democratic Republic)', false),
    ('Costa Rica', false),
    ('Côte d''Ivoire', false),
    ('Croatia', false),
    ('Cuba', false),
    ('Cyprus', false),
    ('Czechia', false),
    ('Denmark', false),
    ('Djibouti', false),
    ('Dominica', false),
    ('Dominican Republic', false),
    ('Ecuador', false),
    ('Egypt', false),
    ('El Salvador', false),
    ('Equatorial Guinea', false),
    ('Eritrea', false),
    ('Estonia', false),
    ('Eswatini', false),
    ('Ethiopia', false),
    ('Fiji', false),
    ('Finland', false),
    ('France', false),
    ('Gabon', false),
    ('Gambia', false),
    ('Georgia', false),
    ('Germany', false),
    ('Ghana', false),
    ('Greece', false),
    ('Grenada', false),
    ('Guatemala', false),
    ('Guinea', false),
    ('Guinea-Bissau', false),
    ('Guyana', false),
    ('Haiti', false),
    ('Honduras', false),
    ('Hungary', false),
    ('Iceland', false),
    ('India', false),
    ('Indonesia', false),
    ('Iran', false),
    ('Iraq', false),
    ('Ireland', false),
    ('Israel', false),
    ('Italy', false),
    ('Jamaica', false),
    ('Japan', false),
    ('Jordan', false),
    ('Kazakhstan', false),
    ('Kenya', false),
    ('Kiribati', false),
    ('Kuwait', false),
    ('Kyrgyzstan', false),
    ('Laos', false),
    ('Latvia', false),
    ('Lebanon', false),
    ('Lesotho', false),
    ('Liberia', false),
    ('Libya', false),
    ('Liechtenstein', false),
    ('Lithuania', false),
    ('Luxembourg', false),
    ('Madagascar', false),
    ('Malawi', false),
    ('Malaysia', false),
    ('Maldives', false),
    ('Mali', false),
    ('Malta', false),
    ('Marshall Islands', false),
    ('Mauritania', false),
    ('Mauritius', false),
    ('Mexico', false),
    ('Micronesia', false),
    ('Moldova', false),
    ('Monaco', false),
    ('Mongolia', false),
    ('Montenegro', false),
    ('Morocco', false),
    ('Mozambique', false),
    ('Myanmar', false),
    ('Namibia', false),
    ('Nauru', false),
    ('Nepal', false),
    ('Netherlands', false),
    ('New Zealand', false),
    ('Nicaragua', false),
    ('Niger', false),
    ('Nigeria', true),
    ('North Korea', false),
    ('North Macedonia', false),
    ('Norway', false),
    ('Oman', false),
    ('Pakistan', false),
    ('Palau', false),
    ('Palestine', false),
    ('Panama', false),
    ('Papua New Guinea', false),
    ('Paraguay', false),
    ('Peru', false),
    ('Philippines', false),
    ('Poland', false),
    ('Portugal', false),
    ('Qatar', false),
    ('Romania', false),
    ('Russia', false),
    ('Rwanda', false),
    ('Saint Kitts and Nevis', false),
    ('Saint Lucia', false),
    ('Saint Vincent and the Grenadines', false),
    ('Samoa', false),
    ('San Marino', false),
    ('São Tomé and Príncipe', false),
    ('Saudi Arabia', false),
    ('Senegal', false),
    ('Serbia', false),
    ('Seychelles', false),
    ('Sierra Leone', false),
    ('Singapore', false),
    ('Slovakia', false),
    ('Slovenia', false),
    ('Solomon Islands', false),
    ('Somalia', false),
    ('South Africa', false),
    ('South Korea', false),
    ('South Sudan', false),
    ('Spain', false),
    ('Sri Lanka', false),
    ('Sudan', false),
    ('Suriname', false),
    ('Sweden', false),
    ('Switzerland', false),
    ('Syria', false),
    ('Taiwan', false),
    ('Tajikistan', false),
    ('Tanzania', false),
    ('Thailand', false),
    ('Timor-Leste', false),
    ('Togo', false),
    ('Tonga', false),
    ('Trinidad and Tobago', false),
    ('Tunisia', false),
    ('Türkiye', false),
    ('Turkmenistan', false),
    ('Tuvalu', false),
    ('Uganda', false),
    ('Ukraine', false),
    ('United Arab Emirates', false),
    ('United Kingdom', false),
    ('United States', false),
    ('Uruguay', false),
    ('Uzbekistan', false),
    ('Vanuatu', false),
    ('Vatican City', false),
    ('Venezuela', false),
    ('Vietnam', false),
    ('Yemen', false),
    ('Zambia', false),
    ('Zimbabwe', false)
ON CONFLICT DO NOTHING;

CREATE TABLE ref.state (
    code text PRIMARY KEY,
    name text NOT NULL UNIQUE,
    CONSTRAINT ck_state_code CHECK (code ~ '^[A-Z]{2}$')
);
SELECT audit.attach('ref.state');
INSERT INTO ref.state (code, name) VALUES
    ('AB', 'Abia'),
    ('AD', 'Adamawa'),
    ('AK', 'Akwa Ibom'),
    ('AN', 'Anambra'),
    ('BA', 'Bauchi'),
    ('BY', 'Bayelsa'),
    ('BE', 'Benue'),
    ('BO', 'Borno'),
    ('CR', 'Cross River'),
    ('DE', 'Delta'),
    ('EB', 'Ebonyi'),
    ('ED', 'Edo'),
    ('EK', 'Ekiti'),
    ('EN', 'Enugu'),
    ('FC', 'Federal Capital Territory'),
    ('GO', 'Gombe'),
    ('IM', 'Imo'),
    ('JI', 'Jigawa'),
    ('KD', 'Kaduna'),
    ('KN', 'Kano'),
    ('KT', 'Katsina'),
    ('KE', 'Kebbi'),
    ('KO', 'Kogi'),
    ('KW', 'Kwara'),
    ('LA', 'Lagos'),
    ('NA', 'Nasarawa'),
    ('NI', 'Niger'),
    ('OG', 'Ogun'),
    ('ON', 'Ondo'),
    ('OS', 'Osun'),
    ('OY', 'Oyo'),
    ('PL', 'Plateau'),
    ('RI', 'Rivers'),
    ('SO', 'Sokoto'),
    ('TA', 'Taraba'),
    ('YO', 'Yobe'),
    ('ZA', 'Zamfara')
ON CONFLICT DO NOTHING;

CREATE TABLE ref.lga (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    state_code text NOT NULL REFERENCES ref.state(code),
    name       text NOT NULL,
    UNIQUE (state_code, name)
);
SELECT audit.attach('ref.lga');
INSERT INTO ref.lga (state_code, name) VALUES
    ('AB', 'Aba North'),
    ('AB', 'Aba South'),
    ('AB', 'Arochukwu'),
    ('AB', 'Bende'),
    ('AB', 'Ikwuano'),
    ('AB', 'Isiala-Ngwa North'),
    ('AB', 'Isiala-Ngwa South'),
    ('AB', 'Isuikwato'),
    ('AB', 'Obingwa'),
    ('AB', 'Ohafia'),
    ('AB', 'Osisioma'),
    ('AB', 'Ugwunagbo'),
    ('AB', 'Ukwa East'),
    ('AB', 'Ukwa West'),
    ('AB', 'Umu-Nnochi'),
    ('AB', 'Umuahia North'),
    ('AB', 'Umuahia South'),
    ('AD', 'Demsa'),
    ('AD', 'Fufore'),
    ('AD', 'Ganaye'),
    ('AD', 'Gireri'),
    ('AD', 'Gombi'),
    ('AD', 'Guyuk'),
    ('AD', 'Hong'),
    ('AD', 'Jada'),
    ('AD', 'Lamurde'),
    ('AD', 'Madagali'),
    ('AD', 'Maiha'),
    ('AD', 'Mayo-Belwa'),
    ('AD', 'Michika'),
    ('AD', 'Mubi North'),
    ('AD', 'Mubi South'),
    ('AD', 'Numan'),
    ('AD', 'Shelleng'),
    ('AD', 'Song'),
    ('AD', 'Toungo'),
    ('AD', 'Yola North'),
    ('AD', 'Yola South'),
    ('AK', 'Abak'),
    ('AK', 'Eastern Obolo'),
    ('AK', 'Eket'),
    ('AK', 'Esit Eket'),
    ('AK', 'Essien Udim'),
    ('AK', 'Etim Ekpo'),
    ('AK', 'Etinan'),
    ('AK', 'Ibeno'),
    ('AK', 'Ibesikpo Asutan'),
    ('AK', 'Ibiono Ibom'),
    ('AK', 'Ika'),
    ('AK', 'Ikono'),
    ('AK', 'Ikot Abasi'),
    ('AK', 'Ikot Ekpene'),
    ('AK', 'Ini'),
    ('AK', 'Itu'),
    ('AK', 'Mbo'),
    ('AK', 'Mkpat Enin'),
    ('AK', 'Nsit Atai'),
    ('AK', 'Nsit Ibom'),
    ('AK', 'Nsit Ubium'),
    ('AK', 'Obot Akara'),
    ('AK', 'Okobo'),
    ('AK', 'Onna'),
    ('AK', 'Oron'),
    ('AK', 'Oruk Anam'),
    ('AK', 'Udung Uko'),
    ('AK', 'Ukanafun'),
    ('AK', 'Uruan'),
    ('AK', 'Urue-Offong/Oruko'),
    ('AK', 'Uyo'),
    ('AN', 'Aguata'),
    ('AN', 'Anambra East'),
    ('AN', 'Anambra West'),
    ('AN', 'Anaocha'),
    ('AN', 'Awka North'),
    ('AN', 'Awka South'),
    ('AN', 'Ayamelum'),
    ('AN', 'Dunukofia'),
    ('AN', 'Ekwusigo'),
    ('AN', 'Idemili North'),
    ('AN', 'Idemili south'),
    ('AN', 'Ihiala'),
    ('AN', 'Njikoka'),
    ('AN', 'Nnewi North'),
    ('AN', 'Nnewi South'),
    ('AN', 'Ogbaru'),
    ('AN', 'Onitsha North'),
    ('AN', 'Onitsha South'),
    ('AN', 'Orumba North'),
    ('AN', 'Orumba South'),
    ('AN', 'Oyi'),
    ('BA', 'Alkaleri'),
    ('BA', 'Bauchi'),
    ('BA', 'Bogoro'),
    ('BA', 'Damban'),
    ('BA', 'Darazo'),
    ('BA', 'Dass'),
    ('BA', 'Ganjuwa'),
    ('BA', 'Giade'),
    ('BA', 'Itas/Gadau'),
    ('BA', 'Jama''are'),
    ('BA', 'Katagum'),
    ('BA', 'Kirfi'),
    ('BA', 'Misau'),
    ('BA', 'Ningi'),
    ('BA', 'Shira'),
    ('BA', 'Tafawa-Balewa'),
    ('BA', 'Toro'),
    ('BA', 'Warji'),
    ('BA', 'Zaki'),
    ('BY', 'Brass'),
    ('BY', 'Ekeremor'),
    ('BY', 'Kolokuma/Opokuma'),
    ('BY', 'Nembe	Ogbia'),
    ('BY', 'Sagbama'),
    ('BY', 'Southern Jaw'),
    ('BY', 'Yenegoa'),
    ('BE', 'Ado'),
    ('BE', 'Agatu'),
    ('BE', 'Apa'),
    ('BE', 'Buruku'),
    ('BE', 'Gboko'),
    ('BE', 'Guma'),
    ('BE', 'Gwer East'),
    ('BE', 'Gwer West'),
    ('BE', 'Katsina-Ala'),
    ('BE', 'Konshisha'),
    ('BE', 'Kwande'),
    ('BE', 'Logo'),
    ('BE', 'Makurdi'),
    ('BE', 'Obi'),
    ('BE', 'Ogbadibo'),
    ('BE', 'Ohimini'),
    ('BE', 'Oju'),
    ('BE', 'Okpokwu'),
    ('BE', 'Oturkpo'),
    ('BE', 'Tarka'),
    ('BE', 'Ukum'),
    ('BE', 'Ushongo'),
    ('BE', 'Vandeikya'),
    ('BO', 'Abadam'),
    ('BO', 'Askira/Uba'),
    ('BO', 'Bama'),
    ('BO', 'Bayo'),
    ('BO', 'Biu'),
    ('BO', 'Chibok'),
    ('BO', 'Damboa'),
    ('BO', 'Dikwa'),
    ('BO', 'Gubio'),
    ('BO', 'Guzamala'),
    ('BO', 'Gwoza'),
    ('BO', 'Hawul'),
    ('BO', 'Jere'),
    ('BO', 'Kaga'),
    ('BO', 'Kala/Balge'),
    ('BO', 'Konduga'),
    ('BO', 'Kukawa'),
    ('BO', 'Kwaya Kusar'),
    ('BO', 'Mafa'),
    ('BO', 'Magumeri'),
    ('BO', 'Maiduguri'),
    ('BO', 'Marte'),
    ('BO', 'Mobbar'),
    ('BO', 'Monguno'),
    ('BO', 'Ngala'),
    ('BO', 'Nganzai'),
    ('BO', 'Shani'),
    ('CR', 'Abi'),
    ('CR', 'Akamkpa'),
    ('CR', 'Akpabuyo'),
    ('CR', 'Bakassi'),
    ('CR', 'Bekwara'),
    ('CR', 'Biase'),
    ('CR', 'Boki'),
    ('CR', 'Calabar Municipality'),
    ('CR', 'Calabar South'),
    ('CR', 'Etung'),
    ('CR', 'Ikom'),
    ('CR', 'Obanliku'),
    ('CR', 'Obudu'),
    ('CR', 'Odubra'),
    ('CR', 'Odukpani'),
    ('CR', 'Ogoja'),
    ('CR', 'Yala'),
    ('CR', 'Yarkur'),
    ('DE', 'Aniocha'),
    ('DE', 'Aniocha South'),
    ('DE', 'Bomadi'),
    ('DE', 'Burutu'),
    ('DE', 'Ethiope East'),
    ('DE', 'Ethiope West'),
    ('DE', 'Ika North-East'),
    ('DE', 'Ika South'),
    ('DE', 'Isoko North'),
    ('DE', 'Isoko south'),
    ('DE', 'Ndokwa East'),
    ('DE', 'Ndokwa West'),
    ('DE', 'Okpe'),
    ('DE', 'Oshimili'),
    ('DE', 'Oshimili North'),
    ('DE', 'Patani'),
    ('DE', 'Sapele'),
    ('DE', 'Udu'),
    ('DE', 'Ughelli North'),
    ('DE', 'Ughelli South'),
    ('DE', 'Ukwani'),
    ('DE', 'Uvwie'),
    ('DE', 'Warri Central'),
    ('DE', 'Warri North'),
    ('DE', 'Warri South'),
    ('EB', 'Abakaliki'),
    ('EB', 'Afikpo North'),
    ('EB', 'Afikpo South'),
    ('EB', 'Ebonyi'),
    ('EB', 'Ezza'),
    ('EB', 'Ezza South'),
    ('EB', 'Ishielu'),
    ('EB', 'Ivo'),
    ('EB', 'Ohaozara'),
    ('EB', 'Ohaukwu'),
    ('EB', 'Onicha'),
    ('EB', 'lkwo'),
    ('ED', 'Egor'),
    ('ED', 'Esan Central'),
    ('ED', 'Esan North-East'),
    ('ED', 'Esan South-East'),
    ('ED', 'Esan West'),
    ('ED', 'Etsako Central'),
    ('ED', 'Etsako East'),
    ('ED', 'Igueben'),
    ('ED', 'Oredo'),
    ('ED', 'Orhionwon'),
    ('ED', 'Ovia South-East'),
    ('ED', 'Ovia SouthWest'),
    ('ED', 'Uhunmwonde'),
    ('ED', 'Ukpoba Central'),
    ('EK', 'Ado'),
    ('EK', 'Efon'),
    ('EK', 'Ekiti South-West'),
    ('EK', 'Ekiti-East'),
    ('EK', 'Ekiti-West'),
    ('EK', 'Emure/Ise/Orun'),
    ('EK', 'Gbonyin'),
    ('EK', 'Ido/Osi'),
    ('EK', 'Ijero'),
    ('EK', 'Ikare'),
    ('EK', 'Ikole'),
    ('EK', 'Ilejemeje'),
    ('EK', 'Irepodun'),
    ('EK', 'Ise/Orun'),
    ('EK', 'Moba'),
    ('EK', 'Oye'),
    ('EN', 'Aninri'),
    ('EN', 'Enugu East'),
    ('EN', 'Enugu North'),
    ('EN', 'Enugu South'),
    ('EN', 'Ezeagu'),
    ('EN', 'Igbo-Ekiti'),
    ('EN', 'Igbo-Eze South'),
    ('EN', 'IgboEze North'),
    ('EN', 'Isi-Uzo'),
    ('EN', 'Nkanu'),
    ('EN', 'Nkanu East'),
    ('EN', 'Nsukka'),
    ('EN', 'Oji-River'),
    ('EN', 'Udenu'),
    ('EN', 'Udi Agwu'),
    ('EN', 'Uzo-Uwani'),
    ('FC', 'Abaji'),
    ('FC', 'Bwari'),
    ('FC', 'Gwagwalada'),
    ('FC', 'Kuje'),
    ('FC', 'Kwali'),
    ('FC', 'Municipal Area Council'),
    ('GO', 'Akko'),
    ('GO', 'Balanga'),
    ('GO', 'Billiri'),
    ('GO', 'Dukku'),
    ('GO', 'Funakaye'),
    ('GO', 'Gombe'),
    ('GO', 'Kaltungo'),
    ('GO', 'Kwami'),
    ('GO', 'Nafada/Bajoga'),
    ('GO', 'Shomgom'),
    ('GO', 'Yamaltu/Delta'),
    ('IM', 'Aboh-Mbaise'),
    ('IM', 'Ahiazu-Mbaise'),
    ('IM', 'Ehime-Mbano'),
    ('IM', 'Ezinihitte'),
    ('IM', 'Ideato North'),
    ('IM', 'Ideato South'),
    ('IM', 'Ihitte/Uboma'),
    ('IM', 'Ikeduru'),
    ('IM', 'Isiala Mbano'),
    ('IM', 'Isu'),
    ('IM', 'Mbaitoli'),
    ('IM', 'Ngor-Okpala'),
    ('IM', 'Njaba'),
    ('IM', 'Nkwerre'),
    ('IM', 'Nwangele'),
    ('IM', 'Obowo'),
    ('IM', 'Oguta'),
    ('IM', 'Ohaji/Egbema'),
    ('IM', 'Okigwe'),
    ('IM', 'Orlu'),
    ('IM', 'Orsu'),
    ('IM', 'Oru East'),
    ('IM', 'Oru West'),
    ('IM', 'Owerri North'),
    ('IM', 'Owerri West'),
    ('IM', 'Owerri-Municipal'),
    ('JI', 'Auyo'),
    ('JI', 'Babura'),
    ('JI', 'Biriniwa'),
    ('JI', 'Birni Kudu'),
    ('JI', 'Buji'),
    ('JI', 'Dutse'),
    ('JI', 'Gagarawa'),
    ('JI', 'Garki'),
    ('JI', 'Gumel'),
    ('JI', 'Guri'),
    ('JI', 'Gwaram'),
    ('JI', 'Gwiwa'),
    ('JI', 'Hadejia'),
    ('JI', 'Jahun'),
    ('JI', 'Kafin Hausa'),
    ('JI', 'Kaugama Kazaure'),
    ('JI', 'Kiri Kasamma'),
    ('JI', 'Kiyawa'),
    ('JI', 'Maigatari'),
    ('JI', 'Malam Madori'),
    ('JI', 'Miga'),
    ('JI', 'Ringim'),
    ('JI', 'Roni'),
    ('JI', 'Sule-Tankarkar'),
    ('JI', 'Taura'),
    ('JI', 'Yankwashi'),
    ('KD', 'Birni-Gwari'),
    ('KD', 'Chikun'),
    ('KD', 'Giwa'),
    ('KD', 'Igabi'),
    ('KD', 'Ikara'),
    ('KD', 'Jaba'),
    ('KD', 'Jema''a'),
    ('KD', 'Kachia'),
    ('KD', 'Kaduna North'),
    ('KD', 'Kaduna South'),
    ('KD', 'Kagarko'),
    ('KD', 'Kajuru'),
    ('KD', 'Kaura'),
    ('KD', 'Kauru'),
    ('KD', 'Kubau'),
    ('KD', 'Kudan'),
    ('KD', 'Lere'),
    ('KD', 'Makarfi'),
    ('KD', 'Sabon-Gari'),
    ('KD', 'Sanga'),
    ('KD', 'Soba'),
    ('KD', 'Zango-Kataf'),
    ('KD', 'Zaria'),
    ('KN', 'Ajingi'),
    ('KN', 'Albasu'),
    ('KN', 'Bagwai'),
    ('KN', 'Bebeji'),
    ('KN', 'Bichi'),
    ('KN', 'Bunkure'),
    ('KN', 'Dala'),
    ('KN', 'Dambatta'),
    ('KN', 'Dawakin Kudu'),
    ('KN', 'Dawakin Tofa'),
    ('KN', 'Doguwa'),
    ('KN', 'Fagge'),
    ('KN', 'Gabasawa'),
    ('KN', 'Garko'),
    ('KN', 'Garum'),
    ('KN', 'Gaya'),
    ('KN', 'Gezawa'),
    ('KN', 'Gwale'),
    ('KN', 'Gwarzo'),
    ('KN', 'Kabo'),
    ('KN', 'Kano Municipal'),
    ('KN', 'Karaye'),
    ('KN', 'Kibiya'),
    ('KN', 'Kiru'),
    ('KN', 'Kunchi'),
    ('KN', 'Kura'),
    ('KN', 'Madobi'),
    ('KN', 'Makoda'),
    ('KN', 'Mallam'),
    ('KN', 'Minjibir'),
    ('KN', 'Nasarawa'),
    ('KN', 'Rano'),
    ('KN', 'Rimin Gado'),
    ('KN', 'Rogo'),
    ('KN', 'Shanono'),
    ('KN', 'Sumaila'),
    ('KN', 'Takali'),
    ('KN', 'Tarauni'),
    ('KN', 'Tofa'),
    ('KN', 'Tsanyawa'),
    ('KN', 'Tudun Wada'),
    ('KN', 'Ungogo'),
    ('KN', 'Warawa'),
    ('KN', 'Wudil'),
    ('KN', 'kumbotso'),
    ('KT', 'Bakori'),
    ('KT', 'Batagarawa'),
    ('KT', 'Batsari'),
    ('KT', 'Baure'),
    ('KT', 'Bindawa'),
    ('KT', 'Charanchi'),
    ('KT', 'Dan Musa'),
    ('KT', 'Dandume'),
    ('KT', 'Danja'),
    ('KT', 'Daura'),
    ('KT', 'Dutsi'),
    ('KT', 'Dutsin-Ma'),
    ('KT', 'Faskari'),
    ('KT', 'Funtua'),
    ('KT', 'Ingawa'),
    ('KT', 'Jibia'),
    ('KT', 'Kafur'),
    ('KT', 'Kaita'),
    ('KT', 'Kankara'),
    ('KT', 'Kankia'),
    ('KT', 'Katsina'),
    ('KT', 'Kurfi'),
    ('KT', 'Kusada'),
    ('KT', 'Mai''Adua'),
    ('KT', 'Malumfashi'),
    ('KT', 'Mani'),
    ('KT', 'Mashi'),
    ('KT', 'Matazuu'),
    ('KT', 'Musawa'),
    ('KT', 'Rimi'),
    ('KT', 'Sabuwa'),
    ('KT', 'Safana'),
    ('KT', 'Sandamu'),
    ('KT', 'Zango'),
    ('KE', 'Aleiro'),
    ('KE', 'Arewa-Dandi'),
    ('KE', 'Argungu'),
    ('KE', 'Augie'),
    ('KE', 'Bagudo'),
    ('KE', 'Birnin Kebbi'),
    ('KE', 'Bunza'),
    ('KE', 'Dandi'),
    ('KE', 'Fakai'),
    ('KE', 'Gwandu'),
    ('KE', 'Jega'),
    ('KE', 'Kalgo'),
    ('KE', 'Koko/Besse'),
    ('KE', 'Maiyama'),
    ('KE', 'Ngaski'),
    ('KE', 'Sakaba'),
    ('KE', 'Shanga'),
    ('KE', 'Suru'),
    ('KE', 'Wasagu/Danko'),
    ('KE', 'Yauri'),
    ('KE', 'Zuru'),
    ('KO', 'Adavi'),
    ('KO', 'Ajaokuta'),
    ('KO', 'Ankpa'),
    ('KO', 'Bassa'),
    ('KO', 'Dekina'),
    ('KO', 'Ibaji'),
    ('KO', 'Idah'),
    ('KO', 'Igalamela-Odolu'),
    ('KO', 'Ijumu'),
    ('KO', 'Kabba/Bunu'),
    ('KO', 'Kogi'),
    ('KO', 'Lokoja'),
    ('KO', 'Mopa-Muro'),
    ('KO', 'Ofu'),
    ('KO', 'Ogori/Mangongo'),
    ('KO', 'Okehi'),
    ('KO', 'Okene'),
    ('KO', 'Olamabolo'),
    ('KO', 'Omala'),
    ('KO', 'Yagba East'),
    ('KO', 'Yagba West'),
    ('KW', 'Asa'),
    ('KW', 'Baruten'),
    ('KW', 'Edu'),
    ('KW', 'Ekiti'),
    ('KW', 'Ifelodun'),
    ('KW', 'Ilorin East'),
    ('KW', 'Ilorin West'),
    ('KW', 'Irepodun'),
    ('KW', 'Isin'),
    ('KW', 'Kaiama'),
    ('KW', 'Moro'),
    ('KW', 'Offa'),
    ('KW', 'Oke-Ero'),
    ('KW', 'Oyun'),
    ('KW', 'Pategi'),
    ('LA', 'Agege'),
    ('LA', 'Ajeromi-Ifelodun'),
    ('LA', 'Alimosho'),
    ('LA', 'Amuwo-Odofin'),
    ('LA', 'Apapa'),
    ('LA', 'Badagry'),
    ('LA', 'Epe'),
    ('LA', 'Eti-Osa'),
    ('LA', 'Ibeju/Lekki'),
    ('LA', 'Ifako-Ijaye'),
    ('LA', 'Ikeja'),
    ('LA', 'Ikorodu'),
    ('LA', 'Kosofe'),
    ('LA', 'Lagos Island'),
    ('LA', 'Lagos Mainland'),
    ('LA', 'Mushin'),
    ('LA', 'Ojo'),
    ('LA', 'Oshodi-Isolo'),
    ('LA', 'Shomolu'),
    ('LA', 'Surulere'),
    ('NA', 'Akwanga'),
    ('NA', 'Awe'),
    ('NA', 'Doma'),
    ('NA', 'Karu'),
    ('NA', 'Keana'),
    ('NA', 'Keffi'),
    ('NA', 'Kokona'),
    ('NA', 'Lafia'),
    ('NA', 'Nasarawa'),
    ('NA', 'Nasarawa-Eggon'),
    ('NA', 'Obi'),
    ('NA', 'Toto'),
    ('NA', 'Wamba'),
    ('NI', 'Agaie'),
    ('NI', 'Agwara'),
    ('NI', 'Bida'),
    ('NI', 'Borgu'),
    ('NI', 'Bosso'),
    ('NI', 'Chanchaga'),
    ('NI', 'Edati'),
    ('NI', 'Gbako'),
    ('NI', 'Gurara'),
    ('NI', 'Katcha'),
    ('NI', 'Kontagora'),
    ('NI', 'Lapai'),
    ('NI', 'Lavun'),
    ('NI', 'Magama'),
    ('NI', 'Mariga'),
    ('NI', 'Mashegu'),
    ('NI', 'Mokwa'),
    ('NI', 'Muya'),
    ('NI', 'Pailoro'),
    ('NI', 'Rafi'),
    ('NI', 'Rijau'),
    ('NI', 'Shiroro'),
    ('NI', 'Suleja'),
    ('NI', 'Tafa'),
    ('NI', 'Wushishi'),
    ('OG', 'Abeokuta North'),
    ('OG', 'Abeokuta South'),
    ('OG', 'Ado-Odo/Ota'),
    ('OG', 'Egbado North'),
    ('OG', 'Egbado South'),
    ('OG', 'Ewekoro'),
    ('OG', 'Ifo'),
    ('OG', 'Ijebu East'),
    ('OG', 'Ijebu North'),
    ('OG', 'Ijebu North East'),
    ('OG', 'Ijebu Ode'),
    ('OG', 'Ikenne'),
    ('OG', 'Imeko-Afon'),
    ('OG', 'Ipokia'),
    ('OG', 'Obafemi-Owode'),
    ('OG', 'Odeda'),
    ('OG', 'Odogbolu'),
    ('OG', 'Ogun Waterside'),
    ('OG', 'Remo North'),
    ('OG', 'Shagamu'),
    ('ON', 'Akoko North East'),
    ('ON', 'Akoko North West'),
    ('ON', 'Akoko South Akure East'),
    ('ON', 'Akoko South West'),
    ('ON', 'Akure North'),
    ('ON', 'Akure South'),
    ('ON', 'Ese-Odo'),
    ('ON', 'Idanre'),
    ('ON', 'Ifedore'),
    ('ON', 'Ilaje'),
    ('ON', 'Ile-Oluji'),
    ('ON', 'Irele'),
    ('ON', 'Odigbo'),
    ('ON', 'Okeigbo'),
    ('ON', 'Okitipupa'),
    ('ON', 'Ondo East'),
    ('ON', 'Ondo West'),
    ('ON', 'Ose'),
    ('ON', 'Owo'),
    ('OS', 'Aiyedade'),
    ('OS', 'Aiyedire'),
    ('OS', 'Atakumosa East'),
    ('OS', 'Atakumosa West'),
    ('OS', 'Boluwaduro'),
    ('OS', 'Boripe'),
    ('OS', 'Ede North'),
    ('OS', 'Ede South'),
    ('OS', 'Egbedore'),
    ('OS', 'Ejigbo'),
    ('OS', 'Ife Central'),
    ('OS', 'Ife East'),
    ('OS', 'Ife North'),
    ('OS', 'Ife South'),
    ('OS', 'Ifedayo'),
    ('OS', 'Ifelodun'),
    ('OS', 'Ila'),
    ('OS', 'Ilesha East'),
    ('OS', 'Ilesha West'),
    ('OS', 'Irepodun'),
    ('OS', 'Irewole'),
    ('OS', 'Isokan'),
    ('OS', 'Iwo'),
    ('OS', 'Obokun'),
    ('OS', 'Odo-Otin'),
    ('OS', 'Ola-Oluwa'),
    ('OS', 'Olorunda'),
    ('OS', 'Oriade'),
    ('OS', 'Orolu'),
    ('OS', 'Osogbo'),
    ('OY', 'Afijio'),
    ('OY', 'Akinyele'),
    ('OY', 'Atiba'),
    ('OY', 'Atigbo'),
    ('OY', 'Egbeda'),
    ('OY', 'Ibadan North'),
    ('OY', 'Ibadan North West'),
    ('OY', 'Ibadan South East'),
    ('OY', 'Ibadan South West'),
    ('OY', 'IbadanCentral'),
    ('OY', 'Ibarapa Central'),
    ('OY', 'Ibarapa East'),
    ('OY', 'Ibarapa North'),
    ('OY', 'Ido'),
    ('OY', 'Irepo'),
    ('OY', 'Iseyin'),
    ('OY', 'Itesiwaju'),
    ('OY', 'Iwajowa'),
    ('OY', 'Kajola'),
    ('OY', 'Lagelu Ogbomosho North'),
    ('OY', 'Ogbmosho South'),
    ('OY', 'Ogo Oluwa'),
    ('OY', 'Olorunsogo'),
    ('OY', 'Oluyole'),
    ('OY', 'Ona-Ara'),
    ('OY', 'Orelope'),
    ('OY', 'Ori Ire'),
    ('OY', 'Oyo East'),
    ('OY', 'Oyo West'),
    ('OY', 'Saki East'),
    ('OY', 'Saki West'),
    ('OY', 'Surulere'),
    ('PL', 'Barikin Ladi'),
    ('PL', 'Bassa'),
    ('PL', 'Bokkos'),
    ('PL', 'Jos East'),
    ('PL', 'Jos North'),
    ('PL', 'Jos South'),
    ('PL', 'Kanam'),
    ('PL', 'Kanke'),
    ('PL', 'Langtang North'),
    ('PL', 'Langtang South'),
    ('PL', 'Mangu'),
    ('PL', 'Mikang'),
    ('PL', 'Pankshin'),
    ('PL', 'Qua''an Pan'),
    ('PL', 'Riyom'),
    ('PL', 'Shendam'),
    ('PL', 'Wase'),
    ('RI', 'Abua/Odual'),
    ('RI', 'Ahoada East'),
    ('RI', 'Ahoada West'),
    ('RI', 'Akuku Toru'),
    ('RI', 'Andoni'),
    ('RI', 'Asari-Toru'),
    ('RI', 'Bonny'),
    ('RI', 'Degema'),
    ('RI', 'Eleme'),
    ('RI', 'Emohua'),
    ('RI', 'Etche'),
    ('RI', 'Gokana'),
    ('RI', 'Ikwerre'),
    ('RI', 'Khana'),
    ('RI', 'Obia/Akpor'),
    ('RI', 'Ogba/Egbema/Ndoni'),
    ('RI', 'Ogu/Bolo'),
    ('RI', 'Okrika'),
    ('RI', 'Omumma'),
    ('RI', 'Opobo/Nkoro'),
    ('RI', 'Oyigbo'),
    ('RI', 'Port-Harcourt'),
    ('RI', 'Tai'),
    ('SO', 'Binji'),
    ('SO', 'Bodinga'),
    ('SO', 'Dange-shnsi'),
    ('SO', 'Gada'),
    ('SO', 'Gawabawa'),
    ('SO', 'Goronyo'),
    ('SO', 'Gudu'),
    ('SO', 'Illela'),
    ('SO', 'Isa'),
    ('SO', 'Kware'),
    ('SO', 'Rabah'),
    ('SO', 'Sabon birni'),
    ('SO', 'Shagari'),
    ('SO', 'Silame'),
    ('SO', 'Sokoto North'),
    ('SO', 'Sokoto South'),
    ('SO', 'Tambuwal'),
    ('SO', 'Tungaza'),
    ('SO', 'Tureta'),
    ('SO', 'Wamako'),
    ('SO', 'Wurno'),
    ('SO', 'Yabo'),
    ('SO', 'kebbe'),
    ('TA', 'Ardo-kola'),
    ('TA', 'Bali'),
    ('TA', 'Cassol'),
    ('TA', 'Donga'),
    ('TA', 'Gashaka'),
    ('TA', 'Ibi'),
    ('TA', 'Jalingo'),
    ('TA', 'Karin-Lamido'),
    ('TA', 'Kurmi'),
    ('TA', 'Lau'),
    ('TA', 'Sardauna'),
    ('TA', 'Takum'),
    ('TA', 'Ussa'),
    ('TA', 'Wukari'),
    ('TA', 'Yorro'),
    ('TA', 'Zing'),
    ('YO', 'Bade'),
    ('YO', 'Bursari'),
    ('YO', 'Damaturu'),
    ('YO', 'Fika'),
    ('YO', 'Fune'),
    ('YO', 'Geidam'),
    ('YO', 'Gujba'),
    ('YO', 'Gulani'),
    ('YO', 'Jakusko'),
    ('YO', 'Karasuwa'),
    ('YO', 'Karawa'),
    ('YO', 'Machina'),
    ('YO', 'Nangere'),
    ('YO', 'Nguru Potiskum'),
    ('YO', 'Tarmua'),
    ('YO', 'Yunusari'),
    ('YO', 'Yusufari'),
    ('ZA', 'Anka'),
    ('ZA', 'Bakura'),
    ('ZA', 'Birnin Magaji'),
    ('ZA', 'Bukkuyum'),
    ('ZA', 'Bungudu'),
    ('ZA', 'Gummi'),
    ('ZA', 'Gusau'),
    ('ZA', 'Kaura'),
    ('ZA', 'Maradun'),
    ('ZA', 'Maru'),
    ('ZA', 'Namoda'),
    ('ZA', 'Shinkafi'),
    ('ZA', 'Talata Mafara'),
    ('ZA', 'Tsafe'),
    ('ZA', 'Zurmi')
ON CONFLICT DO NOTHING;

-- the fields the forms ask for that the catalogue still lacked
INSERT INTO ref.biodata_field (field, section, label, tier, hint, wide, ord) VALUES
    ('date_of_birth',  'personal', 'Date of birth',      'open', 'Where JAMB sent none; YYYY-MM-DD', false, 40),
    ('bank_sort_code', 'bank',     'Bank sort code',     'open', NULL, false, 56),
    ('bank_location',  'bank',     'Bank location',      'open', NULL, false, 57)
ON CONFLICT (field) DO NOTHING;

/* what still stands in the way of a submission: the required fields and documents, at least one O'Level row — and now the shape of what was given */
CREATE OR REPLACE FUNCTION admissions.screening_missing(p_app uuid)
RETURNS TABLE (kind text, item text, label text)
LANGUAGE sql STABLE AS $$
    WITH ans AS (SELECT x.field, btrim(x.value) AS value FROM admissions.screening_answer x WHERE x.application_id = p_app AND btrim(x.value) <> '')
    SELECT 'FIELD', f, bf.label
      FROM admissions.application a JOIN admissions.screening_policy sp ON sp.session = a.session CROSS JOIN unnest(sp.required_fields) AS f
      JOIN ref.biodata_field bf ON bf.field = f
     WHERE a.id = p_app AND NOT EXISTS (SELECT 1 FROM ans WHERE ans.field = f)
    UNION ALL
    SELECT 'DOCUMENT', d, initcap(replace(lower(d), '_', ' '))
      FROM admissions.application a JOIN admissions.screening_policy sp ON sp.session = a.session CROSS JOIN unnest(sp.required_documents) AS d
     WHERE a.id = p_app AND NOT EXISTS (SELECT 1 FROM admissions.application_document x WHERE x.application_id = p_app AND x.kind = d AND x.status <> 'REJECTED')
    UNION ALL
    SELECT 'OLEVEL', 'OLEVEL', 'At least one O''Level result'
     WHERE NOT EXISTS (SELECT 1 FROM admissions.screening_olevel x WHERE x.application_id = p_app AND x.active)
    UNION ALL
    SELECT 'INVALID', ans.field, bf.label || ': ' || CASE
             WHEN ans.field IN ('mobile', 'alt_mobile', 'kin_mobile', 'kin_alt_mobile', 'guardian_mobile', 'father_mobile', 'mother_mobile', 'guarantor_mobile', 'whatsapp') THEN 'eleven digits, starting with 0'
             WHEN ans.field IN ('personal_email', 'kin_email', 'guardian_email', 'father_email', 'mother_email') THEN 'not shaped as an email address'
             WHEN ans.field = 'date_of_birth' THEN 'a past date as YYYY-MM-DD'
             WHEN ans.field IN ('secondary_graduation_year', 'alevel_graduation_year') THEN 'a four-digit year'
             WHEN ans.field = 'bank_account_no' THEN 'ten digits'
             WHEN ans.field = 'nationality' THEN 'choose a country from the list'
             WHEN ans.field = 'state_of_origin' THEN 'choose a state from the list'
             WHEN ans.field = 'lga' THEN 'choose a local government of the chosen state'
             ELSE 'not valid' END
      FROM ans JOIN ref.biodata_field bf ON bf.field = ans.field
     WHERE (ans.field IN ('mobile', 'alt_mobile', 'kin_mobile', 'kin_alt_mobile', 'guardian_mobile', 'father_mobile', 'mother_mobile', 'guarantor_mobile', 'whatsapp') AND ans.value !~ '^0[0-9]{10}$')
        OR (ans.field IN ('personal_email', 'kin_email', 'guardian_email', 'father_email', 'mother_email') AND ans.value !~ '^[^\s@]+@[^\s@]+\.[A-Za-z]{2,}$')
        OR (ans.field = 'date_of_birth' AND NOT (ans.value ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND ans.value::date < current_date AND ans.value::date > current_date - interval '100 years'))
        OR (ans.field IN ('secondary_graduation_year', 'alevel_graduation_year') AND NOT (ans.value ~ '^[0-9]{4}$' AND ans.value::int BETWEEN 1950 AND extract(year FROM current_date)::int))
        OR (ans.field = 'bank_account_no' AND ans.value !~ '^[0-9]{10}$')
        OR (ans.field = 'nationality' AND NOT EXISTS (SELECT 1 FROM ref.country c WHERE lower(c.name) = lower(ans.value)))
        OR (ans.field = 'state_of_origin' AND NOT EXISTS (SELECT 1 FROM ref.state s WHERE lower(s.name) = lower(ans.value)))
        OR (ans.field = 'lga' AND NOT EXISTS (SELECT 1 FROM ref.lga l JOIN ref.state s ON s.code = l.state_code
                                                 WHERE lower(l.name) = lower(ans.value) AND lower(s.name) = lower(coalesce((SELECT value FROM ans a2 WHERE a2.field = 'state_of_origin'), ''))));
$$;

GRANT SELECT ON ref.country, ref.state, ref.lga TO app_student, app_admissions, app_auditor;

COMMIT;
