-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V314 — GST & EPS: the fee the Bursar states, the entitlement a verified payment grants, the gate on
--        registration, and the two offices that run the courses
--
--   General Studies (GST) and Entrepreneurship Studies (EPS) are two academic offices over the courses the
--   catalogue already carries as kind 'GST' (V013, V116, V172: a GST/EPS course is one of kind GST, offered to
--   a programme on basis GST, registered as an entry of type GST). Nothing of that changes. What is added:
--
--     1  two offices on the register, 'gst' and 'eps', with the courses split between them by
--        catalogue.course.general_office — GST or EPS — derived from the code and title once and kept by a
--        trigger, editable by the office that owns the course.
--     2  the GST fee: a separate obligation from school fees, stated by the Bursar per session in
--        finance.gst_fee, scoped where needed to a level, an entry mode, a faculty or a programme; a new
--        statement supersedes the old and never touches a payment already made. ONE payment covers GST and
--        EPS (finance.gst_setting.covers_eps); there is no EPS fee.
--     3  the entitlement: finance.gst_entitlement(student, session) reads the CONFIRMED references of purpose
--        'GST fee <session>' on finance.payment_reference — the same ledger, the same confirmation as every
--        other payment — net of any approved or paid refund, and says whether the student is entitled. The
--        reference is generated by finance.new_gst_reference and paid on the gateway like any other.
--     4  the gate: registration.gst_gate refuses a GST or EPS course on a registration while the GST fee is
--        stated and unpaid (finance.gst_setting.required_for_gst_eps, on by default); it may also be set to
--        hold the whole registration (required_for_all, off by default). The refusal is raised by
--        registration.student_choose, student_add and student_submit themselves, so no path round the API
--        registers an unpaid student; the message names the fee and the way to pay it.
--     5  what the offices read: finance.gst_population (one row per undergraduate with their requirement,
--        fee, payment, entitlement and GST/EPS registrations for a session) and finance.gst_course_stats
--        (one row per GST/EPS offering with its registrations, its score sheet and its stage) — set-based,
--        for the dashboards, the lists and the exports.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

BEGIN;
SELECT set_config('moaum.actor_id', '00000000-0000-0000-0000-000000000000', true),
       set_config('moaum.actor_office', 'ict', true),
       set_config('moaum.reason', 'V314: GST & EPS — the fee, the entitlement, the gate, the offices', true);

-- ── 1 · the two offices, and which of them a general course belongs to ────────────────────────
INSERT INTO ref.office (code, label, scope_kind) VALUES
    ('gst', 'Director, General Studies',          'unit'),
    ('eps', 'Director, Entrepreneurship Studies', 'unit')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE catalogue.course ADD COLUMN IF NOT EXISTS general_office text NULL;
ALTER TABLE catalogue.course DROP CONSTRAINT IF EXISTS ck_course_general_office;
ALTER TABLE catalogue.course ADD CONSTRAINT ck_course_general_office CHECK (general_office IS NULL OR general_office IN ('GST', 'EPS'));
COMMENT ON COLUMN catalogue.course.general_office IS
  'For a course of kind GST (V314): the office that runs it — GST (General Studies) or EPS (Entrepreneurship Studies). NULL for every other course.';

CREATE OR REPLACE FUNCTION catalogue.general_office_of(p_code text, p_title text, p_kind text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE WHEN coalesce(p_kind, '') <> 'GST' THEN NULL
                WHEN upper(coalesce(p_code, '')) ~ '^(EPS|ENT)[ -]?[0-9]' OR coalesce(p_title, '') ~* '(entrepreneur|enterprise|venture)' THEN 'EPS'
                ELSE 'GST' END
$$;
COMMENT ON FUNCTION catalogue.general_office_of(text, text, text) IS
  'The office a general course belongs to by its code and title (V314): EPS for an EPS/ENT code or an entrepreneurship title, GST for the rest of kind GST, NULL otherwise.';

UPDATE catalogue.course SET general_office = catalogue.general_office_of(code, title, kind) WHERE kind = 'GST' AND general_office IS NULL;

CREATE OR REPLACE FUNCTION catalogue.course_general_office()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.kind <> 'GST' THEN
        NEW.general_office := NULL;
    ELSIF NEW.general_office IS NULL THEN
        NEW.general_office := catalogue.general_office_of(NEW.code, NEW.title, NEW.kind);
    END IF;
    RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_course_general_office ON catalogue.course;
CREATE TRIGGER trg_course_general_office BEFORE INSERT OR UPDATE OF kind, code, title, general_office ON catalogue.course
    FOR EACH ROW EXECUTE FUNCTION catalogue.course_general_office();
CREATE INDEX IF NOT EXISTS ix_course_general_office ON catalogue.course (general_office) WHERE general_office IS NOT NULL;

-- ── 2 · the rule: what the GST payment is required for, and that it covers EPS ────────────────
CREATE TABLE finance.gst_setting (
    id                   int PRIMARY KEY CHECK (id = 1),
    required_for_gst_eps boolean NOT NULL DEFAULT true,
    required_for_all     boolean NOT NULL DEFAULT false,
    covers_eps           boolean NOT NULL DEFAULT true,
    updated_by           uuid NULL,
    updated_office       text NULL,
    updated_at           timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE finance.gst_setting IS
  'The University''s GST rule (V314), one row: whether the GST fee gates GST/EPS course registration (default yes), whether it gates the whole registration (default no), and whether it covers EPS (default yes — there is no EPS fee).';
INSERT INTO finance.gst_setting (id) VALUES (1);
SELECT audit.attach('finance.gst_setting');
GRANT SELECT, UPDATE ON finance.gst_setting TO app_student;

CREATE OR REPLACE FUNCTION finance.set_gst_setting(p_gst_eps boolean, p_all boolean, p_covers boolean, p_actor uuid, p_office text)
RETURNS void LANGUAGE sql AS $$
    UPDATE finance.gst_setting
       SET required_for_gst_eps = coalesce(p_gst_eps, required_for_gst_eps),
           required_for_all     = coalesce(p_all, required_for_all),
           covers_eps           = coalesce(p_covers, covers_eps),
           updated_by = p_actor, updated_office = p_office, updated_at = now()
     WHERE id = 1
$$;

-- ── 3 · the GST fee, stated by the Bursar per session; a new statement supersedes, never edits ─
CREATE TABLE finance.gst_fee (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session        text NOT NULL REFERENCES policy.academic_session(name),
    amount         numeric(12,2) NOT NULL CHECK (amount >= 0),
    level          int NULL CHECK (level IS NULL OR level IN (100, 200, 300, 400, 500, 600)),
    entry_mode     text NULL CHECK (entry_mode IS NULL OR entry_mode IN ('UTME', 'DIRECT_ENTRY', 'TRANSFER', 'JUPEB', 'SANDWICH')),
    faculty_code   text NULL REFERENCES ref.faculty(code),
    programme_code text NULL REFERENCES ref.programme(code),
    effective_from date NOT NULL DEFAULT current_date,
    note           text NULL,
    stated_by      uuid NULL,
    stated_office  text NULL,
    stated_at      timestamptz NOT NULL DEFAULT now(),
    superseded_at  timestamptz NULL
);
COMMENT ON TABLE finance.gst_fee IS
  'The GST fee per session (V314), stated by the Bursar: a general rule, or one scoped to a level, an entry mode, a faculty or a programme; the most specific live rule prices a student. A new statement supersedes the old; a payment already confirmed keeps its own amount.';
CREATE INDEX ix_gst_fee_live ON finance.gst_fee (session) WHERE superseded_at IS NULL;
SELECT audit.attach('finance.gst_fee');
GRANT SELECT, INSERT, UPDATE ON finance.gst_fee TO app_student;

CREATE OR REPLACE FUNCTION finance.state_gst_fee(p_session text, p_amount numeric, p_level int, p_entry_mode text, p_faculty text, p_programme text,
                                                  p_effective_from date, p_note text, p_actor uuid, p_office text)
RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_id uuid; v_mode text := nullif(upper(btrim(coalesce(p_entry_mode, ''))), '');
BEGIN
    IF NOT EXISTS (SELECT 1 FROM policy.academic_session WHERE name = p_session) THEN
        RAISE EXCEPTION 'no academic session % on the calendar', p_session USING ERRCODE = '23503';
    END IF;
    IF p_amount IS NULL OR p_amount < 0 THEN RAISE EXCEPTION 'the GST fee is an amount of zero or more' USING ERRCODE = '23514'; END IF;
    IF p_level IS NOT NULL AND p_level NOT IN (100, 200, 300, 400, 500, 600) THEN RAISE EXCEPTION 'a level is 100 to 600' USING ERRCODE = '23514'; END IF;
    IF v_mode IS NOT NULL AND v_mode NOT IN ('UTME', 'DIRECT_ENTRY', 'TRANSFER', 'JUPEB', 'SANDWICH') THEN RAISE EXCEPTION 'unknown entry mode %', v_mode USING ERRCODE = '23514'; END IF;
    IF p_faculty IS NOT NULL AND NOT EXISTS (SELECT 1 FROM ref.faculty WHERE code = p_faculty) THEN RAISE EXCEPTION 'no faculty %', p_faculty USING ERRCODE = '23503'; END IF;
    IF p_programme IS NOT NULL AND NOT EXISTS (SELECT 1 FROM ref.programme WHERE code = p_programme) THEN RAISE EXCEPTION 'no programme %', p_programme USING ERRCODE = '23503'; END IF;
    UPDATE finance.gst_fee SET superseded_at = now()
     WHERE session = p_session AND superseded_at IS NULL
       AND level IS NOT DISTINCT FROM p_level AND entry_mode IS NOT DISTINCT FROM v_mode
       AND faculty_code IS NOT DISTINCT FROM p_faculty AND programme_code IS NOT DISTINCT FROM p_programme;
    INSERT INTO finance.gst_fee (session, amount, level, entry_mode, faculty_code, programme_code, effective_from, note, stated_by, stated_office)
    VALUES (p_session, p_amount, p_level, v_mode, p_faculty, p_programme, coalesce(p_effective_from, current_date), nullif(btrim(coalesce(p_note, '')), ''), p_actor, p_office)
    RETURNING id INTO v_id;
    RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION finance.end_gst_fee(p_id uuid)
RETURNS void LANGUAGE sql AS $$
    UPDATE finance.gst_fee SET superseded_at = now() WHERE id = p_id AND superseded_at IS NULL
$$;

/* the rule that prices one student: the most specific live rule of the session */
CREATE OR REPLACE FUNCTION finance.gst_fee_for(p_student uuid, p_session text)
RETURNS TABLE (fee_id uuid, amount numeric, stated boolean)
LANGUAGE sql STABLE AS $$
    WITH s AS (SELECT st.programme_code, p.faculty_code, st.current_level, st.entry_mode
                 FROM people.student st JOIN ref.programme p ON p.code = st.programme_code WHERE st.id = p_student),
    r AS (SELECT f.id, f.amount
            FROM finance.gst_fee f CROSS JOIN s
           WHERE f.session = p_session AND f.superseded_at IS NULL AND f.effective_from <= current_date
             AND (f.programme_code IS NULL OR f.programme_code = s.programme_code)
             AND (f.faculty_code IS NULL OR f.faculty_code = s.faculty_code)
             AND (f.level IS NULL OR f.level = s.current_level)
             AND (f.entry_mode IS NULL OR f.entry_mode = s.entry_mode)
           ORDER BY (f.programme_code IS NOT NULL) DESC, (f.faculty_code IS NOT NULL) DESC, (f.level IS NOT NULL) DESC, (f.entry_mode IS NOT NULL) DESC, f.stated_at DESC
           LIMIT 1)
    SELECT r.id, r.amount, true FROM r
    UNION ALL
    SELECT NULL::uuid, 0::numeric, false WHERE NOT EXISTS (SELECT 1 FROM r)
$$;

-- ── 4 · who is required, and whether they are entitled ───────────────────────────────────────
/* required: an undergraduate whose programme offers a GST/EPS course at their level */
CREATE OR REPLACE FUNCTION finance.gst_required(p_student uuid, p_session text)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT EXISTS (
        SELECT 1 FROM people.student st
          JOIN ref.programme p ON p.code = st.programme_code AND p.category = 'UNDER GRADUATE'
          JOIN catalogue.course_offer co ON co.programme_code = st.programme_code AND co.level = st.current_level
          JOIN catalogue.course c ON c.code = co.course_code AND c.kind = 'GST' AND c.state <> 'ENDED'
         WHERE st.id = p_student)
$$;

/* the entitlement: the fee the Bursar stated for this student, what was paid against it on the ledger, and the answer */
CREATE OR REPLACE FUNCTION finance.gst_entitlement(p_student uuid, p_session text)
RETURNS TABLE (required boolean, stated boolean, fee numeric, covers_eps boolean, paid numeric, entitled boolean, state text,
               reference text, receipt_no text, paid_at timestamptz, open_reference text, open_amount numeric, open_expires_at timestamptz)
LANGUAGE sql STABLE AS $$
    WITH f AS (SELECT * FROM finance.gst_fee_for(p_student, p_session)),
    cfg AS (SELECT covers_eps FROM finance.gst_setting WHERE id = 1),
    pays AS (SELECT r.reference, r.receipt_no, r.amount, r.confirmed_at
               FROM finance.payment_reference r
              WHERE r.student_id = p_student AND r.session = p_session AND r.purpose LIKE 'GST fee %' AND r.confirmed_at IS NOT NULL
                AND NOT EXISTS (SELECT 1 FROM finance.refund rf WHERE rf.reference = r.reference AND rf.state IN ('APPROVED', 'PAID'))),
    agg AS (SELECT coalesce(sum(amount), 0) AS paid, max(confirmed_at) AS paid_at, count(*) AS n FROM pays),
    last AS (SELECT reference, receipt_no FROM pays ORDER BY confirmed_at DESC LIMIT 1),
    open AS (SELECT r.reference, r.amount, r.expires_at
               FROM finance.payment_reference r
              WHERE r.student_id = p_student AND r.session = p_session AND r.purpose LIKE 'GST fee %' AND r.confirmed_at IS NULL AND r.expires_at > now()
              ORDER BY r.generated_at DESC LIMIT 1),
    req AS (SELECT finance.gst_required(p_student, p_session) AS required)
    SELECT req.required, f.stated, f.amount, cfg.covers_eps, agg.paid,
           -- a confirmed reference was generated for the fee as it stood: a later change of the fee does not unmake the payment
           (agg.n > 0 OR (f.stated AND f.amount = 0)) AS entitled,
           CASE WHEN agg.n > 0 OR (f.stated AND f.amount = 0) THEN 'PAID'
                WHEN NOT req.required THEN 'NOT_REQUIRED'
                WHEN NOT f.stated THEN 'NOT_STATED'
                WHEN open.reference IS NOT NULL THEN 'PENDING'
                ELSE 'NOT_PAID' END,
           last.reference, last.receipt_no, agg.paid_at, open.reference, open.amount, open.expires_at
      FROM f CROSS JOIN cfg CROSS JOIN agg CROSS JOIN req LEFT JOIN last ON true LEFT JOIN open ON true
$$;
COMMENT ON FUNCTION finance.gst_entitlement(uuid, text) IS
  'The authoritative answer (V314): entitled when a CONFIRMED reference of purpose ''GST fee <session>'' stands on finance.payment_reference for the student, net of approved or paid refunds — the fee as stated when the reference was generated; a later change of the fee does not unmake a payment. Never from an invoice, never from a page.';

/* the reference a student pays the GST fee against: the stated fee, once, on the same ledger as everything else */
CREATE OR REPLACE FUNCTION finance.new_gst_reference(p_student uuid, p_session text)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE e record;
BEGIN
    SELECT * INTO e FROM finance.gst_entitlement(p_student, p_session);
    IF NOT e.stated OR e.fee <= 0 THEN
        RAISE EXCEPTION 'GST_FEE_NOT_STATED: no GST fee is stated for %', p_session USING ERRCODE = '23514',
            HINT = 'The Bursar states the GST fee for the session before it is paid.';
    END IF;
    IF e.entitled THEN
        RAISE EXCEPTION 'GST_ALREADY_PAID: the GST fee for % is paid in full (receipt %)', p_session, coalesce(e.receipt_no, e.reference) USING ERRCODE = '23514',
            HINT = 'It is paid once and covers both GST and EPS.';
    END IF;
    IF e.open_reference IS NOT NULL THEN RETURN e.open_reference; END IF;
    RETURN finance.new_purpose_reference(p_student, p_session, e.fee - e.paid, 'GST fee ' || p_session);
END $$;

-- ── 5 · the gate on registration ─────────────────────────────────────────────────────────────
/* NULL when the course may be registered; otherwise the coded refusal */
CREATE OR REPLACE FUNCTION registration.gst_gate(p_student uuid, p_session text, p_course text)
RETURNS text LANGUAGE sql STABLE AS $$
    WITH c AS (SELECT kind, general_office FROM catalogue.course WHERE code = p_course),
         g AS (SELECT * FROM finance.gst_setting WHERE id = 1),
         e AS (SELECT * FROM finance.gst_entitlement(p_student, p_session))
    SELECT CASE WHEN e.stated AND e.fee > 0 AND NOT e.entitled
                     AND ((g.required_for_gst_eps AND c.kind = 'GST' AND (coalesce(c.general_office, 'GST') = 'GST' OR g.covers_eps))
                          OR (g.required_for_all AND e.required))
                THEN 'GST_PAYMENT_REQUIRED: you are required to pay the GST fee of NGN ' || to_char(e.fee, 'FM999,999,999,990.00') || ' for ' || p_session
                     || ' before you can register ' || CASE WHEN c.kind = 'GST' THEN coalesce(c.general_office, 'GST') || ' courses' ELSE 'your courses' END
                     || '. GST payment covers both GST and EPS requirements.'
                ELSE NULL END
      FROM g CROSS JOIN e LEFT JOIN c ON true
$$;
COMMENT ON FUNCTION registration.gst_gate(uuid, text, text) IS
  'The GST gate on one course (V314): the refusal while the stated GST fee is unpaid, for a GST/EPS course (required_for_gst_eps) or for any course (required_for_all); NULL when the student may go on. With no fee stated there is nothing to pay and no gate.';

-- the student's choice, replaced whole: as V264, with the GST gate on each general course
CREATE OR REPLACE FUNCTION registration.student_choose(p_registration uuid, p_offerings uuid[])
RETURNS int
LANGUAGE plpgsql AS $$
DECLARE r registration.course_registration; m record; n int := 0; v_gate text;
BEGIN
    SELECT * INTO r FROM registration.course_registration WHERE id = p_registration;
    IF NOT FOUND THEN RAISE EXCEPTION 'no such registration' USING ERRCODE = '23503'; END IF;
    IF r.status NOT IN ('DRAFT','RETURNED') THEN
        RAISE EXCEPTION 'this registration is %; it is not edited', lower(r.status) USING ERRCODE = '23514',
            HINT = 'A submitted registration is changed by the level adviser returning it.';
    END IF;
    DELETE FROM registration.entry WHERE registration_id = p_registration AND entry_type NOT IN ('CARRYOVER','DEFERRED');
    -- a deferred course or a carry-over that has since become due is added to a draft that predates it
    FOR m IN SELECT * FROM registration.student_menu(r.student_id, r.session, r.semester) WHERE carryover LOOP
        INSERT INTO registration.entry (registration_id, offering_id, units, entry_type)
        VALUES (p_registration, m.offering_id, m.units, CASE WHEN m.deferred THEN 'DEFERRED' ELSE 'CARRYOVER' END)
        ON CONFLICT (registration_id, offering_id) DO NOTHING;
    END LOOP;
    FOR m IN SELECT * FROM registration.student_menu(r.student_id, r.session, r.semester) WHERE NOT carryover AND offering_id = ANY(p_offerings) LOOP
        -- V314: a GST or EPS course is registered only by a student whose GST fee is paid
        v_gate := registration.gst_gate(r.student_id, r.session, m.course_code);
        IF v_gate IS NOT NULL THEN
            RAISE EXCEPTION '%', v_gate USING ERRCODE = '23514', HINT = 'Pay the GST fee on GST & EPS; registration opens the moment the payment is confirmed.';
        END IF;
        INSERT INTO registration.entry (registration_id, offering_id, units, entry_type)
        VALUES (p_registration, m.offering_id, m.units,
                CASE WHEN m.basis = 'GST' OR m.kind = 'GST' THEN 'GST' WHEN m.basis = 'Borrowed' THEN 'BORROWED'
                     WHEN m.basis = 'Elective' OR m.kind = 'Elective' THEN 'ELECTIVE' ELSE 'CURRENT' END)
        ON CONFLICT (registration_id, offering_id) DO NOTHING;
        n := n + 1;
    END LOOP;
    RETURN registration.units_of(p_registration);
END $$;

-- add during add/drop: as V195, with the GST gate
CREATE OR REPLACE FUNCTION registration.student_add(p_student uuid, p_session text, p_semester int, p_offering uuid)
RETURNS int
LANGUAGE plpgsql AS $$
DECLARE r registration.course_registration; m record; lim policy.level_limit; v_units int; v_type text; v_status text; v_gate text;
BEGIN
    SELECT * INTO r FROM registration.course_registration WHERE student_id = p_student AND session = p_session AND semester = p_semester;
    IF NOT FOUND THEN RAISE EXCEPTION 'register first, then add or drop' USING ERRCODE = '23514'; END IF;
    IF r.status = 'LOCKED' THEN RAISE EXCEPTION 'this registration is locked and cannot be changed' USING ERRCODE = '23514'; END IF;
    IF NOT registration.add_drop_open(p_session, p_semester) THEN
        RAISE EXCEPTION 'add and drop is not open for % semester %', p_session, p_semester USING ERRCODE = '23514',
            HINT = 'It runs while the semester is open, up to the late-registration deadline set by the Registry.';
    END IF;
    IF NOT finance.clears(p_student, p_session, 'REGISTRATION') THEN
        RAISE EXCEPTION 'the Bursary has not cleared you for registration in %', p_session USING ERRCODE = '23514';
    END IF;

    SELECT * INTO m FROM registration.student_menu(p_student, p_session, p_semester) WHERE offering_id = p_offering AND NOT carryover;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'that course is not offered to your programme at your level this semester' USING ERRCODE = '23514';
    END IF;
    -- V314: a GST or EPS course is added only by a student whose GST fee is paid
    v_gate := registration.gst_gate(p_student, p_session, m.course_code);
    IF v_gate IS NOT NULL THEN
        RAISE EXCEPTION '%', v_gate USING ERRCODE = '23514', HINT = 'Pay the GST fee on GST & EPS; it opens the moment the payment is confirmed.';
    END IF;
    v_units := m.units;
    v_type := CASE WHEN m.basis = 'GST' OR m.kind = 'GST' THEN 'GST' WHEN m.basis = 'Borrowed' THEN 'BORROWED'
                   WHEN m.basis = 'Elective' OR m.kind = 'Elective' THEN 'ELECTIVE' ELSE 'CURRENT' END;
    -- an approved registration has no further approval step, so the added course is examinable at once;
    -- a still-submitted one keeps REGISTERED and the HOD's approval flips it with the batch (RegistrationRepository)
    v_status := CASE WHEN r.status = 'APPROVED' THEN 'APPROVED' ELSE 'REGISTERED' END;

    -- would this exceed the level's maximum?
    SELECT * INTO lim FROM policy.level_limit WHERE level = r.level;
    IF FOUND AND registration.units_of(r.id) + v_units > lim.max_units THEN
        RAISE EXCEPTION 'adding this course puts you at % units, over the maximum of % at % level',
            registration.units_of(r.id) + v_units, lim.max_units, r.level USING ERRCODE = '23514',
            HINT = 'Drop a course first, or ask your Head of Department for an overload.';
    END IF;

    -- reinstate a dropped entry, or add a new one
    IF EXISTS (SELECT 1 FROM registration.entry WHERE registration_id = r.id AND offering_id = p_offering) THEN
        UPDATE registration.entry SET status = v_status, units = v_units, entry_type = v_type
         WHERE registration_id = r.id AND offering_id = p_offering;
    ELSE
        INSERT INTO registration.entry (registration_id, offering_id, units, entry_type, status)
        VALUES (r.id, p_offering, v_units, v_type, v_status);
    END IF;
    RETURN registration.units_of(r.id);
END $$;

-- submission: as V246, with the whole-registration GST gate where the University has switched it on
CREATE OR REPLACE FUNCTION registration.student_submit(p_registration uuid)
RETURNS text
LANGUAGE plpgsql AS $$
DECLARE r registration.course_registration; lim policy.level_limit; units int; st record; v_gate text;
BEGIN
    SELECT * INTO r FROM registration.course_registration WHERE id = p_registration;
    IF NOT FOUND THEN RAISE EXCEPTION 'no such registration' USING ERRCODE = '23503'; END IF;
    IF r.status NOT IN ('DRAFT', 'RETURNED') THEN RETURN 'already ' || lower(r.status); END IF;
    IF NOT finance.semester_cleared(r.student_id, r.session, r.semester) THEN
        RAISE EXCEPTION 'the % semester school fees for % are not fully paid',
            CASE r.semester WHEN 1 THEN 'first' WHEN 2 THEN 'second' WHEN 3 THEN 'third' ELSE r.semester::text END, r.session
            USING ERRCODE = '23514',
            HINT = 'Course registration for a semester opens when that semester''s school fees are cleared in full; the position updates the moment a payment is confirmed.';
    END IF;
    -- V314: where the University holds the whole registration on the GST fee, an unpaid student does not submit
    v_gate := registration.gst_gate(r.student_id, r.session, NULL);
    IF v_gate IS NOT NULL THEN
        RAISE EXCEPTION '%', v_gate USING ERRCODE = '23514', HINT = 'Pay the GST fee on GST & EPS; submission opens the moment the payment is confirmed.';
    END IF;
    -- and a GST/EPS course already on the draft is not submitted unpaid either
    SELECT registration.gst_gate(r.student_id, r.session, o.course_code) INTO v_gate
      FROM registration.entry e JOIN catalogue.offering o ON o.id = e.offering_id JOIN catalogue.course c ON c.code = o.course_code AND c.kind = 'GST'
     WHERE e.registration_id = p_registration AND e.status <> 'DROPPED' AND registration.gst_gate(r.student_id, r.session, o.course_code) IS NOT NULL
     LIMIT 1;
    IF v_gate IS NOT NULL THEN
        RAISE EXCEPTION '%', v_gate USING ERRCODE = '23514', HINT = 'Pay the GST fee on GST & EPS, or remove the GST/EPS courses from the registration.';
    END IF;
    units := registration.units_of(p_registration);
    SELECT * INTO lim FROM policy.level_limit WHERE level = r.level;
    IF FOUND AND (units < lim.min_units OR units > lim.max_units) THEN
        RAISE EXCEPTION 'the registration carries % units; at % level the range is % to %', units, r.level, lim.min_units, lim.max_units
        USING ERRCODE = '23514', HINT = 'Add or drop courses to bring it within the range, or obtain an overload approval from the Head of Department.';
    END IF;
    SELECT * INTO st FROM assessment.student_standing(r.student_id);
    IF FOUND AND st.standing IN ('PROBATION', 'ADVISED_TO_WITHDRAW') AND lim.probation_max_units IS NOT NULL AND units > lim.probation_max_units THEN
        RAISE EXCEPTION 'you are on probation (CGPA % after % % semester); the registration carries % units and the limit on probation at % level is %',
            st.cgpa, st.pronounced_session, CASE st.pronounced_semester WHEN 1 THEN 'first' ELSE 'second' END, units, r.level, lim.probation_max_units
        USING ERRCODE = '23514', HINT = 'Drop courses to bring the registration within the probation limit. The carryovers stay; choose fewer new courses.';
    END IF;
    UPDATE registration.course_registration SET status = 'SUBMITTED', submitted_at = now() WHERE id = p_registration;
    RETURN 'submitted';
END $$;

-- ── 6 · the student is told when the GST payment is confirmed ────────────────────────────────
CREATE OR REPLACE FUNCTION finance.gst_payment_notice()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE r record;
BEGIN
    FOR r IN SELECT * FROM people.student_reach(NEW.student_id) LOOP
        IF r.email IS NOT NULL THEN
            PERFORM platform.queue_notice('EMAIL', r.email, 'GST fee payment confirmed',
                'Your GST fee payment of NGN ' || to_char(NEW.amount, 'FM999,999,999,990.00') || ' for ' || NEW.session || ' is confirmed (receipt '
                || coalesce(NEW.receipt_no, NEW.reference) || '). It covers both GST and EPS: you may now register your GST and EPS courses on the portal.'
                || E'\n\nBursary, Rev. Fr. Moses Orshio Adasu University, Makurdi', 'student', NEW.student_id);
        END IF;
        IF r.phone IS NOT NULL THEN
            PERFORM platform.queue_notice('SMS', r.phone, 'GST fee confirmed',
                'MOAUM: your GST fee for ' || NEW.session || ' is confirmed (receipt ' || coalesce(NEW.receipt_no, NEW.reference) || '). Register your GST/EPS courses on the portal.',
                'student', NEW.student_id);
        END IF;
    END LOOP;
    RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS trg_gst_payment_notice ON finance.payment_reference;
CREATE TRIGGER trg_gst_payment_notice AFTER UPDATE OF confirmed_at ON finance.payment_reference
    FOR EACH ROW WHEN (NEW.confirmed_at IS NOT NULL AND OLD.confirmed_at IS NULL AND NEW.purpose LIKE 'GST fee %')
    EXECUTE FUNCTION finance.gst_payment_notice();

-- ── 7 · what the offices read: the population and the courses, set-based ─────────────────────
CREATE OR REPLACE FUNCTION finance.gst_population(p_session text, p_semester int)
RETURNS TABLE (student_id uuid, number text, surname text, other_names text, sex text, faculty_code text, faculty text, dept_code text, department text,
               programme_code text, programme text, level int, status text, entry_mode text,
               required boolean, fee numeric, stated boolean, paid numeric, entitled boolean, pay_state text, reference text, paid_at timestamptz,
               gst_registered boolean, eps_registered boolean, gst_courses int, eps_courses int, registered_at timestamptz)
LANGUAGE sql STABLE AS $$
    WITH base AS (
        SELECT s.id, coalesce(s.matric_no, s.admission_no) AS number, s.surname, s.other_names, s.sex,
               p.faculty_code, f.name AS faculty, p.dept_code, d.name AS department, s.programme_code, p.name AS programme,
               s.current_level AS level, s.status, s.entry_mode
          FROM people.student s
          JOIN ref.programme p ON p.code = s.programme_code AND p.category = 'UNDER GRADUATE'
          JOIN ref.department d ON d.code = p.dept_code
          JOIN ref.faculty f ON f.code = d.faculty_code
         WHERE s.status IN ('ADMITTED', 'ACTIVE', 'PROBATION')),
    req AS (SELECT DISTINCT co.programme_code, co.level
              FROM catalogue.course_offer co JOIN catalogue.course c ON c.code = co.course_code AND c.kind = 'GST' AND c.state <> 'ENDED'),
    fees AS (SELECT f.id, f.amount, f.level, f.entry_mode, f.faculty_code, f.programme_code, f.stated_at
               FROM finance.gst_fee f WHERE f.session = p_session AND f.superseded_at IS NULL AND f.effective_from <= current_date),
    pays AS (SELECT r.student_id, sum(r.amount) AS paid, max(r.confirmed_at) AS paid_at, count(*) AS n, (array_agg(r.reference ORDER BY r.confirmed_at DESC))[1] AS reference
               FROM finance.payment_reference r
              WHERE r.session = p_session AND r.purpose LIKE 'GST fee %' AND r.confirmed_at IS NOT NULL
                AND NOT EXISTS (SELECT 1 FROM finance.refund rf WHERE rf.reference = r.reference AND rf.state IN ('APPROVED', 'PAID'))
              GROUP BY r.student_id),
    pend AS (SELECT DISTINCT r.student_id FROM finance.payment_reference r
              WHERE r.session = p_session AND r.purpose LIKE 'GST fee %' AND r.confirmed_at IS NULL AND r.expires_at > now()),
    regs AS (SELECT cr.student_id,
                    count(*) FILTER (WHERE c.general_office = 'GST') AS gst_courses,
                    count(*) FILTER (WHERE c.general_office = 'EPS') AS eps_courses,
                    min(cr.submitted_at) AS registered_at
               FROM registration.course_registration cr
               JOIN registration.entry e ON e.registration_id = cr.id AND e.status <> 'DROPPED'
               JOIN catalogue.offering o ON o.id = e.offering_id
               JOIN catalogue.course c ON c.code = o.course_code AND c.kind = 'GST'
              WHERE cr.session = p_session AND (p_semester IS NULL OR cr.semester = p_semester)
              GROUP BY cr.student_id)
    SELECT b.id, b.number, b.surname, b.other_names, b.sex, b.faculty_code, b.faculty, b.dept_code, b.department, b.programme_code, b.programme,
           b.level, b.status, b.entry_mode,
           (rq.programme_code IS NOT NULL),
           coalesce(fr.amount, 0), (fr.id IS NOT NULL),
           coalesce(py.paid, 0),
           (coalesce(py.n, 0) > 0 OR (fr.id IS NOT NULL AND fr.amount = 0)),
           CASE WHEN coalesce(py.n, 0) > 0 OR (fr.id IS NOT NULL AND fr.amount = 0) THEN 'PAID'
                WHEN rq.programme_code IS NULL THEN 'NOT_REQUIRED'
                WHEN fr.id IS NULL THEN 'NOT_STATED'
                WHEN pd.student_id IS NOT NULL THEN 'PENDING'
                ELSE 'NOT_PAID' END,
           py.reference, py.paid_at,
           coalesce(rg.gst_courses, 0) > 0, coalesce(rg.eps_courses, 0) > 0, coalesce(rg.gst_courses, 0)::int, coalesce(rg.eps_courses, 0)::int, rg.registered_at
      FROM base b
      LEFT JOIN req rq ON rq.programme_code = b.programme_code AND rq.level = b.level
      LEFT JOIN LATERAL (SELECT f.id, f.amount FROM fees f
                          WHERE (f.programme_code IS NULL OR f.programme_code = b.programme_code) AND (f.faculty_code IS NULL OR f.faculty_code = b.faculty_code)
                            AND (f.level IS NULL OR f.level = b.level) AND (f.entry_mode IS NULL OR f.entry_mode = b.entry_mode)
                          ORDER BY (f.programme_code IS NOT NULL) DESC, (f.faculty_code IS NOT NULL) DESC, (f.level IS NOT NULL) DESC, (f.entry_mode IS NOT NULL) DESC, f.stated_at DESC
                          LIMIT 1) fr ON true
      LEFT JOIN pays py ON py.student_id = b.id
      LEFT JOIN pend pd ON pd.student_id = b.id
      LEFT JOIN regs rg ON rg.student_id = b.id
$$;
COMMENT ON FUNCTION finance.gst_population(text, int) IS
  'One row per undergraduate of the register for a session (V314): whether their programme requires GST/EPS courses at their level, the GST fee the Bursar stated for them, what they paid, whether they are entitled, and their GST and EPS registrations (of one semester when asked). The one source of the GST and EPS dashboards, lists and exports.';

CREATE OR REPLACE FUNCTION finance.gst_course_stats(p_session text, p_semester int, p_office text)
RETURNS TABLE (offering_id uuid, course_code text, title text, units int, level int, semester int, general_office text, dept_code text, department text,
               lecturer_id uuid, lecturer text, state text, registered bigint, entitled bigint, sheet_id uuid, stage text, graded bigint, published_at timestamptz)
LANGUAGE sql STABLE AS $$
    WITH pays AS (SELECT DISTINCT r.student_id FROM finance.payment_reference r
                   WHERE r.session = p_session AND r.purpose LIKE 'GST fee %' AND r.confirmed_at IS NOT NULL)
    SELECT o.id, c.code, c.title, c.units, c.level, o.semester, c.general_office, c.dept_code, d.name, o.lecturer_id,
           CASE WHEN p.id IS NULL THEN NULL ELSE p.surname || ', ' || p.given_names END, c.state,
           (SELECT count(*) FROM registration.entry e WHERE e.offering_id = o.id AND e.status <> 'DROPPED'),
           (SELECT count(*) FROM registration.entry e JOIN registration.course_registration cr ON cr.id = e.registration_id
              JOIN pays py ON py.student_id = cr.student_id WHERE e.offering_id = o.id AND e.status <> 'DROPPED'),
           sh.id, sh.stage,
           CASE WHEN sh.id IS NULL THEN 0 ELSE (SELECT count(*) FROM assessment.latest_scores(sh.id) WHERE outcome = 'GRADED') END,
           sh.published_at
      FROM catalogue.offering o
      JOIN catalogue.course c ON c.code = o.course_code AND c.kind = 'GST'
      JOIN ref.department d ON d.code = c.dept_code
      LEFT JOIN iam.person p ON p.id = o.lecturer_id
      LEFT JOIN assessment.score_sheet sh ON sh.offering_id = o.id
     WHERE o.session = p_session AND (p_semester IS NULL OR o.semester = p_semester) AND (p_office IS NULL OR c.general_office = p_office)
     ORDER BY o.semester, c.level, c.code
$$;

COMMIT;

-- the GST references of a session, found without a scan of the ledger (outside the transaction: CONCURRENTLY)
CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_pref_gst_fee ON finance.payment_reference (session, student_id) WHERE purpose LIKE 'GST fee %';
