output "alb_dns_name" { value = aws_lb.main.dns_name }
output "ecr_api" { value = aws_ecr_repository.svc["api"].repository_url }
output "ecr_frontend" { value = aws_ecr_repository.svc["frontend"].repository_url }
output "cluster" { value = aws_ecs_cluster.main.name }
output "api_task_definition" { value = aws_ecs_task_definition.api.family }
output "frontend_task_definition" { value = aws_ecs_task_definition.frontend.family }
output "migrate_task_definition" { value = aws_ecs_task_definition.migrate.family }
output "private_subnets" { value = aws_subnet.private[*].id }
output "tasks_security_group" { value = aws_security_group.tasks.id }
output "db_endpoint" { value = aws_db_instance.main.address }
output "db_master_secret_arn" { value = aws_db_instance.main.master_user_secret[0].secret_arn }
output "github_deploy_role_arn" { value = aws_iam_role.github_deploy.arn }
output "alerts_topic_arn" { value = aws_sns_topic.alerts.arn }
output "ops_bucket" { value = aws_s3_bucket.ops.bucket }
output "bastion_instance_id" { value = var.enable_bastion ? aws_instance.bastion[0].id : null }
output "files_bucket" { value = aws_s3_bucket.files.bucket }
