"use client";
/** The support desk's own audit (V346): every act ICT Support did on a student — when, who, which student, the module, the act
 *  in words, the ticket, the reason and the result — with the overrides marked and the rule each set aside. This is the
 *  support audit trail, not the student's academic history. Filtered and paged by the server; exported where the posting
 *  carries exports. */
import Link from "next/link";
import { useQueryNav } from "@/lib/query-nav";
import { Btn, LinkBtn, PageHead, Panel, PBody, Pil, Tiles } from "@/components/proto/ui";
import { DTable } from "@/components/proto/DTable";
import { Field } from "@/components/proto/blocks";
import { brandedXlsx, docSerial, downloadBlob } from "@/lib/exportbrand";
import { notifyProblem } from "@/components/proto/Toast";
import { ACTION_WORD, MODULE_WORD, RESULT_WORD } from "@/lib/support";

export interface AuditFilters { module: string; action: string; from: string; to: string; overrides: string }
export interface AuditRow {
  id: string; at: string; action: string; module: string; summary: string | null; reason: string; outcome: string; override: boolean; normal_rule: string | null; method: string | null;
  payment_reference: string | null; session: string | null; semester: number | null; agent: string; agent_office: string; student_id: string; student: string; number: string | null;
  ticket_id: string | null; ticket_number: string | null; result: string;
}
export interface AuditList { total: number; page: number; size: number; rows: AuditRow[]; summary?: { module: string; acts: number; overrides: number; week: number }[] }

const when = (iso: string) => new Date(iso).toLocaleString("en-GB", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" });

export function SupportAudit({ list, filters, page, generatedBy }: { list: AuditList; filters: AuditFilters; page: number; generatedBy: string | null }) {
  const go = useQueryNav();
  function nav(patch: Partial<AuditFilters & { page: string }>) {
    const next: Record<string, string> = { ...filters, page: "1", ...patch };
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(next)) if (v && !(k === "page" && v === "1")) qs.set(k, v);
    go(`/helpdesk/audit${qs.toString() ? "?" + qs.toString() : ""}`);
  }
  const pages = Math.max(1, Math.ceil(list.total / (list.size || 50)));
  const HEAD = ["Date", "Agent", "Student", "Number", "Module", "Action", "Ticket", "Reason", "Result", "Override: the rule set aside"];
  const rowsOf = (rows: AuditRow[]) => rows.map((r) => [when(r.at), r.agent, r.student, r.number ?? "", MODULE_WORD[r.module] ?? r.module, r.summary ?? ACTION_WORD[r.action] ?? r.action,
    r.ticket_number ?? "", r.reason, RESULT_WORD[r.result]?.[0] ?? r.result, r.override ? r.normal_rule ?? "" : ""]);
  async function exportAll() {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(filters)) if (v) qs.set(k, v);
    qs.set("export", "true"); qs.set("size", "5000");
    const r = await fetch(`/api/bff/api/v1/helpdesk/support/actions?${qs.toString()}`);
    if (!r.ok) { notifyProblem((await r.json().catch(() => null)) ?? { status: r.status, title: r.statusText }); return; }
    const j = (await r.json()) as AuditList;
    downloadBlob(await brandedXlsx("Support action history — ICT Support", HEAD, rowsOf(j.rows), { sheetName: "Support acts", serial: docSerial("SAH"), meta: [["Generated by", generatedBy ?? "—"]] }), "support-action-history.xlsx");
  }
  const sum = list.summary ?? [];
  const of = (m: string) => sum.find((x) => x.module === m);
  return (
    <>
      <PageHead title="Support Action History" eyebrow="ICT Support Desk"
        description="Every act ICT Support did on a student's record, registration, password or payment — who, for which ticket, why, and what came of it. Overrides are marked with the rule they set aside."
        actions={<><LinkBtn href="/helpdesk">Support Desk</LinkBtn><Btn kind="secondary" onClick={() => void exportAll()}>Excel</Btn></>} />
      {sum.length ? (
        <Tiles cls="grid--5" items={[
          ["Course registration", String(of("COURSE_REGISTRATION")?.acts ?? 0), null, `${of("COURSE_REGISTRATION")?.overrides ?? 0} overrides · ${of("COURSE_REGISTRATION")?.week ?? 0} this week`, "/helpdesk/audit?module=COURSE_REGISTRATION"],
          ["Payments", String(of("PAYMENT")?.acts ?? 0), null, `${of("PAYMENT")?.week ?? 0} this week`, "/helpdesk/audit?module=PAYMENT"],
          ["Password resets", String(of("AUTHENTICATION")?.acts ?? 0), null, `${of("AUTHENTICATION")?.week ?? 0} this week`, "/helpdesk/audit?module=AUTHENTICATION"],
          ["Record edits", String(of("STUDENT_RECORD")?.acts ?? 0), null, `${of("STUDENT_RECORD")?.week ?? 0} this week`, "/helpdesk/audit?module=STUDENT_RECORD"],
          ["Tickets and escalations", String(of("TICKET")?.acts ?? 0), null, `${of("TICKET")?.week ?? 0} this week`, "/helpdesk/audit?module=TICKET"],
        ]} />
      ) : null}
      <form className="filterbar" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); nav({ module: String(f.get("module") ?? ""), from: String(f.get("from") ?? ""), to: String(f.get("to") ?? ""), overrides: f.get("overrides") ? "true" : "" }); }}>
        <Field id="sa-module" label="Module"><select id="sa-module" name="module" className="ctl" defaultValue={filters.module}>
          <option value="">Every module</option>{Object.entries(MODULE_WORD).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
        </select></Field>
        <Field id="sa-from" label="From"><input id="sa-from" name="from" type="date" className="ctl" defaultValue={filters.from} /></Field>
        <Field id="sa-to" label="To"><input id="sa-to" name="to" type="date" className="ctl" defaultValue={filters.to} /></Field>
        <label className="row row--inline row--tight" style={{ alignSelf: "flex-end" }}><input type="checkbox" className="chk" name="overrides" defaultChecked={filters.overrides === "true"} /> Overrides only</label>
        <button type="submit" className="btn btn--primary btn--sm" style={{ alignSelf: "flex-end" }}>Filter</button>
      </form>
      <Panel title={`${list.total.toLocaleString()} act${list.total === 1 ? "" : "s"}`} right={pages > 1 ? `Page ${page} of ${pages}` : undefined}>
        {list.rows.length ? (
          <DTable pageSize={0} cols={["Date", "Agent", "Student", "Module", "Action", "Ticket|mid", "Reason", "Result|mid"]} rows={list.rows.map((r) => [
            <span key="w" className="sub2 tnum">{when(r.at)}</span>,
            <span key="a">{r.agent}<div className="sub2">{r.agent_office}</div></span>,
            <span key="s"><Link className="lnk" href={`/helpdesk/students/${r.student_id}?tab=history`}>{r.student}</Link><div className="sub2 tnum">{r.number ?? ""}</div></span>,
            <span key="m" className="sub2">{MODULE_WORD[r.module] ?? r.module}</span>,
            <span key="k"><b>{r.summary ?? ACTION_WORD[r.action] ?? r.action}</b>{r.override ? <><Pil kind="warn" className="ml-1">Override</Pil><div className="sub2">Normal rule: {r.normal_rule}</div></> : null}{r.payment_reference ? <div className="sub2 tnum">{r.payment_reference}</div> : null}</span>,
            r.ticket_id ? <Link key="t" href={`/helpdesk/tickets/${r.ticket_id}`} className="lnk tnum">{r.ticket_number}</Link> : <span key="t" className="sub2">—</span>,
            <span key="r" className="sub2">{r.reason}</span>,
            <Pil key="res" kind={RESULT_WORD[r.result]?.[1] ?? "grey"}>{RESULT_WORD[r.result]?.[0] ?? r.result}</Pil>,
          ])} />
        ) : <PBody><div className="sub2">No support act matches.</div></PBody>}
        {pages > 1 ? (
          <PBody><div className="row row--inline" style={{ gap: "var(--s-2)" }}>
            {page > 1 ? <button className="btn btn--ghost btn--sm" onClick={() => nav({ page: String(page - 1) })}>Previous</button> : null}
            {page < pages ? <button className="btn btn--ghost btn--sm" onClick={() => nav({ page: String(page + 1) })}>Next</button> : null}
          </div></PBody>
        ) : null}
      </Panel>
    </>
  );
}
