/**
 * Every office's menu. The items and their routes are the prototype's (proto/part17.html
 * ROLES); the staff offices' headings were regrouped into one section vocabulary in the
 * harmonization of September 2026 — Overview, Academic, Students, Admissions, Finance, Staff,
 * Services, Reports, Administration, Me. Students and applicants keep their journey menus.
 * An office without a menu here gets the fallback in Shell.tsx. Regenerated by script; edit
 * the script, not the file.
 */
export interface MenuItem { id: string; icon: string; label: string; badge?: string }
export interface MenuGroup { name: string; items: MenuItem[] }
export interface Menu { label: string; home: string; groups: MenuGroup[] }

export const MENUS: Record<string, Menu> = {
  "siwes": {
    "label": "SIWES Coordinator",
    "home": "r/academic",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/academic", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "r/siwes", "icon": "swap", "label": "SIWES Supervision" },
          { "id": "r/mysiwes", "icon": "user", "label": "My SIWES Students" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "lecturer": {
    "label": "Lecturer",
    "home": "r/lecturer",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/lecturer", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/eligibility", "icon": "swap", "label": "Who May Register It" },
          { "id": "t/lms", "icon": "book", "label": "Course Spaces" },
          { "id": "r/upload", "icon": "box", "label": "Upload Material" },
          { "id": "t/teaching", "icon": "cal", "label": "My Teaching & Timetable" },
          { "id": "t/sheet", "icon": "doc", "label": "Score Entry", "badge": "2" },
          { "id": "t/bulk", "icon": "box", "label": "Upload Results (bulk)" },
          { "id": "t/scores", "icon": "doc", "label": "My Score Sheets" },
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/chain", "icon": "check", "label": "Approval Chain" },
          { "id": "t/cbtbank", "icon": "flask", "label": "Question Bank" },
          { "id": "t/projects", "icon": "flask", "label": "My Projects" },
          { "id": "t/ethics", "icon": "scale", "label": "Ethics & Repository" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/supervision", "icon": "check", "label": "Postings I Supervise" },
          { "id": "r/classlist", "icon": "user", "label": "Registered Students" },
          { "id": "r/mysiwes", "icon": "user", "label": "My SIWES Students" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "hod": {
    "label": "Head of Department",
    "home": "r/hod",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/hod", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "r/allocate", "icon": "swap", "label": "Teaching Allocation", "badge": "3" },
          { "id": "t/deptcourses", "icon": "book", "label": "Department Courses", "badge": "2" },
          { "id": "t/structure", "icon": "book", "label": "Programme Structure" },
          { "id": "t/resultdesk", "icon": "check", "label": "Result Desk", "badge": "4" },
          { "id": "t/approvals", "icon": "check", "label": "Departmental Approvals" },
          { "id": "t/queries", "icon": "bell", "label": "Result Queries" },
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Broadsheet" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" },
          { "id": "t/scores", "icon": "doc", "label": "Score Sheets" },
          { "id": "t/sheet", "icon": "doc", "label": "Score Entry", "badge": "2" },
          { "id": "t/bulk", "icon": "box", "label": "Upload Results (bulk)" },
          { "id": "t/eligibility", "icon": "swap", "label": "Who May Register It" },
          { "id": "t/lms", "icon": "book", "label": "Course Spaces" },
          { "id": "r/upload", "icon": "box", "label": "Upload Material" },
          { "id": "t/teaching", "icon": "cal", "label": "My Teaching & Timetable" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/clearance", "icon": "check", "label": "Department Clearance" },
          { "id": "t/transfers", "icon": "swap", "label": "Inter-Departmental Transfer" },
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "r/siwes", "icon": "swap", "label": "SIWES Supervision" },
          { "id": "r/classlist", "icon": "user", "label": "Registered Students" },
          { "id": "t/students", "icon": "cap", "label": "Students" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/pgadmissions", "icon": "cap", "label": "PG Admissions" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/requisitions", "icon": "box", "label": "Requisitions" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/deptstaff", "icon": "user", "label": "Department Staff" },
          { "id": "t/leave", "icon": "cal", "label": "Leave Requests", "badge": "2" },
          { "id": "t/appraisal", "icon": "chart", "label": "Appraisal" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "dean": {
    "label": "Dean",
    "home": "r/dean",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/dean", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "r/allocate", "icon": "swap", "label": "Teaching Allocation" },
          { "id": "t/resultdesk", "icon": "check", "label": "Result Desk", "badge": "7" },
          { "id": "t/approvals", "icon": "check", "label": "Faculty Board" },
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Broadsheet" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" },
          { "id": "t/graduation", "icon": "cap", "label": "Graduation List" },
          { "id": "t/sheet", "icon": "doc", "label": "Score Entry" },
          { "id": "t/bulk", "icon": "box", "label": "Upload Results (bulk)" },
          { "id": "t/scores", "icon": "doc", "label": "My Score Sheets" },
          { "id": "t/eligibility", "icon": "swap", "label": "Who May Register It" },
          { "id": "t/lms", "icon": "book", "label": "Course Spaces" },
          { "id": "r/upload", "icon": "box", "label": "Upload Material" },
          { "id": "t/projects", "icon": "flask", "label": "Research in the Faculty" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/clearance", "icon": "check", "label": "Faculty Clearance" },
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/students", "icon": "cap", "label": "Students" },
          { "id": "r/classlist", "icon": "user", "label": "Registered Students" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/pgadmissions", "icon": "cap", "label": "PG Admissions" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/budget", "icon": "chart", "label": "Faculty Budget" },
          { "id": "t/requisitions", "icon": "box", "label": "Requisitions" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "hrm": {
    "label": "Director of Human Resource Management",
    "home": "t/hrm",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/hrm", "icon": "user", "label": "Movements", "badge": "8" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/payroll", "icon": "card", "label": "Payroll" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/movement", "icon": "doc", "label": "Open a Movement" },
          { "id": "t/staff", "icon": "user", "label": "Staff Records" },
          { "id": "t/recruit", "icon": "user", "label": "Recruitment" },
          { "id": "t/leave", "icon": "cal", "label": "Leave Requests", "badge": "2" },
          { "id": "t/appraisal", "icon": "chart", "label": "Appraisal" },
          { "id": "t/staffupload", "icon": "user", "label": "Upload Non-Academic Staff" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "housing": {
    "label": "Deputy Registrar (Housing, Welfare and Passages)",
    "home": "t/housing",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/housing", "icon": "bed", "label": "Housing & Welfare", "badge": "6" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/staff", "icon": "user", "label": "Staff Records" }
        ]
      },
      {
        "name": "Services",
        "items": [
          { "id": "t/hostel", "icon": "bed", "label": "Hostel Allocation" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "audit": {
    "label": "Director of Internal Audit",
    "home": "t/prepayment",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/prepayment", "icon": "check", "label": "Payment Vouchers", "badge": "7" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/pv", "icon": "doc", "label": "A Voucher in Full" },
          { "id": "t/auditrevenue", "icon": "chart", "label": "Revenue & Student Income", "badge": "9" },
          { "id": "t/ledger", "icon": "card", "label": "Ledger" },
          { "id": "t/reconcile", "icon": "swap", "label": "Reconciliation" },
          { "id": "t/auditpayroll", "icon": "chart", "label": "Payroll Variance", "badge": "6" },
          { "id": "t/auditassets", "icon": "box", "label": "Assets Register", "badge": "!" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/auditstaff", "icon": "user", "label": "Staff Movements" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "exams": {
    "label": "Exams Officer (Programme)",
    "home": "r/exams",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/exams", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/exams", "icon": "flask", "label": "CBT Sessions", "badge": "!" },
          { "id": "t/cbtbank", "icon": "flask", "label": "Question Bank" },
          { "id": "t/scores", "icon": "doc", "label": "Score Sheets", "badge": "6" },
          { "id": "t/chain", "icon": "check", "label": "Approval Chain" },
          { "id": "t/approvals", "icon": "check", "label": "Verification Queue" },
          { "id": "t/queries", "icon": "bell", "label": "Result Queries" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "r/classlist", "icon": "user", "label": "Examination Roll" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "academic": {
    "label": "Academic Office",
    "home": "r/academic",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/academic", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/facultyupload", "icon": "cap", "label": "Upload or Create Faculties" },
          { "id": "t/programmeupload", "icon": "book", "label": "Upload or Create Programmes" },
          { "id": "t/departmentupload", "icon": "cap", "label": "Upload or Create Departments" },
          { "id": "t/courseupload", "icon": "doc", "label": "Upload or Create Courses" },
          { "id": "t/college", "icon": "swap", "label": "College of Health Sciences" },
          { "id": "t/session", "icon": "cal", "label": "Session & Semester Setup" },
          { "id": "t/examsession", "icon": "cal", "label": "Examination Sessions" },
          { "id": "t/graduation", "icon": "cap", "label": "Graduation" },
          { "id": "t/approvals", "icon": "check", "label": "Results to Senate" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/matriculation", "icon": "cap", "label": "Matriculation", "badge": "!" },
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/students", "icon": "cap", "label": "Student Records" },
          { "id": "t/biochange", "icon": "user", "label": "Biodata Changes", "badge": "4" },
          { "id": "r/classlist", "icon": "user", "label": "Registered Students" },
          { "id": "t/transfers", "icon": "swap", "label": "Inter-Departmental Transfer" },
          { "id": "t/clearance", "icon": "check", "label": "Clearance", "badge": "54" },
          { "id": "t/transcripts", "icon": "doc", "label": "Transcripts", "badge": "9" },
          { "id": "t/certificates", "icon": "cap", "label": "Certificates" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/admissionsetup", "icon": "doc", "label": "Admission Settings", "badge": "!" },
          { "id": "t/capsintake", "icon": "box", "label": "Upload Applicants and Candidates" },
          { "id": "t/candidatedata", "icon": "box", "label": "Upload Passport, DOB & O’Level" },
          { "id": "t/migrate", "icon": "box", "label": "Migrate Old-Portal Applicants" },
          { "id": "t/postutme", "icon": "chart", "label": "Compute PUTME Score" },
          { "id": "t/screening", "icon": "chart", "label": "Screening Register" },
          { "id": "t/putme", "icon": "doc", "label": "Upload PUTME Score" },
          { "id": "t/merit", "icon": "chart", "label": "Merit List" },
          { "id": "t/de-screening", "icon": "chart", "label": "Direct Entry Screening" },
          { "id": "t/pgadmissions", "icon": "cap", "label": "Postgraduate Admissions" },
          { "id": "t/applicants", "icon": "user", "label": "Report on Post-UTME Registration" },
          { "id": "t/admissions", "icon": "doc", "label": "Report on Admissions" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "bursar": {
    "label": "Bursar",
    "home": "r/bursar",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/bursar", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/clearance", "icon": "check", "label": "Financial Clearance" },
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/heldscripts", "icon": "alert", "label": "Held Scripts" },
          { "id": "t/feesetup", "icon": "card", "label": "Fee Setup and Schedule" },
          { "id": "t/legacyfees", "icon": "swap", "label": "Old Fees History" },
          { "id": "t/gateways", "icon": "card", "label": "Payment Gateways", "badge": "!" },
          { "id": "t/hanging", "icon": "alert", "label": "Hanging Payments", "badge": "7" },
          { "id": "t/exception", "icon": "alert", "label": "Payment Investigation", "badge": "!" },
          { "id": "t/payments", "icon": "card", "label": "Payments Query" },
          { "id": "t/paymenthistory", "icon": "upload", "label": "Payment History Upload" },
          { "id": "t/refunds", "icon": "swap", "label": "Refunds & Credits" },
          { "id": "t/fundsources", "icon": "card", "label": "Funding Sources" },
          { "id": "t/nelfund", "icon": "swap", "label": "Sources & Wallets" },
          { "id": "t/nelstatus", "icon": "user", "label": "NELFUND Applicants" },
          { "id": "t/nelmatch", "icon": "swap", "label": "Match a Remittance" },
          { "id": "t/pv", "icon": "doc", "label": "Payment Vouchers", "badge": "1" },
          { "id": "t/payroll", "icon": "card", "label": "Payroll", "badge": "3" },
          { "id": "t/budget", "icon": "chart", "label": "Budget" },
          { "id": "t/tenders", "icon": "box", "label": "Tenders" },
          { "id": "t/cashdesk", "icon": "card", "label": "Cash Office & Assets" },
          { "id": "t/accounts", "icon": "chart", "label": "Accounting & Books" },
          { "id": "t/ledger", "icon": "swap", "label": "Transactions & Accounts" },
          { "id": "t/reconcile", "icon": "swap", "label": "Reconciliation", "badge": "12" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "library": {
    "label": "Librarian",
    "home": "t/idcards",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/idcards", "icon": "user", "label": "Card Printing", "badge": "4" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/clearance", "icon": "check", "label": "Library Clearance", "badge": "7" }
        ]
      },
      {
        "name": "Services",
        "items": [
          { "id": "t/circulation", "icon": "book", "label": "Circulation" },
          { "id": "t/stores", "icon": "box", "label": "Stock & Acquisitions" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "security": {
    "label": "Chief Security Officer",
    "home": "t/idverify",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/idverify", "icon": "check", "label": "Verify a Card" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Services",
        "items": [
          { "id": "t/idcards", "icon": "user", "label": "Card Collection", "badge": "2" },
          { "id": "t/idlost", "icon": "alert", "label": "Lost & Replacement", "badge": "!" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "facultyexams": {
    "label": "Faculty Exams Officer",
    "home": "t/resultdesk",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/resultdesk", "icon": "check", "label": "Scrutiny Desk", "badge": "9" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Broadsheet" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" },
          { "id": "t/scores", "icon": "doc", "label": "Score Sheets" },
          { "id": "t/exams", "icon": "flask", "label": "Examinations" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "facultyofficer": {
    "label": "Faculty Officer",
    "home": "t/resultdesk",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/resultdesk", "icon": "check", "label": "Result Desk", "badge": "9" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Broadsheet" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" },
          { "id": "t/scores", "icon": "doc", "label": "Score Sheets" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/students", "icon": "cap", "label": "Students" },
          { "id": "t/matlist", "icon": "cap", "label": "Registered Students", "badge": "!" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "records": {
    "label": "Exams & Records",
    "home": "t/examsrec",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/examsrec", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/examsession", "icon": "cal", "label": "Examination Sessions", "badge": "!" },
          { "id": "t/resultdesk", "icon": "check", "label": "Validation Desk", "badge": "12" },
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/college", "icon": "swap", "label": "College of Health Sciences" },
          { "id": "t/legacy", "icon": "swap", "label": "Migrate from Old Portal" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Broadsheets" },
          { "id": "t/senate", "icon": "scale", "label": "Senate Schedule", "badge": "!" },
          { "id": "t/publish", "icon": "bell", "label": "Publication" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" },
          { "id": "t/graduation", "icon": "cap", "label": "Graduation Records" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/transcripts", "icon": "doc", "label": "Transcripts", "badge": "9" },
          { "id": "t/certificates", "icon": "cap", "label": "Certificates" },
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "dregistrar": {
    "label": "Deputy Registrar (Academic Affairs)",
    "home": "t/mgmt",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/mgmt", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/senate", "icon": "scale", "label": "Senate Schedule", "badge": "!" },
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Broadsheets" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/clearance", "icon": "check", "label": "Clearance" },
          { "id": "t/students", "icon": "cap", "label": "Student Records" },
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/transcripts", "icon": "doc", "label": "Transcripts" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/staffupload", "icon": "user", "label": "Upload Non-Academic Staff" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "dvc": {
    "label": "DVC (Academic)",
    "home": "t/mgmt",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/mgmt", "icon": "home", "label": "Dashboard" },
          { "id": "t/overview", "icon": "chart", "label": "Institutional Overview" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" },
          { "id": "t/senate", "icon": "scale", "label": "Senate Schedule" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Broadsheets" },
          { "id": "t/graduation", "icon": "cap", "label": "Graduation" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "doc", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "super": {
    "label": "Super Administrator",
    "home": "t/setup",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/setup", "icon": "server", "label": "Setup Console" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/session", "icon": "cal", "label": "Session & Semester Setup" },
          { "id": "t/college", "icon": "swap", "label": "College of Health Sciences" },
          { "id": "t/pipeline", "icon": "swap", "label": "Result Pipeline" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/lecturers", "icon": "user", "label": "Upload Lecturers" },
          { "id": "t/staffupload", "icon": "user", "label": "Upload Non-Academic Staff" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Administration",
        "items": [
          { "id": "t/users", "icon": "user", "label": "Users & Roles" },
          { "id": "t/channels", "icon": "bell", "label": "Notification Channels" },
          { "id": "t/migration", "icon": "box", "label": "Data Migration", "badge": "!" },
          { "id": "t/platform", "icon": "server", "label": "Platform" },
          { "id": "t/api", "icon": "swap", "label": "Integrations" },
          { "id": "t/audit", "icon": "shield", "label": "Audit Log" },
          { "id": "t/security", "icon": "shield", "label": "Security" },
          { "id": "t/dr", "icon": "box", "label": "Backups & Recovery" },
          { "id": "t/governance", "icon": "scale", "label": "Governance" },
          { "id": "t/helpdesk", "icon": "life", "label": "ICT Support Desk" },
          { "id": "t/helpdeskreports", "icon": "chart", "label": "ICT Support Reports" },
          { "id": "t/helpdesksettings", "icon": "server", "label": "ICT Support Settings" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "registrar": {
    "label": "Registrar",
    "home": "r/registrar",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/registrar", "icon": "home", "label": "Dashboard" },
          { "id": "t/overview", "icon": "chart", "label": "Institutional Overview" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/college", "icon": "swap", "label": "College of Health Sciences" },
          { "id": "t/approvals", "icon": "check", "label": "Senate Business" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/transfers", "icon": "swap", "label": "Inter-Departmental Transfer" },
          { "id": "t/students", "icon": "cap", "label": "Student Records" },
          { "id": "t/biochange", "icon": "user", "label": "Biodata Changes", "badge": "4" },
          { "id": "t/certificates", "icon": "cap", "label": "Certificates" },
          { "id": "t/clearance", "icon": "check", "label": "Clearance", "badge": "54" },
          { "id": "t/transcripts", "icon": "doc", "label": "Transcripts", "badge": "9" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/admissions", "icon": "doc", "label": "Admissions" },
          { "id": "t/applicants", "icon": "user", "label": "Admitted List" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/staff", "icon": "user", "label": "Staff Records" },
          { "id": "t/recruit", "icon": "user", "label": "Recruitment" },
          { "id": "t/staffupload", "icon": "user", "label": "Upload Non-Academic Staff" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Administration",
        "items": [
          { "id": "t/governance", "icon": "scale", "label": "Data Governance", "badge": "2" },
          { "id": "t/audit", "icon": "shield", "label": "Audit Trail" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "ict": {
    "label": "Director of ICT",
    "home": "t/platform",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/platform", "icon": "server", "label": "Platform & Integrations", "badge": "!" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/facultyupload", "icon": "cap", "label": "Upload or Create Faculties" },
          { "id": "t/programmeupload", "icon": "book", "label": "Upload or Create Programmes" },
          { "id": "t/departmentupload", "icon": "cap", "label": "Upload or Create Departments" },
          { "id": "t/courseupload", "icon": "doc", "label": "Upload or Create Courses" },
          { "id": "t/legacy", "icon": "box", "label": "Migrate from Old Portal" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/students", "icon": "cap", "label": "Student Records" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/putme", "icon": "doc", "label": "Post-UTME Scores" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/gateways", "icon": "card", "label": "Payment Gateways", "badge": "!" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/lecturers", "icon": "user", "label": "Upload Lecturers" },
          { "id": "t/staffupload", "icon": "user", "label": "Upload Non-Academic Staff" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Administration",
        "items": [
          { "id": "t/users", "icon": "user", "label": "Users & Roles", "badge": "1" },
          { "id": "t/mail", "icon": "server", "label": "Mail Server" },
          { "id": "t/sms", "icon": "server", "label": "SMS Gateway" },
          { "id": "t/notify", "icon": "bell", "label": "Notifications", "badge": "!" },
          { "id": "t/security", "icon": "shield", "label": "Security Posture", "badge": "!" },
          { "id": "t/api", "icon": "swap", "label": "API Management", "badge": "2" },
          { "id": "t/release", "icon": "box", "label": "Release Pipeline" },
          { "id": "t/dr", "icon": "life", "label": "Disaster Recovery" },
          { "id": "t/cloud", "icon": "chart", "label": "Cloud Readiness" },
          { "id": "t/audit", "icon": "shield", "label": "Audit Trail" },
          { "id": "t/governance", "icon": "scale", "label": "Data Governance", "badge": "2" },
          { "id": "t/helpdesk", "icon": "life", "label": "ICT Support Desk" },
          { "id": "t/helpdeskreports", "icon": "chart", "label": "ICT Support Reports" },
          { "id": "t/helpdesksettings", "icon": "server", "label": "ICT Support Settings" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "services": {
    "label": "Support Services",
    "home": "t/clinic",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/clinic", "icon": "heart", "label": "Clinic" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/clearance", "icon": "check", "label": "Student Clearance" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/requisitions", "icon": "box", "label": "Requisitions" },
          { "id": "t/tenders", "icon": "box", "label": "Tenders" }
        ]
      },
      {
        "name": "Services",
        "items": [
          { "id": "t/circulation", "icon": "book", "label": "Library Circulation" },
          { "id": "t/stores", "icon": "box", "label": "Stores & Assets" },
          { "id": "t/alumni", "icon": "cap", "label": "Alumni Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "admin": {
    "label": "System Administrator",
    "home": "r/admin",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/admin", "icon": "home", "label": "Administrator Dashboard" },
          { "id": "t/readiness", "icon": "chart", "label": "Go-Live Readiness" },
          { "id": "t/overview", "icon": "chart", "label": "Institutional Overview" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "r/allocate", "icon": "swap", "label": "Teaching Allocation" },
          { "id": "t/chain", "icon": "doc", "label": "Approval Chain" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/records", "icon": "chart", "label": "Records & Queries" },
          { "id": "t/clearance", "icon": "check", "label": "Clearance", "badge": "54" },
          { "id": "t/students", "icon": "cap", "label": "Student Records" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/putme", "icon": "doc", "label": "Post-UTME Scores" },
          { "id": "t/admissions", "icon": "doc", "label": "Admissions" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/gateways", "icon": "card", "label": "Payment Gateways", "badge": "!" },
          { "id": "t/accounts", "icon": "chart", "label": "Accounting & Books" },
          { "id": "t/ledger", "icon": "swap", "label": "Transactions & Accounts" },
          { "id": "t/reconcile", "icon": "swap", "label": "Reconciliation", "badge": "12" },
          { "id": "t/exception", "icon": "alert", "label": "Payment Investigation" },
          { "id": "t/feesched", "icon": "card", "label": "Fee Schedules" }
        ]
      },
      {
        "name": "Staff",
        "items": [
          { "id": "t/lecturers", "icon": "user", "label": "Upload Lecturers" },
          { "id": "t/staffupload", "icon": "user", "label": "Upload Non-Academic Staff" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Administration",
        "items": [
          { "id": "t/mail", "icon": "server", "label": "Mail Server" },
          { "id": "t/sms", "icon": "server", "label": "SMS Gateway" },
          { "id": "t/users", "icon": "user", "label": "Users & Roles" },
          { "id": "t/platform", "icon": "server", "label": "Platform & Integrations" },
          { "id": "t/security", "icon": "shield", "label": "Security Posture", "badge": "!" },
          { "id": "t/audit", "icon": "shield", "label": "Audit Trail" },
          { "id": "t/governance", "icon": "scale", "label": "Data Governance", "badge": "2" },
          { "id": "t/helpdesk", "icon": "life", "label": "ICT Support Desk" },
          { "id": "t/helpdeskreports", "icon": "chart", "label": "ICT Support Reports" },
          { "id": "t/helpdesksettings", "icon": "server", "label": "ICT Support Settings" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "vc": {
    "label": "Vice-Chancellor",
    "home": "t/overview",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/overview", "icon": "home", "label": "Institutional Overview" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/approvals", "icon": "check", "label": "Senate Business", "badge": "7" },
          { "id": "t/graduation", "icon": "cap", "label": "Graduation" },
          { "id": "t/projects", "icon": "flask", "label": "Research" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/budget", "icon": "card", "label": "Budget" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Administration",
        "items": [
          { "id": "t/audit", "icon": "shield", "label": "Audit Trail" },
          { "id": "t/governance", "icon": "scale", "label": "Data Governance" },
          { "id": "t/security", "icon": "shield", "label": "Security Posture" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "student": {
    "label": "Student",
    "home": "s/dashboard",
    "groups": [
      {
        "name": "Start here",
        "items": [
          { "id": "s/dashboard", "icon": "home", "label": "Dashboard" },
          { "id": "s/fees", "icon": "card", "label": "School Fees — Pay First" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "s/register", "icon": "book", "label": "Course Registration" },
          { "id": "s/reghistory", "icon": "chart", "label": "Registration History" },
          { "id": "s/results", "icon": "cap", "label": "Results" },
          { "id": "s/broadsheet", "icon": "chart", "label": "Result Broadsheet" },
          { "id": "s/query", "icon": "alert", "label": "Result Query" },
          { "id": "s/carryover", "icon": "swap", "label": "Carryover" },
          { "id": "s/transfer", "icon": "swap", "label": "Inter-Departmental Transfer" },
          { "id": "s/transcript", "icon": "doc", "label": "Transcript" }
        ]
      },
      {
        "name": "Learning",
        "items": [
          { "id": "s/courses", "icon": "book", "label": "My Courses" },
          { "id": "s/timetable", "icon": "cal", "label": "Timetable" },
          { "id": "s/attendance", "icon": "check", "label": "Attendance" },
          { "id": "s/exams", "icon": "cap", "label": "Examinations" }
        ]
      },
      {
        "name": "Services",
        "items": [
          { "id": "s/wallet", "icon": "swap", "label": "Wallet & Funding" },
          { "id": "s/hostel", "icon": "bed", "label": "Hostel" },
          { "id": "s/library", "icon": "book", "label": "Library" },
          { "id": "s/idcard", "icon": "user", "label": "Identity Card" },
          { "id": "s/health", "icon": "heart", "label": "Health" },
          { "id": "s/support", "icon": "life", "label": "Help & Requests" },
          { "id": "s/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      },
      {
        "name": "Account",
        "items": [
          { "id": "s/profile", "icon": "user", "label": "Profile" },
          { "id": "s/biodata", "icon": "doc", "label": "Biodata" },
          { "id": "s/notifications", "icon": "bell", "label": "Notifications" }
        ]
      }
    ]
  },
  "pgstudent": {
    "label": "Postgraduate Student",
    "home": "s/dashboard",
    "groups": [
      {
        "name": "Start here",
        "items": [
          { "id": "s/dashboard", "icon": "home", "label": "Dashboard" },
          { "id": "s/fees", "icon": "card", "label": "School Fees" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "s/pgcourses", "icon": "book", "label": "Registration & Results" },
          { "id": "s/research", "icon": "flask", "label": "Research & Thesis" },
          { "id": "s/exams", "icon": "cap", "label": "Examinations" },
          { "id": "s/transcript", "icon": "doc", "label": "Transcript" }
        ]
      },
      {
        "name": "Services",
        "items": [
          { "id": "s/wallet", "icon": "swap", "label": "Wallet & Funding" },
          { "id": "s/library", "icon": "book", "label": "Library" },
          { "id": "s/idcard", "icon": "user", "label": "Identity Card" },
          { "id": "s/health", "icon": "heart", "label": "Health" },
          { "id": "s/support", "icon": "life", "label": "Help & Requests" },
          { "id": "s/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      },
      {
        "name": "Account",
        "items": [
          { "id": "s/profile", "icon": "user", "label": "Profile" },
          { "id": "s/biodata", "icon": "doc", "label": "Biodata" },
          { "id": "s/notifications", "icon": "bell", "label": "Notifications" }
        ]
      }
    ]
  },
  "applicant": {
    "label": "Applicant",
    "home": "a/dashboard",
    "groups": [
      {
        "name": "My application",
        "items": [
          { "id": "a/dashboard", "icon": "home", "label": "Overview" },
          { "id": "a/apply", "icon": "doc", "label": "Application Form" },
          { "id": "a/fee", "icon": "card", "label": "Application Fee" }
        ]
      },
      {
        "name": "Screening",
        "items": [
          { "id": "a/screening", "icon": "print", "label": "Screening Slip" },
          { "id": "a/score", "icon": "chart", "label": "Screening Result" }
        ]
      },
      {
        "name": "Admission",
        "items": [
          { "id": "a/status", "icon": "cap", "label": "Admission Status" },
          { "id": "a/accept", "icon": "check", "label": "Accept Your Offer" },
          { "id": "a/clearance", "icon": "shield", "label": "Document Clearance" },
          { "id": "a/matric", "icon": "user", "label": "Matriculation" }
        ]
      }
    ]
  },
  "pgapplicant": {
    "label": "Postgraduate Applicant",
    "home": "pg/home",
    "groups": [
      {
        "name": "My application",
        "items": [
          { "id": "pg/portal", "icon": "home", "label": "Dashboard" },
          { "id": "pg/apply", "icon": "doc", "label": "Apply Form" },
          { "id": "pg/summary", "icon": "print", "label": "Application Summary" }
        ]
      }
    ]
  },
  "pgschool": {
    "label": "Dean, Postgraduate School",
    "home": "r/pgschool",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/pgschool", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/pgcourses", "icon": "book", "label": "Courses" },
          { "id": "t/pgcalendar", "icon": "cal", "label": "Calendar" },
          { "id": "t/pgboard", "icon": "check", "label": "School Board" },
          { "id": "t/pgscores", "icon": "doc", "label": "Course Results" },
          { "id": "t/pgexaminers", "icon": "shield", "label": "External Examiners" },
          { "id": "t/pgpanels", "icon": "doc", "label": "Examination Panels" },
          { "id": "t/graduation", "icon": "cap", "label": "Graduation List" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Results Broadsheet" },
          { "id": "t/pgresearch", "icon": "flask", "label": "Research Desk" },
          { "id": "t/pgclearance", "icon": "check", "label": "Thesis Clearance" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/pgstudents", "icon": "user", "label": "PG Students" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/pgadmissions", "icon": "cap", "label": "Admissions" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "provost": {
    "label": "Provost, College of Health Sciences",
    "home": "r/college",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/college", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/college", "icon": "flask", "label": "College Overview" },
          { "id": "t/collegeexams", "icon": "chart", "label": "Professional Examinations" },
          { "id": "t/collegecalendar", "icon": "calendar", "label": "College Calendar" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/postings", "icon": "calendar", "label": "Postings" },
          { "id": "t/supervision", "icon": "check", "label": "Logbooks" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "collegesecretary": {
    "label": "College Secretary, College of Health Sciences",
    "home": "r/college",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/college", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/college", "icon": "flask", "label": "College Overview" },
          { "id": "t/collegeexams", "icon": "chart", "label": "Professional Examinations" },
          { "id": "t/collegecalendar", "icon": "calendar", "label": "College Calendar" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/postings", "icon": "calendar", "label": "Postings" },
          { "id": "t/supervision", "icon": "check", "label": "Logbooks" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "mbbscoordinator": {
    "label": "MBBS Coordinator, College of Health Sciences",
    "home": "r/mbbscoordinator",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/mbbscoordinator", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/collegesheets", "icon": "chart", "label": "Score Sheet" },
          { "id": "t/collegeexams", "icon": "chart", "label": "Professional Examination" },
          { "id": "t/collegecalendar", "icon": "calendar", "label": "College Calendar" },
          { "id": "t/college", "icon": "flask", "label": "College Overview" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/postings", "icon": "calendar", "label": "Postings" },
          { "id": "t/supervision", "icon": "check", "label": "Logbooks" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "financecontroller": {
    "label": "Finance Controller, College of Health Sciences",
    "home": "r/college",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/college", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/college", "icon": "flask", "label": "College Overview" },
          { "id": "t/collegeexams", "icon": "chart", "label": "Professional Examinations" },
          { "id": "t/collegecalendar", "icon": "calendar", "label": "College Calendar" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/postings", "icon": "calendar", "label": "Postings" },
          { "id": "t/supervision", "icon": "check", "label": "Logbooks" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "pgsecretary": {
    "label": "Secretary, Postgraduate School",
    "home": "r/pgschool",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "r/pgschool", "icon": "home", "label": "Dashboard" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Academic",
        "items": [
          { "id": "t/pgcourses", "icon": "book", "label": "Courses" },
          { "id": "t/pgcalendar", "icon": "cal", "label": "Calendar" },
          { "id": "t/pgregistration", "icon": "book", "label": "Registration" },
          { "id": "t/pgexams", "icon": "cap", "label": "Course Examinations" },
          { "id": "t/pgseminars", "icon": "book", "label": "Research Seminars" },
          { "id": "t/pgpanels", "icon": "doc", "label": "Panels & Viva" },
          { "id": "t/pgexaminers", "icon": "shield", "label": "External Examiners" },
          { "id": "t/pgclearance", "icon": "check", "label": "Thesis Clearance" },
          { "id": "t/pgscores", "icon": "doc", "label": "Course Results" },
          { "id": "t/pgsenate", "icon": "check", "label": "Results to Senate" },
          { "id": "t/broadsheet", "icon": "chart", "label": "Results Broadsheet" },
          { "id": "t/graduation", "icon": "cap", "label": "Graduation List" }
        ]
      },
      {
        "name": "Students",
        "items": [
          { "id": "t/pgstudents", "icon": "user", "label": "PG Students" },
          { "id": "t/matriculation", "icon": "user", "label": "Matriculation" }
        ]
      },
      {
        "name": "Admissions",
        "items": [
          { "id": "t/pgadmissions", "icon": "cap", "label": "Admissions" }
        ]
      },
      {
        "name": "Finance",
        "items": [
          { "id": "t/feesetup", "icon": "card", "label": "Fees" }
        ]
      },
      {
        "name": "Reports",
        "items": [
          { "id": "t/reports", "icon": "chart", "label": "Reports & Returns" },
          { "id": "t/regstudents", "icon": "user", "label": "Student Register" },
          { "id": "t/regstaff", "icon": "user", "label": "Staff Register" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  },
  "ictagent": {
    "label": "ICT Support Agent",
    "home": "t/helpdesk",
    "groups": [
      {
        "name": "Overview",
        "items": [
          { "id": "t/helpdesk", "icon": "life", "label": "ICT Support Desk" },
          { "id": "t/search", "icon": "user", "label": "Search" }
        ]
      },
      {
        "name": "Me",
        "items": [
          { "id": "r/self", "icon": "user", "label": "Leave & Payslip" },
          { "id": "r/tickets", "icon": "server", "label": "ICT Support Tickets" }
        ]
      }
    ]
  }
};
