/**
 * Every office's menu, exactly as the prototype lays it out (proto/part17.html ROLES,
 * generated by the extraction script — do not edit by hand). An office without a
 * menu here gets the fallback in Shell.tsx.
 */
export interface MenuItem { id: string; icon: string; label: string; badge?: string }
export interface MenuGroup { name: string; items: MenuItem[] }
export interface Menu { label: string; home: string; groups: MenuGroup[] }

export const MENUS: Record<string, Menu> = {
  "lecturer": {
    "label": "Lecturer",
    "home": "r/lecturer",
    "groups": [
      {
        "name": "Teaching",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/lecturer",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "r/classlist",
            "icon": "user",
            "label": "Registered students"
          },
          {
            "id": "t/eligibility",
            "icon": "swap",
            "label": "Who may register it"
          },
          {
            "id": "t/lms",
            "icon": "book",
            "label": "Course spaces"
          },
          {
            "id": "r/upload",
            "icon": "box",
            "label": "Upload material"
          },
          {
            "id": "s/timetable",
            "icon": "cal",
            "label": "Teaching timetable"
          }
        ]
      },
      {
        "name": "Assessment",
        "items": [
          {
            "id": "t/sheet",
            "icon": "doc",
            "label": "Score entry",
            "badge": "2"
          },
          {
            "id": "t/bulk",
            "icon": "box",
            "label": "Upload results (bulk)"
          },
          {
            "id": "t/scores",
            "icon": "doc",
            "label": "My score sheets"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/chain",
            "icon": "check",
            "label": "Approval chain"
          },
          {
            "id": "t/cbtbank",
            "icon": "flask",
            "label": "Question bank"
          }
        ]
      },
      {
        "name": "Research",
        "items": [
          {
            "id": "t/projects",
            "icon": "flask",
            "label": "My projects"
          },
          {
            "id": "t/ethics",
            "icon": "scale",
            "label": "Ethics & repository"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "hod": {
    "label": "Head of Department",
    "home": "r/hod",
    "groups": [
      {
        "name": "Department",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/hod",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "r/allocate",
            "icon": "swap",
            "label": "Teaching allocation",
            "badge": "3"
          },
          {
            "id": "t/deptcourses",
            "icon": "book",
            "label": "Department courses",
            "badge": "2"
          },
          {
            "id": "r/classlist",
            "icon": "user",
            "label": "Registered students"
          },
          {
            "id": "t/students",
            "icon": "cap",
            "label": "Students"
          }
        ]
      },
      {
        "name": "Results",
        "items": [
          {
            "id": "t/resultdesk",
            "icon": "check",
            "label": "Result desk",
            "badge": "4"
          },
          {
            "id": "t/approvals",
            "icon": "check",
            "label": "Departmental approvals"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/broadsheet",
            "icon": "chart",
            "label": "Broadsheet"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          },
          {
            "id": "t/scores",
            "icon": "doc",
            "label": "Score sheets"
          }
        ]
      },
      {
        "name": "My teaching",
        "items": [
          {
            "id": "t/sheet",
            "icon": "doc",
            "label": "Score entry",
            "badge": "2"
          },
          {
            "id": "t/bulk",
            "icon": "box",
            "label": "Upload results (bulk)"
          },
          {
            "id": "t/scores",
            "icon": "doc",
            "label": "My score sheets"
          },
          {
            "id": "t/eligibility",
            "icon": "swap",
            "label": "Who may register it"
          },
          {
            "id": "t/lms",
            "icon": "book",
            "label": "Course spaces"
          },
          {
            "id": "r/upload",
            "icon": "box",
            "label": "Upload material"
          },
          {
            "id": "s/timetable",
            "icon": "cal",
            "label": "Teaching timetable"
          }
        ]
      },
      {
        "name": "Staff",
        "items": [
          {
            "id": "t/leave",
            "icon": "cal",
            "label": "Leave requests",
            "badge": "2"
          },
          {
            "id": "t/appraisal",
            "icon": "chart",
            "label": "Appraisal"
          }
        ]
      },
      {
        "name": "Resources",
        "items": [
          {
            "id": "t/requisitions",
            "icon": "box",
            "label": "Requisitions"
          },
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "dean": {
    "label": "Dean",
    "home": "r/dean",
    "groups": [
      {
        "name": "Faculty",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/dean",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/students",
            "icon": "cap",
            "label": "Students"
          },
          {
            "id": "r/allocate",
            "icon": "swap",
            "label": "Teaching allocation"
          }
        ]
      },
      {
        "name": "Faculty Board",
        "items": [
          {
            "id": "t/resultdesk",
            "icon": "check",
            "label": "Result desk",
            "badge": "7"
          },
          {
            "id": "t/approvals",
            "icon": "check",
            "label": "Faculty Board"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/broadsheet",
            "icon": "chart",
            "label": "Broadsheet"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          },
          {
            "id": "t/graduation",
            "icon": "cap",
            "label": "Graduation list"
          }
        ]
      },
      {
        "name": "My teaching",
        "items": [
          {
            "id": "t/sheet",
            "icon": "doc",
            "label": "Score entry"
          },
          {
            "id": "t/bulk",
            "icon": "box",
            "label": "Upload results (bulk)"
          },
          {
            "id": "t/scores",
            "icon": "doc",
            "label": "My score sheets"
          },
          {
            "id": "r/classlist",
            "icon": "user",
            "label": "Registered students"
          },
          {
            "id": "t/eligibility",
            "icon": "swap",
            "label": "Who may register it"
          },
          {
            "id": "t/lms",
            "icon": "book",
            "label": "Course spaces"
          },
          {
            "id": "r/upload",
            "icon": "box",
            "label": "Upload material"
          }
        ]
      },
      {
        "name": "Faculty business",
        "items": [
          {
            "id": "t/budget",
            "icon": "chart",
            "label": "Faculty budget"
          },
          {
            "id": "t/projects",
            "icon": "flask",
            "label": "Research in the faculty"
          },
          {
            "id": "t/requisitions",
            "icon": "box",
            "label": "Requisitions"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "hrm": {
    "label": "Director of Human Resource Management",
    "home": "t/hrm",
    "groups": [
      {
        "name": "Staff movements",
        "items": [
          {
            "id": "t/hrm",
            "icon": "user",
            "label": "Movements",
            "badge": "8"
          },
          {
            "id": "t/movement",
            "icon": "doc",
            "label": "Open a movement"
          },
          {
            "id": "t/staff",
            "icon": "user",
            "label": "Staff records"
          },
          {
            "id": "t/recruit",
            "icon": "user",
            "label": "Recruitment"
          }
        ]
      },
      {
        "name": "Establishment",
        "items": [
          {
            "id": "t/payroll",
            "icon": "card",
            "label": "Payroll"
          },
          {
            "id": "t/leave",
            "icon": "cal",
            "label": "Leave requests",
            "badge": "2"
          },
          {
            "id": "t/appraisal",
            "icon": "chart",
            "label": "Appraisal"
          }
        ]
      },
      {
        "name": "Records",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "housing": {
    "label": "Deputy Registrar (Housing, Welfare and Passages)",
    "home": "t/housing",
    "groups": [
      {
        "name": "Claims",
        "items": [
          {
            "id": "t/housing",
            "icon": "bed",
            "label": "Housing & welfare",
            "badge": "6"
          },
          {
            "id": "t/hostel",
            "icon": "bed",
            "label": "Hostel allocation"
          }
        ]
      },
      {
        "name": "Records",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/staff",
            "icon": "user",
            "label": "Staff records"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "audit": {
    "label": "Director of Internal Audit",
    "home": "t/prepayment",
    "groups": [
      {
        "name": "Pre-payments",
        "items": [
          {
            "id": "t/prepayment",
            "icon": "check",
            "label": "Payment vouchers",
            "badge": "7"
          },
          {
            "id": "t/pv",
            "icon": "doc",
            "label": "A voucher in full"
          },
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          }
        ]
      },
      {
        "name": "Financial operations",
        "items": [
          {
            "id": "t/auditrevenue",
            "icon": "chart",
            "label": "Revenue & student income",
            "badge": "9"
          },
          {
            "id": "t/ledger",
            "icon": "card",
            "label": "Ledger"
          },
          {
            "id": "t/reconcile",
            "icon": "swap",
            "label": "Reconciliation"
          }
        ]
      },
      {
        "name": "Personnel",
        "items": [
          {
            "id": "t/auditpayroll",
            "icon": "chart",
            "label": "Payroll variance",
            "badge": "6"
          },
          {
            "id": "t/auditstaff",
            "icon": "user",
            "label": "Staff movements"
          }
        ]
      },
      {
        "name": "Assets",
        "items": [
          {
            "id": "t/auditassets",
            "icon": "box",
            "label": "Assets register",
            "badge": "!"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "exams": {
    "label": "Exams Officer (Programme)",
    "home": "r/exams",
    "groups": [
      {
        "name": "Examinations",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/exams",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/exams",
            "icon": "flask",
            "label": "CBT sessions",
            "badge": "!"
          },
          {
            "id": "t/cbtbank",
            "icon": "flask",
            "label": "Question bank"
          },
          {
            "id": "r/classlist",
            "icon": "user",
            "label": "Examination roll"
          }
        ]
      },
      {
        "name": "Results",
        "items": [
          {
            "id": "t/scores",
            "icon": "doc",
            "label": "Score sheets",
            "badge": "6"
          },
          {
            "id": "t/chain",
            "icon": "check",
            "label": "Approval chain"
          },
          {
            "id": "t/approvals",
            "icon": "check",
            "label": "Verification queue"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "academic": {
    "label": "Academic Office",
    "home": "r/academic",
    "groups": [
      {
        "name": "Records",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/academic",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/students",
            "icon": "cap",
            "label": "Student records"
          },
          {
            "id": "t/biochange",
            "icon": "user",
            "label": "Biodata changes",
            "badge": "4"
          },
          {
            "id": "r/classlist",
            "icon": "user",
            "label": "Registered students"
          },
          {
            "id": "t/admissions",
            "icon": "doc",
            "label": "Admissions"
          },
          {
            "id": "t/admissionsetup",
            "icon": "doc",
            "label": "Admission settings",
            "badge": "!"
          },
          {
            "id": "t/capsintake",
            "icon": "box",
            "label": "JAMB admission lists",
            "badge": "6"
          },
          {
            "id": "t/applicants",
            "icon": "user",
            "label": "Applicants (post-UTME)"
          },
          {
            "id": "t/merit",
            "icon": "chart",
            "label": "Merit list"
          },
          {
            "id": "t/putme",
            "icon": "doc",
            "label": "Post-UTME scores"
          },
          {
            "id": "t/candidatedata",
            "icon": "user",
            "label": "Passports, DOB & O’Level"
          },
          {
            "id": "t/matriculation",
            "icon": "cap",
            "label": "Matriculation",
            "badge": "!"
          },
          {
            "id": "t/college",
            "icon": "swap",
            "label": "College of Health Sciences"
          }
        ]
      },
      {
        "name": "Calendar",
        "items": [
          {
            "id": "t/session",
            "icon": "cal",
            "label": "Session & semester setup"
          },
          {
            "id": "t/examsession",
            "icon": "cal",
            "label": "Examination sessions"
          }
        ]
      },
      {
        "name": "Credentials",
        "items": [
          {
            "id": "t/clearance",
            "icon": "check",
            "label": "Clearance",
            "badge": "54"
          },
          {
            "id": "t/transcripts",
            "icon": "doc",
            "label": "Transcripts",
            "badge": "9"
          },
          {
            "id": "t/certificates",
            "icon": "cap",
            "label": "Certificates"
          },
          {
            "id": "t/graduation",
            "icon": "cap",
            "label": "Graduation"
          }
        ]
      },
      {
        "name": "Senate business",
        "items": [
          {
            "id": "t/approvals",
            "icon": "check",
            "label": "Results to Senate"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "bursar": {
    "label": "Bursar",
    "home": "r/bursar",
    "groups": [
      {
        "name": "Students' accounts",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/bursar",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/feesetup",
            "icon": "card",
            "label": "Fee setup"
          },
          {
            "id": "t/feesched",
            "icon": "card",
            "label": "Fee schedules"
          },
          {
            "id": "t/gateways",
            "icon": "card",
            "label": "Payment gateways",
            "badge": "!"
          },
          {
            "id": "t/hanging",
            "icon": "alert",
            "label": "Hanging payments",
            "badge": "7"
          },
          {
            "id": "t/exception",
            "icon": "alert",
            "label": "Payment investigation",
            "badge": "!"
          },
          {
            "id": "t/refunds",
            "icon": "swap",
            "label": "Refunds & credits"
          }
        ]
      },
      {
        "name": "NELFUND",
        "items": [
          {
            "id": "t/nelstatus",
            "icon": "user",
            "label": "Applicants & status"
          },
          {
            "id": "t/nelfund",
            "icon": "swap",
            "label": "Remittances & wallets",
            "badge": "7"
          },
          {
            "id": "t/nelmatch",
            "icon": "swap",
            "label": "Match a remittance"
          }
        ]
      },
      {
        "name": "Expenditure and control",
        "items": [
          {
            "id": "t/pv",
            "icon": "doc",
            "label": "Payment vouchers",
            "badge": "1"
          },
          {
            "id": "t/payroll",
            "icon": "card",
            "label": "Payroll",
            "badge": "3"
          },
          {
            "id": "t/budget",
            "icon": "chart",
            "label": "Budget"
          },
          {
            "id": "t/tenders",
            "icon": "box",
            "label": "Tenders"
          }
        ]
      },
      {
        "name": "Cash and final account",
        "items": [
          {
            "id": "t/cashdesk",
            "icon": "card",
            "label": "Cash office & assets"
          },
          {
            "id": "t/ledger",
            "icon": "swap",
            "label": "Transactions & accounts"
          },
          {
            "id": "t/reconcile",
            "icon": "swap",
            "label": "Reconciliation",
            "badge": "12"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "library": {
    "label": "Librarian",
    "home": "t/idcards",
    "groups": [
      {
        "name": "Identity cards",
        "items": [
          {
            "id": "t/idcards",
            "icon": "user",
            "label": "Card printing",
            "badge": "4"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          }
        ]
      },
      {
        "name": "Library",
        "items": [
          {
            "id": "t/circulation",
            "icon": "book",
            "label": "Circulation"
          },
          {
            "id": "t/clearance",
            "icon": "check",
            "label": "Library clearance",
            "badge": "7"
          },
          {
            "id": "t/stores",
            "icon": "box",
            "label": "Stock & acquisitions"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "security": {
    "label": "Chief Security Officer",
    "home": "t/idverify",
    "groups": [
      {
        "name": "The gate",
        "items": [
          {
            "id": "t/idverify",
            "icon": "check",
            "label": "Verify a card"
          },
          {
            "id": "t/idcards",
            "icon": "user",
            "label": "Card collection",
            "badge": "2"
          },
          {
            "id": "t/idlost",
            "icon": "alert",
            "label": "Lost & replacement",
            "badge": "!"
          }
        ]
      },
      {
        "name": "Records",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "facultyexams": {
    "label": "Faculty Exams Officer",
    "home": "t/resultdesk",
    "groups": [
      {
        "name": "Scrutiny",
        "items": [
          {
            "id": "t/resultdesk",
            "icon": "check",
            "label": "Scrutiny desk",
            "badge": "9"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/broadsheet",
            "icon": "chart",
            "label": "Broadsheet"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          }
        ]
      },
      {
        "name": "The faculty",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/scores",
            "icon": "doc",
            "label": "Score sheets"
          },
          {
            "id": "t/exams",
            "icon": "flask",
            "label": "Examinations"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "facultyofficer": {
    "label": "Faculty Officer",
    "home": "t/resultdesk",
    "groups": [
      {
        "name": "Results",
        "items": [
          {
            "id": "t/resultdesk",
            "icon": "check",
            "label": "Result desk",
            "badge": "9"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/broadsheet",
            "icon": "chart",
            "label": "Broadsheet"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          }
        ]
      },
      {
        "name": "The faculty",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/students",
            "icon": "cap",
            "label": "Students"
          },
          {
            "id": "t/matlist",
            "icon": "cap",
            "label": "Registered students",
            "badge": "!"
          },
          {
            "id": "t/scores",
            "icon": "doc",
            "label": "Score sheets"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "records": {
    "label": "Exams & Records",
    "home": "t/examsrec",
    "groups": [
      {
        "name": "Examinations",
        "items": [
          {
            "id": "t/examsrec",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/examsession",
            "icon": "cal",
            "label": "Examination sessions",
            "badge": "!"
          },
          {
            "id": "t/resultdesk",
            "icon": "check",
            "label": "Validation desk",
            "badge": "12"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/college",
            "icon": "swap",
            "label": "College of Health Sciences"
          }
        ]
      },
      {
        "name": "Results",
        "items": [
          {
            "id": "t/broadsheet",
            "icon": "chart",
            "label": "Broadsheets"
          },
          {
            "id": "t/senate",
            "icon": "scale",
            "label": "Senate schedule",
            "badge": "!"
          },
          {
            "id": "t/publish",
            "icon": "bell",
            "label": "Publication"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          }
        ]
      },
      {
        "name": "Credentials",
        "items": [
          {
            "id": "t/transcripts",
            "icon": "doc",
            "label": "Transcripts",
            "badge": "9"
          },
          {
            "id": "t/certificates",
            "icon": "cap",
            "label": "Certificates"
          },
          {
            "id": "t/graduation",
            "icon": "cap",
            "label": "Graduation records"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "dregistrar": {
    "label": "Deputy Registrar (Academic Affairs)",
    "home": "t/mgmt",
    "groups": [
      {
        "name": "Senate business",
        "items": [
          {
            "id": "t/mgmt",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/senate",
            "icon": "scale",
            "label": "Senate schedule",
            "badge": "!"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          }
        ]
      },
      {
        "name": "Records",
        "items": [
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/broadsheet",
            "icon": "chart",
            "label": "Broadsheets"
          },
          {
            "id": "t/transcripts",
            "icon": "doc",
            "label": "Transcripts"
          },
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "dvc": {
    "label": "DVC (Academic)",
    "home": "t/mgmt",
    "groups": [
      {
        "name": "Academic",
        "items": [
          {
            "id": "t/mgmt",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/senate",
            "icon": "scale",
            "label": "Senate schedule"
          },
          {
            "id": "t/mgmt",
            "icon": "home",
            "label": "Management dashboard"
          },
          {
            "id": "t/overview",
            "icon": "chart",
            "label": "Institutional overview"
          }
        ]
      },
      {
        "name": "Reading",
        "items": [
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/broadsheet",
            "icon": "chart",
            "label": "Broadsheets"
          },
          {
            "id": "t/graduation",
            "icon": "cap",
            "label": "Graduation"
          },
          {
            "id": "t/reports",
            "icon": "doc",
            "label": "Reports & returns"
          },
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "super": {
    "label": "Super Administrator",
    "home": "t/setup",
    "groups": [
      {
        "name": "Configuration",
        "items": [
          {
            "id": "t/setup",
            "icon": "server",
            "label": "Setup console"
          },
          {
            "id": "t/session",
            "icon": "cal",
            "label": "Session & semester setup"
          },
          {
            "id": "t/users",
            "icon": "user",
            "label": "Users & roles"
          },
          {
            "id": "t/channels",
            "icon": "bell",
            "label": "Notification channels"
          },
          {
            "id": "t/migration",
            "icon": "box",
            "label": "Data migration",
            "badge": "!"
          },
          {
            "id": "t/platform",
            "icon": "server",
            "label": "Platform"
          },
          {
            "id": "t/api",
            "icon": "swap",
            "label": "Integrations"
          },
          {
            "id": "t/college",
            "icon": "swap",
            "label": "College of Health Sciences"
          }
        ]
      },
      {
        "name": "Assurance",
        "items": [
          {
            "id": "t/audit",
            "icon": "shield",
            "label": "Audit log"
          },
          {
            "id": "t/security",
            "icon": "shield",
            "label": "Security"
          },
          {
            "id": "t/dr",
            "icon": "box",
            "label": "Backups & recovery"
          },
          {
            "id": "t/governance",
            "icon": "scale",
            "label": "Governance"
          }
        ]
      },
      {
        "name": "Reading only",
        "items": [
          {
            "id": "t/pipeline",
            "icon": "swap",
            "label": "Result pipeline"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          }
        ]
      }
    ]
  },
  "registrar": {
    "label": "Registrar",
    "home": "r/registrar",
    "groups": [
      {
        "name": "Registry",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/registrar",
            "icon": "home",
            "label": "Dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/admissions",
            "icon": "doc",
            "label": "Admissions"
          },
          {
            "id": "t/students",
            "icon": "cap",
            "label": "Student records"
          },
          {
            "id": "t/biochange",
            "icon": "user",
            "label": "Biodata changes",
            "badge": "4"
          },
          {
            "id": "t/certificates",
            "icon": "cap",
            "label": "Certificates"
          },
          {
            "id": "t/clearance",
            "icon": "check",
            "label": "Clearance",
            "badge": "54"
          },
          {
            "id": "t/transcripts",
            "icon": "doc",
            "label": "Transcripts",
            "badge": "9"
          },
          {
            "id": "t/college",
            "icon": "swap",
            "label": "College of Health Sciences"
          }
        ]
      },
      {
        "name": "Staff and Council",
        "items": [
          {
            "id": "t/staff",
            "icon": "user",
            "label": "Staff records"
          },
          {
            "id": "t/recruit",
            "icon": "user",
            "label": "Recruitment"
          },
          {
            "id": "t/approvals",
            "icon": "check",
            "label": "Senate business"
          }
        ]
      },
      {
        "name": "Compliance",
        "items": [
          {
            "id": "t/governance",
            "icon": "scale",
            "label": "Data governance",
            "badge": "2"
          },
          {
            "id": "t/audit",
            "icon": "shield",
            "label": "Audit trail"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "ict": {
    "label": "Director of ICT",
    "home": "t/platform",
    "groups": [
      {
        "name": "Service",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/platform",
            "icon": "server",
            "label": "Platform & integrations",
            "badge": "!"
          },
          {
            "id": "t/users",
            "icon": "user",
            "label": "Users & roles",
            "badge": "1"
          },
          {
            "id": "t/gateways",
            "icon": "card",
            "label": "Payment gateways",
            "badge": "!"
          },
          {
            "id": "t/mail",
            "icon": "server",
            "label": "Mail server"
          },
          {
            "id": "t/putme",
            "icon": "doc",
            "label": "Post-UTME scores"
          },
          {
            "id": "t/notify",
            "icon": "bell",
            "label": "Notifications",
            "badge": "!"
          },
          {
            "id": "t/security",
            "icon": "shield",
            "label": "Security posture",
            "badge": "!"
          }
        ]
      },
      {
        "name": "Engineering",
        "items": [
          {
            "id": "t/api",
            "icon": "swap",
            "label": "API management",
            "badge": "2"
          },
          {
            "id": "t/release",
            "icon": "box",
            "label": "Release pipeline"
          },
          {
            "id": "t/dr",
            "icon": "life",
            "label": "Disaster recovery"
          },
          {
            "id": "t/cloud",
            "icon": "chart",
            "label": "Cloud readiness"
          }
        ]
      },
      {
        "name": "Governance",
        "items": [
          {
            "id": "t/audit",
            "icon": "shield",
            "label": "Audit trail"
          },
          {
            "id": "t/governance",
            "icon": "scale",
            "label": "Data governance",
            "badge": "2"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "services": {
    "label": "Support Services",
    "home": "t/clinic",
    "groups": [
      {
        "name": "Student services",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/clinic",
            "icon": "heart",
            "label": "Clinic"
          },
          {
            "id": "t/circulation",
            "icon": "book",
            "label": "Library circulation"
          },
          {
            "id": "t/stores",
            "icon": "box",
            "label": "Stores & assets"
          }
        ]
      },
      {
        "name": "Procurement",
        "items": [
          {
            "id": "t/requisitions",
            "icon": "box",
            "label": "Requisitions"
          },
          {
            "id": "t/tenders",
            "icon": "box",
            "label": "Tenders"
          }
        ]
      },
      {
        "name": "Advancement",
        "items": [
          {
            "id": "t/alumni",
            "icon": "cap",
            "label": "Alumni register"
          }
        ]
      },
      {
        "name": "Me",
        "items": [
          {
            "id": "r/self",
            "icon": "user",
            "label": "Leave & payslip"
          }
        ]
      }
    ]
  },
  "admin": {
    "label": "System Administrator",
    "home": "r/admin",
    "groups": [
      {
        "name": "Institution",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "r/admin",
            "icon": "home",
            "label": "Administrator dashboard"
          },
          {
            "id": "t/records",
            "icon": "chart",
            "label": "Records & queries"
          },
          {
            "id": "t/overview",
            "icon": "chart",
            "label": "Institutional overview"
          },
          {
            "id": "t/reports",
            "icon": "chart",
            "label": "Reports & returns"
          }
        ]
      },
      {
        "name": "Money",
        "items": [
          {
            "id": "t/gateways",
            "icon": "card",
            "label": "Payment gateways",
            "badge": "!"
          },
          {
            "id": "t/mail",
            "icon": "server",
            "label": "Mail server"
          },
          {
            "id": "t/putme",
            "icon": "doc",
            "label": "Post-UTME scores"
          },
          {
            "id": "t/ledger",
            "icon": "swap",
            "label": "Transactions & accounts"
          },
          {
            "id": "t/reconcile",
            "icon": "swap",
            "label": "Reconciliation",
            "badge": "12"
          },
          {
            "id": "t/exception",
            "icon": "alert",
            "label": "Payment investigation"
          },
          {
            "id": "t/feesched",
            "icon": "card",
            "label": "Fee schedules"
          }
        ]
      },
      {
        "name": "Academic",
        "items": [
          {
            "id": "t/clearance",
            "icon": "check",
            "label": "Clearance",
            "badge": "54"
          },
          {
            "id": "t/students",
            "icon": "cap",
            "label": "Student records"
          },
          {
            "id": "t/admissions",
            "icon": "doc",
            "label": "Admissions"
          },
          {
            "id": "r/allocate",
            "icon": "swap",
            "label": "Teaching allocation"
          },
          {
            "id": "t/chain",
            "icon": "doc",
            "label": "Approval chain"
          }
        ]
      },
      {
        "name": "Platform",
        "items": [
          {
            "id": "t/users",
            "icon": "user",
            "label": "Users & roles"
          },
          {
            "id": "t/platform",
            "icon": "server",
            "label": "Platform & integrations"
          },
          {
            "id": "t/security",
            "icon": "shield",
            "label": "Security posture",
            "badge": "!"
          },
          {
            "id": "t/audit",
            "icon": "shield",
            "label": "Audit trail"
          },
          {
            "id": "t/governance",
            "icon": "scale",
            "label": "Data governance",
            "badge": "2"
          }
        ]
      }
    ]
  },
  "vc": {
    "label": "Vice-Chancellor",
    "home": "t/overview",
    "groups": [
      {
        "name": "Institution",
        "items": [
          {
            "id": "t/search",
            "icon": "user",
            "label": "Search"
          },
          {
            "id": "t/overview",
            "icon": "home",
            "label": "Institutional overview"
          },
          {
            "id": "t/reports",
            "icon": "chart",
            "label": "Reports & returns"
          },
          {
            "id": "t/budget",
            "icon": "card",
            "label": "Budget"
          }
        ]
      },
      {
        "name": "Academic",
        "items": [
          {
            "id": "t/approvals",
            "icon": "check",
            "label": "Senate business",
            "badge": "7"
          },
          {
            "id": "t/graduation",
            "icon": "cap",
            "label": "Graduation"
          },
          {
            "id": "t/projects",
            "icon": "flask",
            "label": "Research"
          }
        ]
      },
      {
        "name": "Assurance",
        "items": [
          {
            "id": "t/audit",
            "icon": "shield",
            "label": "Audit trail"
          },
          {
            "id": "t/governance",
            "icon": "scale",
            "label": "Data governance"
          },
          {
            "id": "t/security",
            "icon": "shield",
            "label": "Security posture"
          }
        ]
      }
    ]
  },
  "student": {
    "label": "Student",
    "home": "s/dashboard",
    "groups": [
      {
        "name": "Academic",
        "items": [
          { "id": "s/dashboard", "icon": "home", "label": "Dashboard" },
          { "id": "s/register", "icon": "book", "label": "Course registration" },
          { "id": "s/results", "icon": "cap", "label": "Results" },
          { "id": "s/query", "icon": "alert", "label": "Result query" },
          { "id": "s/carryover", "icon": "swap", "label": "Carryover" },
          { "id": "s/transcript", "icon": "doc", "label": "Transcript" }
        ]
      },
      {
        "name": "Learning",
        "items": [
          { "id": "s/courses", "icon": "book", "label": "My courses" },
          { "id": "s/timetable", "icon": "cal", "label": "Timetable" },
          { "id": "s/attendance", "icon": "check", "label": "Attendance" },
          { "id": "s/exams", "icon": "cap", "label": "Examinations" }
        ]
      },
      {
        "name": "Services",
        "items": [
          { "id": "s/fees", "icon": "card", "label": "Fees & payments" },
          { "id": "s/wallet", "icon": "swap", "label": "NELFUND wallet" },
          { "id": "s/hostel", "icon": "bed", "label": "Hostel" },
          { "id": "s/library", "icon": "book", "label": "Library" },
          { "id": "s/idcard", "icon": "user", "label": "Identity card" },
          { "id": "s/health", "icon": "heart", "label": "Health" },
          { "id": "s/support", "icon": "life", "label": "Help & requests" }
        ]
      },
      {
        "name": "Account",
        "items": [
          { "id": "s/profile", "icon": "user", "label": "Profile" },
          { "id": "s/biodata", "icon": "doc", "label": "Biodata" },
          { "id": "s/notifications", "icon": "bell", "label": "Notifications" }
        ]
      }
    ]
  },
  "applicant": {
    "label": "Applicant",
    "home": "a/dashboard",
    "groups": [
      {
        "name": "My application",
        "items": [
          { "id": "a/dashboard", "icon": "home", "label": "Overview" },
          { "id": "a/apply", "icon": "doc", "label": "Application form" },
          { "id": "a/fee", "icon": "card", "label": "Application fee" }
        ]
      },
      {
        "name": "Screening",
        "items": [
          { "id": "a/screening", "icon": "print", "label": "Screening slip" },
          { "id": "a/score", "icon": "chart", "label": "Screening result" }
        ]
      },
      {
        "name": "Admission",
        "items": [
          { "id": "a/status", "icon": "cap", "label": "Admission status" },
          { "id": "a/accept", "icon": "check", "label": "Accept your offer" },
          { "id": "a/clearance", "icon": "shield", "label": "Document clearance" },
          { "id": "a/matric", "icon": "user", "label": "Matriculation" }
        ]
      }
    ]
  }
};
