/**
 * The topbar title of every route (first drawn from the prototype). The top bar shows the title alone; a page passes a live
 * subtitle (the session, the record, the reference) when it has one.
 */
export const TITLES: Record<string, string> = {
  "x/dashboard": "Examiner workspace",
  "x/projects": "My assigned projects",
  "x/pending": "Pending reviews",
  "x/submitted": "Submitted reviews",
  "x/profile": "My profile",
  "t/extexaminers": "External examiners",
  "t/extappointments": "Examiner appointments",
  "t/extassignments": "Project assignments",
  "t/extassessments": "Assessments",
  "t/extreports": "Examiner reports",
  "t/sheethistory": "Score sheet history",
  "t/coursehistory": "Course history",
  "r/notices": "Notifications",
  "t/myprofile": "My profile",
  "s/pgprogress": "Academic progress",
  "t/collegepayments": "Student payment report",
  "t/deferments": "Deferments",
  "s/deferment": "Deferment",
  "t/studentstats": "Student statistics",
  "t/staffupload": "Non-Academic Staff",
  "s/tickets": "ICT Support",
  "r/tickets": "ICT Support",
  "t/helpdesk": "ICT Support Desk",
  "t/helpdeskreports": "ICT Support Reports",
  "t/helpdesksettings": "ICT Support Settings",
  "t/cohorts": "Student Cohorts",
  "t/helpdeskagents": "Support Agents & Queues",
  "t/helpdeskoffice": "Support Escalations",
  "s/dashboard": "Dashboard",
  "s/register": "Course registration",
  "s/results": "Results",
  "s/research": "Research & thesis",
  "s/pgcourses": "Course registration & results",
  "t/pgcourses": "Postgraduate courses",
  "t/pgstudents": "Postgraduate register",
  "t/pgresearch": "Research desk",
  "t/pgboard": "School Board & awards",
  "t/pgexaminers": "External examiners",
  "t/pgscores": "Course results",
  "s/broadsheet": "Result broadsheet",
  "s/slip": "Semester result",
  "s/form": "Course form",
  "s/fees": "Fees & payments",
  "s/wallet": "Wallet & funding",
  "s/pay": "Payment",
  "s/receipt": "Payment receipt",
  "s/documents": "My documents",
  "t/documents": "Documents office",
  "t/documents-requests": "Document requests",
  "t/documents-register": "Issued documents",
  "t/documents-settings": "Document policies",
  "s/transcript": "Transcript",
  "s/profile": "Profile",
  "s/courses": "My courses",
  "s/timetable": "Timetable",
  "s/attendance": "Attendance",
  "s/exams": "Examinations",
  "s/hostel": "Hostel",
  "t/hostel": "Accommodation",
  "t/hostel-window": "Application window",
  "t/hostel-inventory": "Hostel inventory",
  "t/hostel-applications": "Hostel applications",
  "t/hostel-occupancy": "Occupancy",
  "t/hostel-clearance": "Checkout and clearance",
  "t/hostel-special": "Special allocations",
  "t/hostel-accountability": "Occupancy accountability",
  "t/hostel-import": "Import hostels and rooms",
  "t/hostel-finance": "Hostel finance",
  "t/hostel-discipline": "Discipline and room swaps",
  "t/pv": "Payment voucher",
  "t/hanging": "Hanging payments",
  "t/heldscripts": "Held scripts",
  "t/cashdesk": "Cash office and final account",
  "t/nelstatus": "NELFUND applicants",
  "t/nellegacy": "Old NELFUND payments",
  "t/feesetup": "Fee Setup and Schedule",
  "t/acts": "Session record",
  "s/library": "Library",
  "s/idcard": "Identity card",
  "s/query": "Result query",
  "s/carryover": "Carryover",
  "s/reghistory": "Registration history",
  "t/idcards": "Identity cards",
  "t/idverify": "Verify a card",
  "t/idlost": "Lost & replacement",
  "t/pipeline": "Result pipeline",
  "t/legacy": "Migrate from the old portal",
  "t/resultdesk": "Result desk",
  "t/review": "Result set",
  "t/broadsheet": "Broadsheet",
  "t/senate": "Senate",
  "t/publish": "Publication",
  "t/examsession": "Examination sessions",
  "t/examsrec": "Exams & Records",
  "t/mgmt": "Management dashboard",
  "t/setup": "Setup console",
  "t/overview": "Institutional overview",
  "t/channels": "Notification channels",
  "t/migration": "Data migration",
  "t/session": "Session & semester setup",
  "t/deptcourses": "Department courses",
  "t/structure": "Programme structure",
  "t/allcourses": "All Courses",
  "t/courseupload": "Upload course structure",
  "t/facultyupload": "Faculties",
  "t/programmeupload": "Programmes",
  "t/departmentupload": "Departments",
  "s/health": "Health",
  "s/support": "Help & requests",
  "t/search": "Search",
  "t/records": "Records & queries",
  "s/biodata": "Biodata",
  "t/biochange": "Biodata changes",
  "s/notifications": "Notifications",
  "t/dashboard": "Dashboard",
  "t/lms": "Course spaces",
  "t/scores": "Score sheets",
  "t/sheet": "Score sheet",
  "t/bulk": "Upload results in bulk",
  "t/hrm": "Staff movements",
  "t/movement": "Movement",
  "t/housing": "Housing, welfare and passages",
  "t/eligibility": "Who may register CSC 311",
  "t/matriculation-manage": "Matriculation management",
  "t/matriculation-config": "Matriculation number format",
  "t/matriculation": "Matriculation",
  "t/transfers": "Inter-Departmental Transfer",
  "s/transfer": "Inter-Departmental Transfer",
  "t/matlist": "Students registered in this faculty",
  "t/collegesheets": "Score sheet by level",
  "t/admissionchecking": "Admission Status Checking",
  "t/applicationwindows": "Application Registration Control",
  "t/portalwindows": "Payment & Registration Windows",
  "t/collegerules": "College Rules",
  "t/collegecalendar": "College calendar",
  "t/collegeexams": "Professional examinations",
  "t/supervision": "Postings I supervise",
  "t/postings": "Postings",
  "t/college": "College of Health Sciences",
  "t/prepayment": "Payment vouchers",
  "t/auditrevenue": "Revenue and student income",
  "t/auditpayroll": "Payroll variance",
  "t/auditstaff": "Staff movements",
  "t/auditassets": "Assets register",
  "t/cbtbank": "Question bank",
  "t/exams": "Examinations",
  "t/gateways": "Payment gateways",
  "t/accounts": "Accounting & books",
  "t/ledger": "Transactions & accounts",
  "t/payments": "Payments query",
  "t/paymenthistory": "Payment history",
  "t/clearance": "Clearance",
  "r/admin": "Administrator",
  "r/lecturer": "Lecturer dashboard",
  "r/hod": "Head of Department",
  "r/dean": "Dean",
  "r/exams": "Examinations Officer",
  "r/academic": "Academic Affairs",
  "r/bursar": "Bursary",
  "r/registrar": "Registry",
  "r/classlist": "Registered students",
  "r/allocate": "Teaching allocation",
  "r/siwes": "SIWES supervision",
  "r/mysiwes": "My SIWES students",
  "r/upload": "Upload course material",
  "r/self": "Leave & payslip",
  "t/chain": "Approval chain",
  "t/exception": "Payment investigation",
  "t/approvals": "Result approvals",
  "t/students": "Students",
  "t/student": "ADAMU, Grace Mwuese",
  "t/screeningreview": "Screening review",
  "a/admission": "Your admission",
  "t/admeligibility": "Programme eligibility",
  "t/programmechanges": "Programme changes",
  "t/admissions": "Admissions",
  "t/admissionsetup": "Admission settings",
  "t/capsintake": "JAMB admission lists",
  "t/candidatedata": "Passports, dates of birth and O’Level",
  "t/postutme": "Computed Post-UTME",
  "t/putme-cbt": "Post-UTME CBT schedule",
  "t/putmecbt": "Post-UTME CBT examinations",
  "t/putmebank": "Post-UTME question bank",
  "t/putmescores": "Post-UTME CBT scores",
  "t/putmefiles": "Post-UTME score files",
  "t/screening": "Screening register",
  "t/de-screening": "Direct Entry screening",
  "t/pgadmissions": "Postgraduate admissions",
  "t/transcripts": "Transcript requests",
  "t/certificates": "Certificates",
  "t/graduation": "Graduation",
  "t/feesched": "Fee schedules",
  "t/nelfund": "Sources of funding",
  "t/fundsources": "Funding sources",
  "t/legacyfees": "Old fees history",
  "t/legacygst": "Old GST payments",
  "t/nelmatch": "Unmatched remittances",
  "t/reconcile": "Settlement reconciliation",
  "t/refunds": "Refunds & credits",
  "t/payroll": "Payroll",
  "t/budget": "Budget",
  "t/staff": "Staff records",
  "t/recruit": "Recruitment",
  "t/leave": "Leave",
  "t/appraisal": "Appraisal & promotion",
  "t/requisitions": "Requisitions",
  "t/tenders": "Tenders",
  "t/stores": "Stores & assets",
  "t/circulation": "Circulation & clearance",
  "t/clinic": "Clinic",
  "t/projects": "Projects & grants",
  "t/ethics": "Ethics & repository",
  "t/alumni": "Alumni register",
  "t/users": "Users & roles",
  "t/lecturers": "Upload lecturers",
  "t/audit": "Audit trail",
  "t/governance": "Data governance",
  "t/platform": "Platform & integrations",
  "t/security": "Security posture",
  "t/notify": "Notifications",
  "t/api": "API management",
  "t/release": "Release pipeline",
  "t/dr": "Disaster recovery",
  "t/cloud": "Cloud readiness",
  "t/reports": "Reports & returns",
  "a/dashboard": "My application",
  "a/apply": "Application form",
  "a/fee": "Application fee",
  "a/screening": "Screening slip",
  "a/score": "Screening result",
  "a/status": "Admission status",
  "a/accept": "Accept your offer",
  "a/clearance": "Document clearance",
  "a/matric": "Matriculation",
  "t/teaching": "My teaching & timetable",
  "t/queries": "Result queries",
  "t/deptstaff": "Department staff",
  "t/regstudents": "Student register",
  "t/regstaff": "Staff register",
  "t/migrate": "Migrate old-portal applicants",
  "t/putme": "Upload Post-UTME scores",
  "t/merit": "Merit list",
  "t/applicants": "Post-UTME registration report",
  "t/mail": "Mail server",
  "t/sms": "SMS gateway",
  "t/readiness": "Go-live readiness",
  "pg/portal": "Your postgraduate application",
  "pg/apply": "Apply",
  "pg/summary": "Application summary",
  "r/pgschool": "Postgraduate School",
  "t/pgcalendar": "Postgraduate calendar",
  "t/pgpanels": "Examination panels",
  "t/pgclearance": "Thesis clearance",
  "r/college": "College of Health Sciences",
  "r/mbbscoordinator": "MBBS Coordinator",
  "t/pgregistration": "Postgraduate registration",
  "t/pgexams": "Postgraduate course examinations",
  "t/pgseminars": "Research seminars",
  "t/gststudents": "GST Students",
  "t/gstcourses": "GST Courses",
  "jupeb/cbt": "JUPEB CBT Examinations",
  "jupeb/bank": "JUPEB Question Bank",
  "jupeb/portal/cbt": "CBT Examinations",
  "t/unicbt": "CBT Examinations",
  "t/cbtcourses": "CBT Courses",
  "t/gstbank": "GST Question Bank",
  "t/gstcbt": "GST CBT Examinations",
  "t/epsbank": "EPS Question Bank",
  "t/epscbt": "EPS CBT Examinations",
  "s/cbt": "CBT Examinations",
  "t/epsstudents": "EPS Students",
  "t/epscourses": "EPS Courses",
  "t/pgsenate": "Results to Senate",
};
