/**
 * The topbar titles, every route (proto/part2.html TITLES, generated by the
 * extraction script — do not edit by hand). A screen the portal serves may
 * override its subtitle where the prototype's named an invented figure.
 */
export const TITLES: Record<string, [string, string]> = {
  "s/dashboard": [
    "Dashboard",
    "2026/2027 session · First semester"
  ],
  "s/register": [
    "Course registration",
    "300 Level · First semester"
  ],
  "s/results": [
    "Results",
    "Published semesters"
  ],
  "s/slip": [
    "Semester result",
    "2025/2026 · Second semester"
  ],
  "s/form": [
    "Course form",
    "Approved 15 September 2026"
  ],
  "s/fees": [
    "Fees & payments",
    "2026/2027 session"
  ],
  "s/wallet": [
    "Wallet & funding",
    "Loans, scholarships and other funding paid on your behalf"
  ],
  "s/pay": [
    "Payment",
    "Instalment 2 · school fees"
  ],
  "s/receipt": [
    "Payment receipt",
    ""
  ],
  "s/transcript": [
    "Transcript",
    "Request an official copy"
  ],
  "s/profile": [
    "Profile",
    "Your record with the University"
  ],
  "s/courses": [
    "My courses",
    "2026/2027 · First semester"
  ],
  "s/timetable": [
    "Timetable",
    "Week 3 of 15"
  ],
  "s/attendance": [
    "Attendance",
    "Recorded at each lecture"
  ],
  "s/exams": [
    "Examinations",
    "December 2026 · computer-based"
  ],
  "s/hostel": [
    "Hostel",
    "Akpehe Hall · 2026/2027"
  ],
  "t/hostel": [
    "Hostel and accommodation",
    "Priority by rule, the rest by a ballot anyone can re-run"
  ],
  "t/pv": [
    "Payment voucher",
    "PV/2026/1892 · Expenditure and Control"
  ],
  "t/hanging": [
    "Hanging payments",
    "Successful at the gateway, pending here"
  ],
  "t/cashdesk": [
    "Cash office and final account",
    "Revenue received, and the assets extracted from it"
  ],
  "t/nelstatus": [
    "NELFUND applicants",
    "Approved, not approved, and still with the Fund"
  ],
  "t/feesetup": [
    "Fee setup",
    "Seven dimensions, and two payments it refuses"
  ],
  "t/acts": [
    "Session record",
    "What you have done, and what was refused"
  ],
  "s/library": [
    "Library",
    "Loans, fines and the catalogue"
  ],
  "s/idcard": [
    "Identity card",
    "Issued 18 September 2026 · valid to 31 October 2027"
  ],
  "s/query": [
    "Result query",
    "One mark, one course, answered on the record"
  ],
  "s/carryover": [
    "Carryover",
    "What must be repeated, and when it is next offered"
  ],
  "t/idcards": [
    "Identity cards",
    "Printed by the Library, handed over by Security"
  ],
  "t/idverify": [
    "Verify a card",
    "One scan, one answer"
  ],
  "t/idlost": [
    "Lost & replacement",
    "A reported card stops at every reader"
  ],
  "t/pipeline": [
    "Result pipeline",
    "Student to transcript, in ten stages"
  ],
  "t/resultdesk": [
    "Result desk",
    "The stage this office holds"
  ],
  "t/review": [
    "Result set",
    "Read it, then decide"
  ],
  "t/broadsheet": [
    "Broadsheet",
    "Computed from approved sets, never typed"
  ],
  "t/senate": [
    "Senate",
    "Nothing is published without a minute"
  ],
  "t/publish": [
    "Publication",
    "The embargo lives in the data"
  ],
  "t/examsession": [
    "Examination sessions",
    "The container everything hangs in"
  ],
  "t/examsrec": [
    "Exams & Records",
    "Where a mark becomes a credential"
  ],
  "t/mgmt": [
    "Management dashboard",
    "Read everything, approve what this seat holds"
  ],
  "t/setup": [
    "Setup console",
    "The University as data"
  ],
  "t/overview": [
    "Institutional overview",
    "Data as at 5 September 2026, 06:00"
  ],
  "t/channels": [
    "Notification channels",
    "SMS, e-mail, WhatsApp and push"
  ],
  "t/migration": [
    "Data migration",
    "From the old portal into this one"
  ],
  "t/session": [
    "Session & semester setup",
    "The calendar everything else hangs on"
  ],
  "t/deptcourses": [
    "Department courses",
    "The department owns them, and creates them"
  ],
  "s/health": [
    "Health",
    "University Health Services"
  ],
  "s/support": [
    "Help & requests",
    "Ask an office for help"
  ],
  "t/search": [
    "Search",
    "Find one record"
  ],
  "t/records": [
    "Records & queries",
    "One scope across every list"
  ],
  "s/biodata": [
    "Biodata",
    "Your record, in full"
  ],
  "t/biochange": [
    "Biodata changes",
    "Requests that need evidence"
  ],
  "s/cbt": [
    "Examination",
    "CSC 311 · Algorithms & Complexity"
  ],
  "s/notifications": [
    "Notifications",
    "Messages from the University"
  ],
  "t/dashboard": [
    "Dashboard",
    "Faculty of Science · First semester"
  ],
  "t/lms": [
    "Course spaces",
    "Materials, assignments and engagement"
  ],
  "t/scores": [
    "Score sheets",
    "Courses assigned to you"
  ],
  "t/sheet": [
    "CSC 311 — Algorithms & Complexity",
    "3 credit units · every registered candidate, all programmes"
  ],
  "t/bulk": [
    "Upload results in bulk",
    "Download the template, fill it, upload it — checked before anything is written"
  ],
  "t/hrm": [
    "Staff movements",
    "Seventeen processes, one workflow — and the instrument every office cites"
  ],
  "t/movement": [
    "Movement",
    "Approved is not implemented until the letter exists"
  ],
  "t/housing": [
    "Housing, welfare and passages",
    "Entitlement is verified before the committee sits"
  ],
  "t/eligibility": [
    "Who may register CSC 311",
    "The eligible set, assigned when the course was created"
  ],
  "t/matriculation": [
    "Matriculation",
    "2026/2027 · numbers issued over the confirmed register"
  ],
  "t/transfers": [
    "Inter-departmental transfer",
    "Applications, the committee, Senate and the register"
  ],
  "s/transfer": [
    "Departmental transfer",
    "Apply to move to another department"
  ],
  "t/matlist": [
    "Students registered in this faculty",
    "The list the Academic Office matriculates from"
  ],
  "t/college": [
    "College of Health Sciences",
    "A separate system, and the seam between the two"
  ],
  "t/prepayment": [
    "Payment vouchers",
    "Pre-payment audit · Bursary raises, Audit clears, Bursary pays"
  ],
  "t/auditrevenue": [
    "Revenue and student income",
    "Academic Office, portal and Bursary in one answer"
  ],
  "t/auditpayroll": [
    "Payroll variance",
    "October against September, explained by staff movements"
  ],
  "t/auditstaff": [
    "Staff movements",
    "Seventeen HR processes, and what each does to the payroll"
  ],
  "t/auditassets": [
    "Assets register",
    "With the date each was last physically verified"
  ],
  "t/cbtbank": [
    "Question bank",
    "CSC 311 · authoring and blueprints"
  ],
  "t/exams": [
    "Examinations",
    "Live sessions and invigilation"
  ],
  "t/gateways": [
    "Payment gateways",
    "Providers, keys, routing and webhooks"
  ],
  "t/ledger": [
    "Transactions & accounts",
    "Payment history and the ledger"
  ],
  "t/clearance": [
    "Clearance",
    "Graduation and registration sign-off"
  ],
  "r/admin": [
    "Administrator",
    "The whole institution, at one desk"
  ],
  "r/lecturer": [
    "Lecturer dashboard",
    "Dr. T. Iorpuu · Computer Science · four courses this semester"
  ],
  "r/hod": [
    "Head of Department",
    "Mathematics & Computer Science · the departmental desk"
  ],
  "r/dean": [
    "Dean",
    "Faculty of Science · five departments"
  ],
  "r/exams": [
    "Examinations Officer",
    "B.Sc. Computer Science · verification and the CBT hall"
  ],
  "r/academic": [
    "Academic Affairs",
    "Registration, credentials and Senate business"
  ],
  "r/bursar": [
    "Bursary",
    "Collection, payroll and the returns"
  ],
  "r/registrar": [
    "Registry",
    "Admissions, Council, Senate and data governance"
  ],
  "r/classlist": [
    "Registered students",
    "Generated now, from approved registrations — all of them"
  ],
  "r/allocate": [
    "Teaching allocation",
    "Assigning a lecturer sets the second examiner at the same time"
  ],
  "r/upload": [
    "Upload course material",
    "CSC 311 — Algorithms & Complexity"
  ],
  "r/self": [
    "Leave & payslip",
    "You as an employee of the University"
  ],
  "t/chain": [
    "Approval chain",
    "CSC 311 · Algorithms & Complexity"
  ],
  "t/exception": [
    "Payment investigation",
    "Unmatched settlement · teller slip BR/44821"
  ],
  "t/approvals": [
    "Result approvals",
    "Awaiting Faculty Board"
  ],
  "t/students": [
    "Students",
    "Registry search"
  ],
  "t/student": [
    "ADAMU, Grace Mwuese",
    "MOAUM/CSC/23/1487 · 300 Level"
  ],
  "t/admissions": [
    "Admissions",
    "2026 UTME cycle"
  ],
  "t/admissionsetup": [
    "Admission settings",
    "The Central Admissions Committee’s guidelines, made into settings the portal applies"
  ],
  "t/capsintake": [
    "JAMB admission lists",
    "UTME and Direct Entry · downloaded from CAPS, reconciled both ways"
  ],
  "t/candidatedata": [
    "Passports, dates of birth and O’Level",
    "The three other JAMB downloads · matched on the registration number"
  ],
  "t/transcripts": [
    "Transcript requests",
    "Exams & Records · production queue"
  ],
  "t/certificates": [
    "Certificates",
    "Convocation 2026"
  ],
  "t/graduation": [
    "Graduation",
    "Degree audit and Senate list"
  ],
  "t/feesched": [
    "Fee schedules",
    "Versioned and effective-dated"
  ],
  "t/nelfund": [
    "Sources of funding",
    "Loans, scholarships, wallets, withdrawals and the report"
  ],
  "t/nelmatch": [
    "Unmatched remittances",
    "Money received that is not yet on a wallet"
  ],
  "t/reconcile": [
    "Settlement reconciliation",
    "Remita · 4 September 2026"
  ],
  "t/refunds": [
    "Refunds & credits",
    "Maker–checker controlled"
  ],
  "t/payroll": [
    "Payroll",
    "September 2026 run"
  ],
  "t/budget": [
    "Budget",
    "Financial year 2026"
  ],
  "t/staff": [
    "Staff records",
    "Establishment and appointments"
  ],
  "t/recruit": [
    "Recruitment",
    "2026 cycle"
  ],
  "t/leave": [
    "Leave",
    "Requests and balances"
  ],
  "t/appraisal": [
    "Appraisal & promotion",
    "2026 exercise"
  ],
  "t/requisitions": [
    "Requisitions",
    "Procurement pipeline"
  ],
  "t/tenders": [
    "Tenders",
    "Evaluation and award"
  ],
  "t/stores": [
    "Stores & assets",
    "Inventory and fixed assets"
  ],
  "t/circulation": [
    "Circulation & clearance",
    "University Library"
  ],
  "t/clinic": [
    "Clinic",
    "University Health Services"
  ],
  "t/projects": [
    "Projects & grants",
    "Research administration"
  ],
  "t/ethics": [
    "Ethics & repository",
    "Review and open access"
  ],
  "t/alumni": [
    "Alumni register",
    "104,882 on record"
  ],
  "t/users": [
    "Users & roles",
    "Identity and access management"
  ],
  "t/audit": [
    "Audit trail",
    "Tamper-evident record of every consequential act"
  ],
  "t/governance": [
    "Data governance",
    "Nigeria Data Protection Act 2023"
  ],
  "t/platform": [
    "Platform & integrations",
    "Availability, backups, external services"
  ],
  "t/security": [
    "Security posture",
    "Findings, privileged access, sign-in defence"
  ],
  "t/notify": [
    "Notifications",
    "Templates, delivery and channel health"
  ],
  "t/api": [
    "API management",
    "Consumers, keys, endpoints, versioning"
  ],
  "t/release": [
    "Release pipeline",
    "Build, test, approve, deploy, roll back"
  ],
  "t/dr": [
    "Disaster recovery",
    "Objectives, drills, runbook, dependencies"
  ],
  "t/cloud": [
    "Cloud readiness",
    "Portability under NDPA data residency"
  ],
  "t/reports": [
    "Reports & returns",
    "Regulatory and management reporting"
  ],
  "a/dashboard": [
    "My application",
    "UTME 2026/2027 · APP/2026/018342"
  ],
  "a/apply": [
    "Application form",
    "Biodata, O’Level results and documents"
  ],
  "a/fee": [
    "Application fee",
    "Post-UTME screening · 2026/2027"
  ],
  "a/screening": [
    "Screening slip",
    "Post-UTME · batch C · CBT Hall B"
  ],
  "a/score": [
    "Screening result",
    "Post-UTME 2026/2027"
  ],
  "a/status": [
    "Admission status",
    "UTME 2026/2027"
  ],
  "a/accept": [
    "Accept your offer",
    "B.Sc. Computer Science · 100 Level"
  ],
  "a/clearance": [
    "Document clearance",
    "Registry · Administration Block"
  ],
  "a/matric": [
    "Matriculation",
    "2026/2027 session"
  ]
};
